// GENERATED FILE: python/generate_runtime_abi.py
import Foundation

enum MetalRoboRuntimeABI {
    static let version: UInt32 = 20
    static let worldBufferCount = 254
    static let pipelineCount = 92
    static let pipelineGroupCount = 11
    static let mrSensorProgramAbiVersion: UInt32 = 9
    static let mrSensorDispatchHasResets: UInt32 = 1
    static let mrSensorDispatchHasContacts: UInt32 = 2
    static let mrSensorProgramHeaderGPUSize = 80
    static let mrSensorDescriptorGPUSize = 224
    static let mrSensorDispatchGPUSize = 48
    static let mrSensorRuntimeStateGPUSize = 80
    static let mrSensorSampleMetadataGPUSize = 32
    static let mrActuatorRuntimeStateGPUSize = 64
    static let mrTaskKinematicFrameGPUSize = 32
    static let mrLearningPublicationDispatchGPUSize = 64
    static let mrLearningPublicationStatusGPUSize = 64
    static let worldBufferDebugNames: [String] = [
        "world",
        "articulations",
        "joints",
        "dofs",
        "bodies",
        "aba dispatch",
        "state qa",
        "state va",
        "working effort",
        "body wrench placeholder",
        "candidate acceleration",
        "candidate v",
        "candidate q",
        "aba statuses",
        "state qb",
        "state vb",
        "effort trajectory",
        "reset masks",
        "reset q",
        "reset v",
        "observations",
        "acceleration trajectory",
        "public statuses",
        "world dispatch",
        "environment statuses",
        "checkpoint q",
        "checkpoint v",
        "shapes",
        "materials",
        "scene body indices",
        "eligible pairs",
        "contact dispatch",
        "operator kinematics dispatch",
        "operator factor dispatch",
        "initial scene bodies",
        "reset scene bodies",
        "kinematic targets",
        "scene bodies a",
        "scene bodies b",
        "checkpoint scene bodies",
        "body poses",
        "point world",
        "factor matrix",
        "point jacobians",
        "generalized impulse",
        "delta velocity",
        "operator statuses",
        "current bodies",
        "candidate bodies",
        "manifold headers a",
        "manifold points a",
        "manifold counts a",
        "manifold headers b",
        "manifold points b",
        "manifold counts b",
        "candidate manifold headers",
        "candidate manifold points",
        "candidate manifold counts",
        "checkpoint manifold headers",
        "checkpoint manifold points",
        "checkpoint manifold counts",
        "candidate pairs",
        "raw contacts",
        "raw pair indices",
        "contacts",
        "contact metadata",
        "ir blocks",
        "ir endpoints",
        "ir rows",
        "ir cones",
        "point queries",
        "evaluated rows",
        "evaluated cones",
        "factor caches",
        "islands",
        "response columns",
        "contact statuses",
        "public contact statuses",
        "active indirect dispatch",
        "projected colliders",
        "pair overlap flags",
        "work queue headers",
        "pair work queue",
        "pair raw counts",
        "compaction offsets",
        "compaction scratch",
        "compaction flags",
        "reserved 87",
        "reserved 88",
        "reserved 89",
        "reserved 90",
        "reserved 91",
        "convex caches",
        "ccd pairs",
        "geometry headers",
        "geometry vertices",
        "geometry indices",
        "convex faces",
        "convex half edges",
        "mesh bvh nodes",
        "mesh triangles",
        "pair raw contact staging",
        "reserved 102",
        "reserved 103",
        "future body poses",
        "future projected colliders",
        "candidate convex caches",
        "ccd event states a",
        "ccd event states b",
        "ccd impact clusters",
        "reserved 110",
        "pair manifold headers",
        "pair manifold points",
        "manifold ir scatter",
        "endpoint runtime",
        "quality dispatch",
        "quality blocks",
        "quality dynamics",
        "quality jacobian",
        "quality bias",
        "quality free velocity",
        "quality warm velocity",
        "quality warm impulses",
        "quality output velocity",
        "quality output impulses",
        "quality derivatives",
        "quality hessian",
        "quality statuses",
        "quality work queue",
        "quality work packets",
        "dynamic nodes",
        "body dynamic nodes",
        "island node references",
        "island constraint references",
        "rod factor caches",
        "operator velocity arena",
        "initial rod nodes",
        "initial rod edges",
        "reset rod nodes",
        "reset rod edges",
        "rod nodes a",
        "rod edges a",
        "rod nodes b",
        "rod edges b",
        "checkpoint rod nodes",
        "checkpoint rod edges",
        "rod dispatches",
        "rod rest lengths",
        "rod rest twists",
        "rod rest curvatures",
        "rod inverse masses",
        "rod inverse rotational inertias",
        "rod stretch stiffness",
        "rod bend stiffness",
        "rod twist stiffness",
        "rod input positions",
        "rod input velocities",
        "rod input twists",
        "rod input twist rates",
        "rod output positions",
        "rod output velocities",
        "rod output twists",
        "rod output twist rates",
        "rod statuses",
        "rod attachments",
        "rod reactions",
        "factor matrix staging",
        "point jacobians staging",
        "rod colliders",
        "rod shape sources",
        "rod tool pairs",
        "rod witness counts",
        "rod witnesses a",
        "rod witnesses b",
        "candidate rod witnesses",
        "checkpoint rod witnesses",
        "rod constraint witness indices",
        "rod collision dispatches",
        "rod contact scratch",
        "authored ir blocks",
        "authored ir endpoints",
        "authored ir rows",
        "authored ir cones",
        "authored ir warm impulses",
        "ccd event rod nodes a",
        "ccd event rod edges a",
        "ccd event rod witnesses a",
        "ccd event rod nodes b",
        "ccd event rod edges b",
        "ccd event rod witnesses b",
        "projected rod colliders",
        "future projected rod colliders",
        "actuator profiles",
        "task dispatch",
        "task actions",
        "task state",
        "task action history",
        "task actor history",
        "task clean history",
        "task critic history",
        "task previous joint velocity",
        "task encoder bias",
        "task body parameters",
        "task controller parameters",
        "task actor observations",
        "task critic observations",
        "task transitions",
        "task contact compact",
        "task default q",
        "task program header",
        "task program arena",
        "policy program header a",
        "policy program arena a",
        "policy scratch a",
        "policy scratch b",
        "policy actor mean",
        "policy latents",
        "policy log probabilities",
        "policy values",
        "task curriculum state",
        "generalized warm state",
        "checkpoint generalized warm state",
        "sensor program header",
        "sensor descriptors",
        "sensor runtime states",
        "sensor history",
        "sensor outputs",
        "sensor metadata",
        "policy program header b",
        "policy program arena b",
        "learning publication status",
        "sensor checkpoint states",
        "sensor checkpoint history",
        "sensor checkpoint outputs",
        "sensor checkpoint metadata",
        "checkpoint convex caches",
        "task checkpoint state",
        "task checkpoint action history",
        "task checkpoint actor history",
        "task checkpoint clean history",
        "task checkpoint critic history",
        "task checkpoint previous joint velocity",
        "task checkpoint encoder bias",
        "task checkpoint body parameters",
        "task checkpoint controller parameters",
        "task checkpoint contact compact",
        "sensor filter bodies",
        "actuator runtime states",
        "actuator command history",
        "checkpoint actuator runtime states",
        "checkpoint actuator command history",
        "task kinematic dispatches",
        "task kinematic queries",
        "task kinematic point world",
    ]
}
