"""MetalRobo's native Python and MLX reinforcement-learning interface."""

from .env import FrankaEnv
from .episode import compile_episode_manifest
from .hybrid_renderer import (
    GAUSSIAN_ASSET_LOCAL,
    GAUSSIAN_BODY_LOCAL,
    GAUSSIAN_WORLD,
    HYBRID_GAUSSIAN_DTYPE,
    HybridObservationDeviceBuffers,
    HybridObservationRenderer,
    HybridObservationSnapshot,
    HybridRendererLayout,
    make_asset_gaussians,
)
from .native import (
    MetalRoboError,
    NativeRuntime,
    RuntimeStats,
    library_version,
)
from .mlx_world import (
    ContactEvidence,
    ControllerDelayState,
    MLXCompiledWorld,
    MetalWorldCapacityProfile,
    SampledWorldFamilyState,
    SampledWorldStepOutput,
    RodState,
    ScenarioState,
    SceneBodyState,
    SolverCache,
    StepOutput,
    WorldState,
    WorldPhysicalParameters,
    compile_world,
    initial_state,
    initial_controller_delay_state,
    initial_state_from_world_family,
    reset_sampled_world_family,
    sampled_state_from_world_family,
    step,
    step_sampled_world_family,
)
from .mlx_multi_articulated import (
    GeneralizedConstraintOutput,
    MLXCompiledMultiArticulatedProgram,
    compile_program as compile_multi_articulated_program,
    step as step_multi_articulated,
)
from .worlds import (
    FrankaPickPlaceWorldFamily,
    PackedWorldFamily,
    ScenarioFeature,
    ScenarioSchema,
)
from .mlx_ppo import (
    MLXPPOTrainer,
    MLXRolloutBatch,
    MLXRolloutCollector,
    MLXRolloutState,
)
from .mlx_family_ppo import (
    MLXFamilyRolloutBatch,
    MLXFamilyRolloutState,
    MLXWorldFamilyPPOTrainer,
    MLXWorldFamilyRolloutCollector,
)
from .mlx_locomotion import (
    MLXG1PPOTrainer,
    MLXG1RolloutCollector,
)
from .mlx_surgical import (
    MLXPSMNeedlePPOTrainer,
    MLXPSMNeedleRolloutCollector,
    psm_physical_position_targets,
)
from .ppo import ActorCritic, PPOConfig, PPOTrainer
from .r2s2r import (
    AlignmentArtifact,
    ArtifactRef,
    ContentAddressedArtifactStore,
    EpisodeOutcome,
    FeedbackArtifact,
    PolicyDescriptor,
    R2S2RCoordinator,
    drain_completed_episode_records,
    make_affine_replay_evaluator,
)
from .mlx_r2s2r import (
    AlignmentPopulationArrays,
    CompactedEpisodeRecords,
    EpisodeAccumulator,
    FailureScores,
    FailureTrainingBatch,
    FiveMemberFailureEnsemble,
    QuantileRegion,
    ReplayEvaluation,
    SMCConfig,
    accumulate_episode_evidence,
    compile_feedback_regions,
    compact_completed_episodes,
    deterministic_candidate_scenarios,
    fit_alignment_smc,
    initial_episode_accumulator,
    reset_episode_accumulator,
)
from .mlx_replay import (
    MLXPhysicalReplayEvaluator,
    PhysicalReplayTrace,
    ReplayResidualScales,
)
from .mlx_manipulation import (
    AdaptedFrankaAction,
    CartesianActionAdapterConfig,
    FrankaActionAdapter,
    FrankaActionMode,
    FrankaPickPlaceTaskConfig,
    FrankaPickPlaceTaskState,
    FrankaTaskEvidence,
    FrankaTaskPhase,
    OperationalSpaceImpedanceConfig,
    adapt_cartesian_action,
    adapt_joint_position_action,
    adapt_operational_space_action,
    franka_kinematics,
    initial_franka_pick_place_task,
    step_franka_pick_place_task,
)
from .mlx_world_step import WorldStepRequest, WorldStepResult
from .mlx_teacher import (
    FrankaPrivilegedTeacherConfig,
    PrivilegedTeacherAction,
    privileged_franka_teacher_action,
)

__all__ = [
    "ActorCritic",
    "AdaptedFrankaAction",
    "AlignmentArtifact",
    "AlignmentPopulationArrays",
    "ArtifactRef",
    "CompactedEpisodeRecords",
    "ContactEvidence",
    "CartesianActionAdapterConfig",
    "ControllerDelayState",
    "ContentAddressedArtifactStore",
    "EpisodeOutcome",
    "EpisodeAccumulator",
    "FailureScores",
    "FailureTrainingBatch",
    "FeedbackArtifact",
    "FiveMemberFailureEnsemble",
    "FrankaEnv",
    "FrankaActionAdapter",
    "FrankaActionMode",
    "FrankaPickPlaceTaskConfig",
    "FrankaPickPlaceTaskState",
    "FrankaPickPlaceWorldFamily",
    "FrankaPrivilegedTeacherConfig",
    "FrankaTaskEvidence",
    "FrankaTaskPhase",
    "GAUSSIAN_ASSET_LOCAL",
    "GAUSSIAN_BODY_LOCAL",
    "GAUSSIAN_WORLD",
    "HYBRID_GAUSSIAN_DTYPE",
    "HybridObservationDeviceBuffers",
    "HybridObservationRenderer",
    "HybridObservationSnapshot",
    "HybridRendererLayout",
    "GeneralizedConstraintOutput",
    "MetalRoboError",
    "MLXCompiledMultiArticulatedProgram",
    "MLXCompiledWorld",
    "MLXFamilyRolloutBatch",
    "MLXFamilyRolloutState",
    "MLXG1PPOTrainer",
    "MLXG1RolloutCollector",
    "MLXPSMNeedlePPOTrainer",
    "MLXPSMNeedleRolloutCollector",
    "MLXPhysicalReplayEvaluator",
    "MetalWorldCapacityProfile",
    "MLXPPOTrainer",
    "MLXRolloutBatch",
    "MLXRolloutCollector",
    "MLXRolloutState",
    "MLXWorldFamilyPPOTrainer",
    "MLXWorldFamilyRolloutCollector",
    "NativeRuntime",
    "OperationalSpaceImpedanceConfig",
    "PPOConfig",
    "PPOTrainer",
    "PackedWorldFamily",
    "PolicyDescriptor",
    "PrivilegedTeacherAction",
    "PhysicalReplayTrace",
    "QuantileRegion",
    "RodState",
    "R2S2RCoordinator",
    "ReplayResidualScales",
    "ReplayEvaluation",
    "RuntimeStats",
    "SMCConfig",
    "SampledWorldFamilyState",
    "SampledWorldStepOutput",
    "ScenarioState",
    "SceneBodyState",
    "ScenarioFeature",
    "ScenarioSchema",
    "SolverCache",
    "StepOutput",
    "WorldState",
    "WorldPhysicalParameters",
    "WorldStepRequest",
    "WorldStepResult",
    "adapt_cartesian_action",
    "adapt_joint_position_action",
    "adapt_operational_space_action",
    "compile_world",
    "compile_multi_articulated_program",
    "compile_episode_manifest",
    "accumulate_episode_evidence",
    "compile_feedback_regions",
    "compact_completed_episodes",
    "deterministic_candidate_scenarios",
    "drain_completed_episode_records",
    "fit_alignment_smc",
    "franka_kinematics",
    "initial_state",
    "initial_controller_delay_state",
    "initial_episode_accumulator",
    "initial_franka_pick_place_task",
    "initial_state_from_world_family",
    "library_version",
    "make_asset_gaussians",
    "make_affine_replay_evaluator",
    "psm_physical_position_targets",
    "privileged_franka_teacher_action",
    "reset_sampled_world_family",
    "reset_episode_accumulator",
    "sampled_state_from_world_family",
    "step",
    "step_franka_pick_place_task",
    "step_multi_articulated",
    "step_sampled_world_family",
]

__version__ = "0.4.0"
