#!/usr/bin/env python3
"""Cook and audit compound convex collision from Unitree's official G1 meshes.

The checked-in runtime data is generated by this tool from the pinned
``unitree_ros`` source revision documented in ``G1.cpp``. Deterministic
two-piece V-HACD preserves authored concavities while keeping the complete G1
below the native 64-collider topology limit. Each piece is then compacted with
aspect-ratio-normalized farthest-point sampling for inexpensive online support
mapping.

``trimesh``, ``vhacdx==0.0.10``, and ``scipy`` are cook-time-only
dependencies.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import trimesh
from scipy.spatial import ConvexHull


SOURCE_REVISION = "aa0f5c68b5aba347bad409e71b6430407da758d7"
TARGET_VOLUME_RATIO = 0.97
TARGET_VERTEX_COUNTS = (48, 64, 80, 96, 112, 128)
VHACD_VERSION = "0.0.10"
VHACD_PARAMETERS = {
    "maxConvexHulls": 2,
    "resolution": 200_000,
    "minimumVolumePercentErrorAllowed": 1.0,
    "maxRecursionDepth": 8,
    "shrinkWrap": True,
    "fillMode": "flood",
    "maxNumVerticesPerCH": 64,
    "asyncACD": False,
    "minEdgeLength": 2,
    "findBestPlane": True,
}


@dataclass(frozen=True)
class MeshSource:
    name: str
    body_index: int
    fixed_offset: tuple[float, float, float] = (0.0, 0.0, 0.0)


MESH_SOURCES = (
    MeshSource("pelvis_contour_link.STL", 0),
    MeshSource("left_hip_pitch_link.STL", 1),
    MeshSource("left_hip_roll_link.STL", 2),
    MeshSource("left_hip_yaw_link.STL", 3),
    MeshSource("left_knee_link.STL", 4),
    MeshSource("left_ankle_pitch_link.STL", 5),
    MeshSource("right_hip_pitch_link.STL", 7),
    MeshSource("right_hip_roll_link.STL", 8),
    MeshSource("right_hip_yaw_link.STL", 9),
    MeshSource("right_knee_link.STL", 10),
    MeshSource("right_ankle_pitch_link.STL", 11),
    MeshSource("torso_link_rev_1_0.STL", 15),
    MeshSource("logo_link.STL", 15, (0.0039635, 0.0, -0.044)),
    MeshSource("head_link.STL", 15, (0.0039635, 0.0, -0.044)),
    MeshSource("left_shoulder_yaw_link.STL", 18),
    MeshSource("left_elbow_link.STL", 19),
    MeshSource("left_wrist_roll_link.STL", 20),
    MeshSource("left_wrist_pitch_link.STL", 21),
    MeshSource("left_wrist_yaw_link.STL", 22),
    MeshSource("right_shoulder_yaw_link.STL", 25),
    MeshSource("right_elbow_link.STL", 26),
    MeshSource("right_wrist_roll_link.STL", 27),
    MeshSource("right_wrist_pitch_link.STL", 28),
    MeshSource("right_wrist_yaw_link.STL", 29),
)


@dataclass
class CookedHull:
    source: MeshSource
    source_element: int
    piece_index: int
    piece_count: int
    source_hash: str
    source_vertices: int
    source_triangles: int
    authored_hull_vertices: int
    authored_hull_triangles: int
    center: np.ndarray
    lower: np.ndarray
    extent: np.ndarray
    quantized_vertices: np.ndarray
    triangles: np.ndarray
    volume_ratio: float


def _canonical_vertices(vertices: np.ndarray) -> np.ndarray:
    finite = np.asarray(vertices, dtype=np.float64)
    if finite.ndim != 2 or finite.shape[1] != 3:
        raise ValueError("mesh vertices must have shape [N, 3]")
    if not np.isfinite(finite).all():
        raise ValueError("mesh contains non-finite vertices")
    return np.unique(finite, axis=0)


def _farthest_point_indices(
    vertices: np.ndarray,
    target_count: int,
) -> np.ndarray:
    lower = vertices.min(axis=0)
    extent = np.maximum(vertices.max(axis=0) - lower, 1.0e-12)
    normalized = (vertices - lower) / extent

    selected: list[int] = []
    for axis in range(3):
        for index in (
            int(np.argmin(normalized[:, axis])),
            int(np.argmax(normalized[:, axis])),
        ):
            if index not in selected:
                selected.append(index)

    distance = np.full(len(vertices), np.inf, dtype=np.float64)
    for index in selected:
        delta = normalized - normalized[index]
        distance = np.minimum(
            distance,
            np.einsum("ij,ij->i", delta, delta),
        )
    while len(selected) < min(target_count, len(vertices)):
        index = int(np.argmax(distance))
        selected.append(index)
        delta = normalized - normalized[index]
        distance = np.minimum(
            distance,
            np.einsum("ij,ij->i", delta, delta),
        )
    return np.asarray(selected, dtype=np.int64)


def _canonical_triangles(points: np.ndarray) -> np.ndarray:
    hull = ConvexHull(points)
    used = np.unique(hull.simplices.reshape(-1))
    canonical_points = points[used]
    order = np.lexsort(
        (
            canonical_points[:, 2],
            canonical_points[:, 1],
            canonical_points[:, 0],
        )
    )
    canonical_points = canonical_points[order]
    hull = ConvexHull(canonical_points)
    triangles = np.sort(hull.simplices.astype(np.uint8), axis=1)
    triangles = np.unique(triangles, axis=0)
    triangle_order = np.lexsort(
        (triangles[:, 2], triangles[:, 1], triangles[:, 0])
    )
    return canonical_points, triangles[triangle_order]


def _cook_piece(
    source: MeshSource,
    source_element: int,
    source_hash: str,
    source_mesh: trimesh.Trimesh,
    piece_mesh: trimesh.Trimesh,
) -> CookedHull:
    authored = piece_mesh.convex_hull
    authored_vertices = _canonical_vertices(authored.vertices)
    authored_volume = float(ConvexHull(authored_vertices).volume)
    if not authored_volume > 0.0:
        raise ValueError(f"{source.name} contains a degenerate V-HACD piece")

    compact = None
    ratio = 0.0
    for target_count in TARGET_VERTEX_COUNTS:
        selected = authored_vertices[
            _farthest_point_indices(authored_vertices, target_count)
        ]
        candidate = ConvexHull(selected)
        ratio = float(candidate.volume / authored_volume)
        compact = selected[np.unique(candidate.simplices.reshape(-1))]
        if ratio >= TARGET_VOLUME_RATIO:
            break
    assert compact is not None

    raw_lower = compact.min(axis=0)
    raw_upper = compact.max(axis=0)
    raw_center = 0.5 * (raw_lower + raw_upper)
    centered = compact - raw_center
    lower = centered.min(axis=0)
    extent = centered.max(axis=0) - lower
    if np.any(extent <= 0.0):
        raise ValueError(f"{source.name} has a zero hull extent")

    quantized = np.rint(
        (centered - lower) / extent * 65535.0
    ).astype(np.uint16)
    quantized = np.unique(quantized, axis=0)
    reconstructed = (
        lower
        + quantized.astype(np.float64) / 65535.0 * extent
    )
    reconstructed, triangles = _canonical_triangles(reconstructed)
    quantized = np.rint(
        (reconstructed - lower) / extent * 65535.0
    ).astype(np.uint16)
    reconstructed = (
        lower
        + quantized.astype(np.float64) / 65535.0 * extent
    )
    final_volume = float(ConvexHull(reconstructed).volume)
    ratio = final_volume / authored_volume
    if ratio < 0.94:
        raise ValueError(
            f"{source.name} retained only {ratio:.4f} of a V-HACD piece"
        )

    return CookedHull(
        source=source,
        source_element=source_element,
        piece_index=0,
        piece_count=0,
        source_hash=source_hash,
        source_vertices=len(source_mesh.vertices),
        source_triangles=len(source_mesh.faces),
        authored_hull_vertices=len(authored.vertices),
        authored_hull_triangles=len(authored.faces),
        center=raw_center + np.asarray(source.fixed_offset),
        lower=lower,
        extent=extent,
        quantized_vertices=quantized,
        triangles=triangles,
        volume_ratio=ratio,
    )


def cook_mesh(
    source: MeshSource,
    source_element: int,
    mesh_path: Path,
) -> list[CookedHull]:
    source_bytes = mesh_path.read_bytes()
    mesh = trimesh.load_mesh(mesh_path, process=True)
    if not isinstance(mesh, trimesh.Trimesh):
        raise ValueError(f"{source.name} did not resolve to one triangle mesh")
    decomposed = trimesh.decomposition.convex_decomposition(
        mesh,
        **VHACD_PARAMETERS,
    )
    if len(decomposed) != 2:
        raise ValueError(
            f"{source.name} produced {len(decomposed)} pieces instead of 2"
        )
    source_hash = hashlib.sha256(source_bytes).hexdigest()
    pieces = [
        _cook_piece(
            source,
            source_element,
            source_hash,
            mesh,
            trimesh.Trimesh(**piece, process=False),
        )
        for piece in decomposed
    ]
    pieces.sort(
        key=lambda piece: (
            tuple(float(value) for value in piece.center),
            hashlib.sha256(
                piece.quantized_vertices.tobytes()
                + piece.triangles.tobytes()
            ).hexdigest(),
        )
    )
    for index, piece in enumerate(pieces):
        piece.piece_index = index
        piece.piece_count = len(pieces)
    return pieces


def _format_float(value: float) -> str:
    text = f"{float(value):.9g}"
    if "." not in text and "e" not in text:
        text += ".0"
    return text + "f"


def _format_array(
    values: list[int],
    *,
    suffix: str,
    columns: int,
) -> list[str]:
    lines = []
    for begin in range(0, len(values), columns):
        chunk = values[begin : begin + columns]
        lines.append(
            "    "
            + ", ".join(f"{value}{suffix}" for value in chunk)
            + ","
        )
    return lines


def emit_cpp(hulls: list[CookedHull]) -> str:
    vertex_values: list[int] = []
    index_values: list[int] = []
    record_lines: list[str] = []
    audit_hasher = hashlib.sha256()
    audit_hasher.update(
        json.dumps(
            {
                "vhacdx": VHACD_VERSION,
                "parameters": VHACD_PARAMETERS,
            },
            sort_keys=True,
        ).encode("utf-8")
    )
    for hull in hulls:
        vertex_offset = len(vertex_values) // 3
        index_offset = len(index_values)
        vertex_values.extend(
            int(value)
            for value in hull.quantized_vertices.reshape(-1)
        )
        index_values.extend(
            int(value)
            for value in hull.triangles.reshape(-1)
        )
        audit_hasher.update(bytes.fromhex(hull.source_hash))
        audit_hasher.update(hull.quantized_vertices.tobytes())
        audit_hasher.update(hull.triangles.tobytes())
        center = ", ".join(_format_float(v) for v in hull.center)
        lower = ", ".join(_format_float(v) for v in hull.lower)
        extent = ", ".join(_format_float(v) for v in hull.extent)
        record_lines.extend(
            (
                "    {",
                (
                    f'        "{hull.source.name}", '
                    f"{hull.source_element}u, "
                    f"{hull.piece_index}u, {hull.piece_count}u,"
                ),
                f"        {hull.source.body_index}u,",
                f"        {{{center}}},",
                f"        {{{lower}}},",
                f"        {{{extent}}},",
                (
                    f"        {vertex_offset}u, "
                    f"{len(hull.quantized_vertices)}u, "
                    f"{index_offset}u, {hull.triangles.size}u,"
                ),
                f"        {_format_float(hull.volume_ratio)},",
                f'        "{hull.source_hash}",',
                "    },",
            )
        )

    lines = [
        "// Generated by python/probes/g1_collision_hull_audit.py.",
        "// Source: unitreerobotics/unitree_ros, BSD-3-Clause, commit",
        f"// {SOURCE_REVISION}. Do not hand-edit.",
        (
            f"// V-HACD wrapper vhacdx {VHACD_VERSION}; "
            "two deterministic pieces per official mesh."
        ),
        f'constexpr std::string_view kG1CollisionHullCookHash = "{audit_hasher.hexdigest()}";',
        (
            "constexpr std::size_t kG1CollisionHullPieceCount = "
            f"{len(hulls)}u;"
        ),
        (
            "constexpr std::array<G1CollisionHullRecord, "
            "kG1CollisionHullPieceCount> kG1CollisionHulls{{"
        ),
        *record_lines,
        "}};",
        "",
        (
            "constexpr std::array<std::uint16_t, "
            f"{len(vertex_values)}> kG1CollisionHullVertices{{{{"
        ),
        *_format_array(vertex_values, suffix="u", columns=12),
        "}};",
        "",
        (
            "constexpr std::array<std::uint8_t, "
            f"{len(index_values)}> kG1CollisionHullIndices{{{{"
        ),
        *_format_array(index_values, suffix="u", columns=18),
        "}};",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("mesh_directory", type=Path)
    parser.add_argument("--emit-cpp", action="store_true")
    args = parser.parse_args()

    hulls = [
        hull
        for source_element, source in enumerate(MESH_SOURCES)
        for hull in cook_mesh(
            source,
            source_element,
            args.mesh_directory / source.name,
        )
    ]
    if args.emit_cpp:
        print(emit_cpp(hulls), end="")
        return 0

    records = []
    for hull in hulls:
        records.append(
            {
                "mesh": hull.source.name,
                "source_element": hull.source_element,
                "piece": hull.piece_index,
                "piece_count": hull.piece_count,
                "source_sha256": hull.source_hash,
                "source_vertices": hull.source_vertices,
                "source_triangles": hull.source_triangles,
                "hull_vertices": hull.authored_hull_vertices,
                "hull_triangles": hull.authored_hull_triangles,
                "compact_vertices": len(hull.quantized_vertices),
                "compact_triangles": len(hull.triangles),
                "volume_ratio": hull.volume_ratio,
            }
        )
    print(json.dumps(records, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
