"use strict";
// Objectives, predictions and selection scores belong to NumiVivo. This view
// only edits the typed objective and links candidate inspection to its record.
window.interventionDesign=(()=>{
  let data,preview=null,record=null,selected=null,root,busy=false;
  const e=id=>document.getElementById('design-'+id);
  const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  const api=async(action,body)=>{const r=await fetch('/api/design'+(action?'/'+action:''),{method:body?'POST':'GET',headers:{'X-Wet-Lab-Token':window.WET_LAB_TOKEN,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error);return d;};
  const fmt=x=>x==null?'UNAVAILABLE':Number(x).toFixed(4);
  const selection=()=>({context:e('context').value,objective:{genes:e('genes').value.split(',').map(s=>s.trim()).filter(Boolean),preserveGenes:[],penalty:0}});
  function status(text){e('status').textContent=text;}
  async function action(fn){if(busy)return;busy=true;root.querySelectorAll('button,input,select').forEach(n=>n.disabled=true);try{await fn();}catch(err){status(err.message);}finally{busy=false;root.querySelectorAll('button,input,select').forEach(n=>n.disabled=false);e('reveal').disabled=!record||record.revealed;e('verify').disabled=!record;e('seal').disabled=!preview;e('preserve').disabled=true;}}
  function inspect(target){selected=target;const row=preview.rankedCandidates.find(r=>r.target===target);const container=e('inspection');container.replaceChildren(node('h3',target==='no-intervention'?'No intervention':target+' · '+data.contexts.find(c=>c.id===preview.selection.context)?.modality));
    container.append(node('p',`Predicted utility ${fmt(row.predictedUtility)} · ${row.contributingControls} control cells · ${row.contributingTreated} measured eligible cells · transfer uncertainty UNQUALIFIED`));
    const p=preview.distributions[target],o=record?.comparison?.distributions[target];
    if(p){const table=node('table');table.innerHTML='<thead><tr><th>Gene</th><th>Control</th><th>Predicted</th><th>Measured</th><th>Residual</th></tr></thead>';const body=node('tbody');preview.selection.objective.genes.forEach((g,i)=>{const tr=node('tr');[g,fmt(p.control[i]),fmt(p.predicted[i]),fmt(o?.mean[i]),fmt(o? p.predicted[i]-o.mean[i]:null)].forEach(v=>tr.append(node('td',v)));body.append(tr);});table.append(body);container.append(table,node('p','Values: mean log1p(CPM). Residual = predicted − measured. Predicted cell variance is uncalibrated dispersion, not confidence in this population mean.','small'));
      const plot=node('canvas');plot.width=700;plot.height=170;plot.setAttribute('aria-label','Shared-scale molecular response distributions');container.append(plot);const ctx=plot.getContext('2d');const vals=[...p.control,...p.predicted,...(o?.mean||[])],lo=Math.min(0,...vals)-1,hi=Math.max(...vals)+1;const x=v=>100+(v-lo)/(hi-lo)*570;
      preview.selection.objective.genes.forEach((g,i)=>{const y=25+i*30;ctx.fillStyle='#233d36';ctx.fillText(g,5,y+4);for(const [v,color,dy] of [[p.control[i],'#5b766f',-6],[p.predicted[i],'#bd7840',0],[o?.mean[i],'#16847b',6]])if(v!=null){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x(v),y+dy,3.5,0,Math.PI*2);ctx.fill();}});
    }else container.append(node('p','Explicit reference option: molecular change and preservation penalty are zero.'));
    container.append(node('p','Receiving-population effects: UNAVAILABLE in this dissociated assay. The tissue below remains the separately labelled spatial development specimen.','small'));
  }
  function render(){if(!preview)return;e('result').hidden=false;e('conclusion').textContent=preview.conclusion;e('equation').textContent=preview.objectiveEquation;const table=e('candidates');table.replaceChildren();
    for(const row of preview.rankedCandidates){const tr=node('tr'),b=node('button',row.target==='no-intervention'?'No intervention':row.target);b.onclick=()=>inspect(row.target);const cell=node('td');cell.append(b);tr.append(cell);[fmt(row.predictedUtility),fmt(row.programDelta),`${fmt(row.modelRange[0])} … ${fmt(row.modelRange[1])}`,record?.revealed?fmt(record.comparison.observedUtilities[row.target]):'Sealed',row.support].forEach(v=>tr.append(node('td',v)));table.append(tr);}
    e('seal').disabled=false;e('reveal').disabled=!record||record.revealed;e('verify').disabled=!record;inspect(selected&&preview.candidates.includes(selected)?selected:preview.numericalChoice);
    const scores=e('scores');scores.replaceChildren();if(record?.revealed){const s=record.comparison.selectionResults['target-descriptor'];scores.append(node('h3','Did the choice help?'),node('p',`Numerical choice: ${s.selected}. Observed utility ${fmt(s.selectedObservedUtility)}. Best measured eligible candidate: ${s.bestObservedEligible}. Regret ${fmt(s.regret)}.`));
      scores.append(node('p',`Gain over random: ${fmt(s.gainOverRandom)} · training-mean ranking: ${fmt(s.gainOverTrainingMean)} · no intervention: ${fmt(s.gainOverNoIntervention)}`));
      const diagnoses=[];if(s.gainOverRandom<=0)diagnoses.push('The selected intervention did not beat uniform random selection.');if(s.gainOverTrainingMean<=0)diagnoses.push('The training-mean ranking was at least as useful.');if(s.gainOverNoIntervention<=0)diagnoses.push('The observed molecular objective did not improve over no intervention.');scores.append(node('p',diagnoses.join(' ')||'The observed selection gains are positive in this context; independent transfer confidence remains unavailable.'));
      const a=record.comparison.acquisition;scores.append(node('p',`Measurement prioritization backtest, budget ${a.budget}: disagreement regret ${fmt(a.policies.disagreement.regret)}, coverage regret ${fmt(a.policies.coverage.regret)}, random mean regret ${fmt(a.randomMeanRegret)}. Active-learning benefit is not established.`));}
  }
  async function mount(parent){data=await api();if(!data.available)return;if(e('root')){root=e('root');return;}root=node('section',undefined,'panel design-workspace');root.id='design-root';parent.prepend(root);root.innerHTML=`
    <div class="eyebrow">INTERVENTION DESIGN · v0.4 EXPERIMENTAL</div><h1>Which intervention should we test?</h1><p>Define an RNA objective. Compare the evidence. Seal the choice before revealing measurements.</p>
    <div class="design-controls"><label>Receiving population / assay context<select id="design-context"></select></label><label>Predefined program<select id="design-program"></select></label><label>Reduce mean RNA in these genes<input id="design-genes" aria-label="Objective genes"></label><label>Population to preserve<select id="design-preserve" disabled><option>Unavailable · no measured spatial relationships</option></select></label><button id="design-compare" class="primary">Compare supported interventions</button></div>
    <p class="small">Dissociated cohorts have no spatial receiving-population readout. A preservation objective cannot execute here. No synthetic neighbors or cell positions are added.</p>
    <p id="design-status" role="status">Reserved mouse batch and Jurkat contexts. Later comparisons become retrospective after reveal.</p>
    <section id="design-result" hidden><h3 id="design-conclusion"></h3><p id="design-equation" class="small"></p><div class="design-table"><table><thead><tr><th>Candidate</th><th>Predicted utility ↑</th><th>RNA change</th><th>Model range</th><th>Observed utility</th><th>Support</th></tr></thead><tbody id="design-candidates"></tbody></table></div><div class="design-actions"><button id="design-seal" class="primary">Seal objective and all candidates</button><button id="design-reveal" disabled>Reveal reserved measurements</button><button id="design-verify" disabled>Replay native predictions</button></div><div id="design-inspection"></div><div id="design-scores"></div></section>
    <p class="small">Research utility only: no treatment efficacy, safety or survival claim. Model ranges measure disagreement, not confidence. State comparison in v0.3 was PerturbMean, not State Transition.</p>`;
    for(const c of data.contexts){const o=node('option',`${c.context} · ${c.source} · ${c.targets.length} targets`);o.value=c.id;e('context').append(o);}for(const p of data.objectives){const o=node('option',p.id);o.value=p.id;e('program').append(o);}e('genes').value=data.objectives[0].genes.join(', ');
    const invalidate=()=>{record=null;preview=null;e('result').hidden=true;status('Objective draft changed; compare and seal a new campaign.');};e('context').onchange=invalidate;e('genes').onchange=invalidate;e('program').onchange=()=>{e('genes').value=data.objectives.find(p=>p.id===e('program').value).genes.join(', ');invalidate();};
    e('compare').onclick=()=>action(async()=>{status('Compiling the objective against sealed target-aware predictions…');preview=await api('preview',{selection:selection()});record=null;render();status('Predictions available. No reserved RNA responses were read.');});
    e('seal').onclick=()=>action(async()=>{record=await api('seal',{selection:selection()});preview=record.prediction;localStorage.setItem('wetlab-design-record',record.id);render();status('Sealed '+record.id+' · objective, candidates and rankings retained.');});
    e('reveal').onclick=()=>action(async()=>{status('Verifying the objective seal, then opening measurements…');record=await api('reveal',{id:record.id});preview=record.prediction;render();status('Choice evaluated; failures retained. Biological promotion remains separate.');});
    e('verify').onclick=()=>action(async()=>{status('Replaying native target descriptor, ID and shuffled models…');const r=await api('verify',{id:record.id});status(r.status+' · native distribution tensors replay bit-exactly.');});
    const saved=localStorage.getItem('wetlab-design-record');if(saved)await action(async()=>{record=await api('open',{id:saved});preview=record.prediction;e('context').value=preview.selection.context;e('genes').value=preview.selection.objective.genes.join(', ');render();status('Restored '+record.id);});
  }
  return {mount,get state(){return {preview,record,selected,data,busy};}};
})();
