"use strict";
// NumiLab interaction only. All biological state, predictions, scoring and replay
// are returned by NumiVivo through the existing experiment lifecycle.
window.learnedLab = (() => {
  let catalog, geometry, index, run = null, field = null, population, role = 'direct', activeTarget,
      camera = {scale:1,x:0,y:0}, selected = null, background, geometryEpoch = 0, requestEpoch = 0;
  let legacyHistory,legacyQualification;
  const selectedTargets = new Set(), cache = new Map(), timings = {feature:[],draw:[],pick:[]};
  const el = id => document.getElementById('learned-'+id);
  const make = (tag, value, cls) => {const e=document.createElement(tag); if(value!==undefined)e.textContent=value;if(cls)e.className=cls;return e;};
  const request = async (path,body) => {const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Wet-Lab-Token':window.WET_LAB_TOKEN},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error);return d;};
  const notice = (s,error=false) => {el('status').textContent=s;el('status').classList.toggle('error',error);};
  async function action(fn) {if(el('root').classList.contains('working'))return;el('root').classList.add('working');el('root').querySelectorAll('button,input,select').forEach(e=>e.disabled=true);try{await fn();}catch(e){notice(e.message,true);}finally{el('root').classList.remove('working');el('root').querySelectorAll('button,input,select').forEach(e=>e.disabled=false);el('reveal').disabled=!run||run.revealed;el('replay').disabled=!run;el('seal').disabled=el('specimen').value!=='chip1'||selectedTargets.size===0;}}
  const active = () => field?.arms.find(a=>a.target===activeTarget&&a.role===role);
  const support = () => run?.comparison?.arms.find(a=>a.target===activeTarget&&a.role===role);
  const fmt = v => v==null?'UNAVAILABLE':Number(v).toFixed(3);
  function saveSelection(){localStorage.setItem('wetlab-comparison-'+catalog.id,JSON.stringify({population,targets:[...selectedTargets],gene:el('gene').value,role}));}
  function option(select,value,label){const e=make('option',label);e.value=value;select.append(e);}
  function evidence(data){const d=document.getElementById('dialog');document.getElementById('dialog-title').textContent='Evidence, coverage and replay';const pre=make('pre',JSON.stringify(data,null,2));document.getElementById('dialog-content').replaceChildren(pre);d.showModal();}
  function resetExperiment(){run=null;field=null;el('seal').disabled=el('specimen').value!=='chip1'||selectedTargets.size===0;el('reveal').disabled=true;el('replay').disabled=true;el('record').textContent='Comparison draft · all arms will be sealed together';saveSelection();loadField();}
  async function loadGeometry(){const epoch=++geometryEpoch;notice('Loading measured specimen geometry…');const g=await request('specimen',{assayID:catalog.id,specimen:el('specimen').value});if(epoch!==geometryEpoch)return;geometry=g;index=new TissueIndex(g.cells.map((c,i)=>({id:c[0],xy:[c[1],c[2]],row:i,type:g.types[c[3]],covered:c[4],population:c[5],guide:c[6],reference:c[7]})));camera={scale:1,x:0,y:0};
    // Two-dimensional LOD raster retains the full specimen, while picking uses
    // every source cell. It is regenerated only when the specimen changes.
    background=document.createElement('canvas');background.width=2048;background.height=2048;const ctx=background.getContext('2d'),b=index.bounds;ctx.fillStyle='#436057';const occupied=new Set();
    for(const p of index.points){const x=Math.round((p.xy[0]-b.xmin)/b.dx*2047),y=Math.round((p.xy[1]-b.ymin)/b.dy*2047),k=y*2048+x;if(occupied.has(k))continue;occupied.add(k);ctx.fillRect(x,y,1.5,1.5);}
    el('count').textContent=g.cells.length.toLocaleString()+' measured cells · fixed endpoint geometry';el('seal').disabled=el('specimen').value!=='chip1';notice(el('specimen').value==='chip1'?'Select a reference population and compare interventions.':'Training pool: large-specimen inspection; held-out prediction is unavailable here.');await loadField();}
  async function loadField(){if(!geometry)return;const epoch=++requestEpoch,start=performance.now(),gene=el('gene').value,key=[geometry.specimen,gene,run?.id,run?.revealed].join(':');let d=cache.get(key);if(!d){d=await request('spatial-feature',{assayID:catalog.id,specimen:geometry.specimen,gene,...(run?{id:run.id}:{})});if(cache.size>20)cache.delete(cache.keys().next().value);cache.set(key,d);}if(epoch!==requestEpoch)return;field=d;saveSelection();renderResults();draw();timings.feature.push(performance.now()-start);}
  function transform(w,h){const b=index.bounds,base=Math.min((w-36)/b.dx,(h-54)/b.dy),s=base*camera.scale;return {s,ox:w/2+camera.x-(b.xmin+b.dx/2)*s,oy:h/2+camera.y-(b.ymin+b.dy/2)*s};}
  function color(v,scale,residual=false){if(v==null||!Number.isFinite(v))return '#4b6159';if(residual){const t=Math.min(1,Math.abs(v)/scale.residual);return v>=0?`hsl(22 76% ${78-38*t}%)`:`hsl(191 70% ${80-44*t}%)`;}const t=Math.max(0,Math.min(1,(v-scale.min)/(scale.max-scale.min)));return `hsl(148 ${35+35*t}% ${24+55*t}%)`;}
  function hull(points){const p=points.slice().sort((a,b)=>a[0]-b[0]||a[1]-b[1]);if(p.length<3)return p;const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);let lo=[],hi=[];for(const x of p){while(lo.length>1&&cross(lo.at(-2),lo.at(-1),x)<=0)lo.pop();lo.push(x);}for(const x of p.slice().reverse()){while(hi.length>1&&cross(hi.at(-2),hi.at(-1),x)<=0)hi.pop();hi.push(x);}return lo.slice(0,-1).concat(hi.slice(0,-1));}
  function envelopes(points){const pending=points.slice(),groups=[],limit=.15*Math.max(index.bounds.dx,index.bounds.dy);while(pending.length){const group=[pending.pop()];for(let i=0;i<group.length;i++)for(let j=pending.length-1;j>=0;j--)if(Math.hypot(group[i][0]-pending[j][0],group[i][1]-pending[j][1])<limit)group.push(pending.splice(j,1)[0]);groups.push(hull(group));}return groups;}
  let hullKey=null, populationHull=[];
  function draw(){if(!index||!field)return;const start=performance.now(),a=active(),raw=el('units').value==='raw';const values=field.arms.flatMap(x=>[x.control,x.predicted,x.observed].filter(v=>v!=null)),res=field.arms.map(x=>x.residual??NaN),scale=TissueIndex.sharedScale([values.length?values:field.referenceNormalized],[res]);
    const key=geometry.specimen+population;if(key!==hullKey){hullKey=key;const p=catalog.populations.find(x=>x.id===population);populationHull=geometry.specimen==='chip1'?envelopes((p?.anchorRows||[]).map(i=>index.points[i].xy)):[];}
    for(const mode of ['control','predicted','observed','residual']){const canvas=el(mode),rect=canvas.getBoundingClientRect(),w=rect.width,h=rect.height,dpr=devicePixelRatio||1;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#102b28';ctx.fillRect(0,0,w,h);const tr=transform(w,h),b=index.bounds;ctx.imageSmoothingEnabled=false;ctx.drawImage(background,b.xmin*tr.s+tr.ox,b.ymin*tr.s+tr.oy,b.dx*tr.s,b.dy*tr.s);
      const value=raw?null:a?.[mode];if(value!=null&&populationHull.length)for(const envelope of populationHull){ctx.beginPath();envelope.forEach(([x,y],i)=>i?ctx.lineTo(x*tr.s+tr.ox,y*tr.s+tr.oy):ctx.moveTo(x*tr.s+tr.ox,y*tr.s+tr.oy));ctx.closePath();ctx.fillStyle=color(value,scale,mode==='residual');ctx.globalAlpha=.25;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=color(value,scale,mode==='residual');ctx.lineWidth=2;ctx.stroke();}
      if(mode==='control'&&!a){for(let k=0;k<field.referenceRows.length;k++){const p=index.points[field.referenceRows[k]],v=raw?field.referenceRaw[k]:field.referenceNormalized[k];if(v==null)continue;ctx.fillStyle=color(v,raw?{min:0,max:Math.max(1,...field.referenceRaw)}:scale);ctx.fillRect(p.xy[0]*tr.s+tr.ox-2,p.xy[1]*tr.s+tr.oy-2,4,4);}}
      if(mode==='observed'&&a?.observedRows.length){for(let k=0;k<a.observedRows.length;k++){const p=index.points[a.observedRows[k]],v=raw?a.observedRaw[k]:a.observedValues[k];ctx.fillStyle=color(v,raw?{min:0,max:Math.max(1,...a.observedRaw)}:scale);ctx.fillRect(p.xy[0]*tr.s+tr.ox-2,p.xy[1]*tr.s+tr.oy-2,4,4);}}
      if(selected){ctx.beginPath();ctx.arc(selected.xy[0]*tr.s+tr.ox,selected.xy[1]*tr.s+tr.oy,6,0,Math.PI*2);ctx.strokeStyle='#fff1ae';ctx.lineWidth=1.5;ctx.stroke();}
      ctx.fillStyle='#dce9dc';ctx.font='11px -apple-system';ctx.fillText(raw?(mode==='predicted'||mode==='residual'?'UNAVAILABLE · model predicts log1p(CPM)':'MEASURED · raw UMI'):mode==='residual'?`−${fmt(scale.residual)} ← 0 → +${fmt(scale.residual)} · predicted − observed`:`${fmt(scale.min)} → ${fmt(scale.max)} · shared log1p(CPM)`,12,h-13);
      if(!a&&mode!=='control'||a&&['observed','residual'].includes(mode)&&!run.revealed){ctx.fillStyle='#e4dfc3';ctx.fillText(run?'Measurements remain sealed':'Seal the selected comparison arms',12,24);}
      el(mode+'-evidence').textContent=mode==='control'?(a?(a.control!=null?'MODEL INFERENCE · reference population':'UNAVAILABLE'):(field.measuredInSource?'MEASURED · isolated reference cells':'UNAVAILABLE')):mode==='predicted'?(a?.predicted!=null&&!raw?'MODEL INFERENCE · population distribution':'UNAVAILABLE'):mode==='observed'?(run?.revealed?'MEASURED · endpoint RNA':'UNAVAILABLE · sealed'):(run?.revealed?'MODEL INFERENCE · signed error':'UNAVAILABLE · sealed');
    }timings.draw.push(performance.now()-start);}
  function renderResults(){const target=active(),root=el('arms');root.replaceChildren();for(const t of [...selectedTargets].sort()){const b=make('button',t,'chip'+(t===activeTarget?' selected':''));b.onclick=()=>{activeTarget=t;renderResults();draw();};root.append(b);}const plots=el('plots');plots.replaceChildren();
    const shown=field?.arms.filter(x=>x.role===role)||[];const max=Math.max(1,...shown.flatMap(x=>[x.control,(x.predicted??0)+2*Math.sqrt(x.variance??0),x.observed||0]));
    for(const p of shown){const card=make('button',undefined,'response-card'+(p.target===activeTarget?' selected':''));card.append(make('b',p.target));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 260 60');svg.setAttribute('aria-label',p.target+' marginal expression distribution');const x=v=>20+Math.max(0,v)/max*215;function mark(v,y,c,r=4){const e=document.createElementNS(svg.namespaceURI,'circle');e.setAttribute('cx',x(v));e.setAttribute('cy',y);e.setAttribute('r',r);e.setAttribute('fill',c);svg.append(e);}if(p.predicted!=null){const line=document.createElementNS(svg.namespaceURI,'line');line.setAttribute('x1',x(p.predicted-1.96*Math.sqrt(p.variance)));line.setAttribute('x2',x(p.predicted+1.96*Math.sqrt(p.variance)));line.setAttribute('y1',25);line.setAttribute('y2',25);line.setAttribute('stroke','#d9b976');line.setAttribute('stroke-width','5');svg.append(line);}if(p.control!=null)mark(p.control,12,'#9dd7b8');if(p.predicted!=null)mark(p.predicted,25,'#ffe1a0');p.observedValues.forEach((v,i)=>mark(v,42+(i%3)*3,'#85cce2',2));card.append(svg,make('span',`Reference ${fmt(p.control)} · prediction ${fmt(p.predicted)} · observed ${fmt(p.observed)}`,'small'));card.onclick=()=>{activeTarget=p.target;renderResults();draw();};plots.append(card);}
    el('distribution-note').textContent=shown.length?'Gold: predicted marginal mean ± 1.96 standard deviations, uncalibrated. Blue: unique measured cells after reveal. Green: shared control reference. Genes and cells do not supply animal-level confidence.':'Choose interventions and seal their comparison to inspect native distributions.';
    const landscape=el('landscape');landscape.replaceChildren(make('h3','Where is the predicted effect strongest?'));
    const effects=(field?.populationEffects||[]).filter(x=>x.target===activeTarget&&x.role===role&&x.effect!=null).sort((a,b)=>Math.abs(b.effect)-Math.abs(a.effect));
    for(const e of effects.slice(0,6)){const b=make('button',`${e.population}: ${e.effect>0?'+':''}${fmt(e.effect)}`,'chip');b.title='Campaign prediction using anchor-matched reference states; opens a comparison draft for this population';b.onclick=()=>{population=e.population;el('population').value=population;resetExperiment();};landscape.append(b);}
    landscape.append(make('p','Campaign effects use anchor-matched references; selecting one opens a new draft. All are experimental population inferences.','small'));
    const s=support(),inspection=el('inspection');inspection.replaceChildren();inspection.append(make('h3',population+' · '+role+' responses'));if(selected){inspection.append(make('p',`Cell ${selected.id} · projected ${selected.type} · reference coverage ${selected.covered?'within limit':'insufficient'}`));inspection.append(make('p',`Guide assignment: ${selected.guide}. Barcode-negative exposure is unknown; a detected guide does not prove functional knockout.`,'small'));let ix=field.referenceRows.indexOf(selected.row);if(ix>=0)inspection.append(make('p',`MEASURED reference ${el('gene').value}: ${fmt(field.referenceRaw[ix])} raw UMI; ${fmt(field.referenceNormalized[ix])} log1p(CPM).`));else if(target&&(ix=target.observedRows.indexOf(selected.row))>=0)inspection.append(make('p',`MEASURED endpoint ${el('gene').value}: ${fmt(target.observedRaw[ix])} raw UMI; ${fmt(target.observedValues[ix])} log1p(CPM).`));else inspection.append(make('p','Cell-specific molecular measurement UNAVAILABLE in this selected comparison.','small'));}
    inspection.append(make('p',target?`${el('gene').value}: predicted change ${fmt(target.predicted==null?null:target.predicted-target.control)} log1p(CPM). Population overlay; not a cell-specific forecast.`:'RNA and guide labels stay in the NumiVivo source-bound cohort. Cell types are uncertain reference projections.'));
    if(s){inspection.append(make('p',`${s.count} unique measured outcome cells · ${s.controlReferenceCells} contributing reference cells · ${s.isolatedSafeControls} isolated safe-harbour controls · ${s.biologicalUnits} held-out animal.`));for(const d of s.diagnostics)inspection.append(make('p',d,'diagnostic'));}
    else inspection.append(make('p','Biological promotion blocked: four isolated safe-harbour controls, below the preregistered minimum of five.','diagnostic'));
    const failure=el('failures');failure.replaceChildren();if(run?.revealed){const table=make('table');const head=make('tr');['Population / intervention','Spatial RMSE','No neighborhood','Matched-control baseline','Coverage'].forEach(x=>head.append(make('th',x)));table.append(head);for(const r of run.comparison.arms.filter(x=>x.role===role)){const tr=make('tr');[r.target,fmt(r.metrics.neighborhood?.rmse),fmt(r.metrics['no-neighborhood']?.rmse),fmt(r.metrics['cell-type-matched']?.rmse),r.support].forEach(x=>tr.append(make('td',x)));tr.onclick=()=>{activeTarget=r.target;renderResults();draw();};table.append(tr);}failure.append(table);}else failure.append(make('p','Diagnostics are computed from revealed measurements. No failure explanation is invented before scoring.'));
    if(catalog.completedCampaign){failure.append(make('h3','Completed campaign: where does error concentrate?'),make('p','Equal population-group RMSE by inferred cell type. Separate from this comparison; one held-out animal, no confidence interval.','small'));const t=make('table'),h=make('tr');['Inferred cell type','Spatial RMSE','No neighborhood','Matched baseline'].forEach(x=>h.append(make('th',x)));t.append(h);for(const r of catalog.completedCampaign.cellTypes.slice().sort((a,b)=>b.spatialRMSE-a.spatialRMSE)){const tr=make('tr');[r.cellType,fmt(r.spatialRMSE),fmt(r.noNeighborhoodRMSE),fmt(r.matchedBaselineRMSE)].forEach(x=>tr.append(make('td',x)));t.append(tr);}failure.append(t);}

  }
  function setupCanvas(mode){const c=el(mode);let drag=null;c.onpointerdown=e=>{drag={x:e.offsetX,y:e.offsetY,px:camera.x,py:camera.y};c.setPointerCapture(e.pointerId);};c.onpointermove=e=>{if(drag){camera.x=drag.px+e.offsetX-drag.x;camera.y=drag.py+e.offsetY-drag.y;draw();}};c.onpointerup=e=>{if(!drag)return;const moved=Math.hypot(e.offsetX-drag.x,e.offsetY-drag.y);drag=null;if(moved>4)return;const start=performance.now(),rect=c.getBoundingClientRect(),tr=transform(rect.width,rect.height);selected=index.pick((e.offsetX-tr.ox)/tr.s,(e.offsetY-tr.oy)/tr.s,18/tr.s);timings.pick.push(performance.now()-start);if(selected?.population&&selected.population!==population&&!run){population=selected.population;el('population').value=population;saveSelection();}renderResults();draw();};c.onwheel=e=>{e.preventDefault();camera.scale=Math.max(.5,Math.min(20,camera.scale*Math.exp(-e.deltaY*.001)));draw();};}
  async function mount(c,assays=[c]){catalog=c;document.querySelector('main').hidden=true;document.querySelector('.version').textContent='v0.3 · experimental';let root=el('root');if(!root){root=make('section');root.id='learned-root';document.querySelector('main').after(root);root.innerHTML=`
      <div class="mast"><div><div class="eyebrow">SPATIAL RESPONSE LABORATORY</div><h1>Where does the response differ?</h1><p>Compare interventions in a shared reference population. Reveal the measurements. Investigate the failures.</p></div><button id="learned-evidence" class="evidence">MODEL INFERENCE ↗</button></div>
      <div class="investigation-toolbar panel"><label>Assay<select id="learned-assay"></select></label><label>Specimen<select id="learned-specimen"></select></label><label>Reference population<select id="learned-population"></select></label><label>Response<select id="learned-role"><option value="direct">Directly perturbed</option><option value="neighbor">Neighboring population</option></select></label><label>Gene<input id="learned-gene" list="learned-genes" value="Gfap"/><datalist id="learned-genes"></datalist></label><label>Units<select id="learned-units"><option value="normalized">log1p(CPM)</option><option value="raw">Measured raw UMI</option></select></label><button id="learned-reset">Reset cameras</button></div>
      <div class="arm-designer"><span class="eyebrow">COMPARE INTERVENTIONS</span><div id="learned-targets"></div><button id="learned-seal" class="primary">Seal all selected arms →</button><button id="learned-saved">Saved comparisons</button></div>
      <details id="learned-excluded"><summary>Excluded interventions and support criteria</summary></details><div class="row"><span id="learned-count" class="small"></span><span id="learned-record" class="small">Comparison draft · all arms will be sealed together</span></div><p id="learned-status" role="status"></p>
      <div class="comparison-canvases">${['control','predicted','observed','residual'].map(m=>`<section class="panel"><div class="row"><h3>${{control:'Control reference',predicted:'Predicted distribution',observed:'Observed endpoint',residual:'Prediction error'}[m]}</h3><button id="learned-${m}-evidence" class="field-evidence">UNAVAILABLE</button></div><canvas id="learned-${m}" tabindex="0" aria-label="${m} tissue comparison"></canvas></section>`).join('')}</div>
      <div class="reveal-strip"><div><b>Prediction → sealed comparison → measured observation → evaluation → replay</b><p class="small">One observed endpoint. Fixed geometry. No inferred cell trajectories or mechanism.</p></div><button id="learned-reveal" class="primary" disabled>Reveal held-out measurements</button><button id="learned-replay" disabled>Exact native replay</button></div>
      <div class="investigation-bottom"><section class="panel"><div class="row"><h2>Linked molecular responses</h2><div id="learned-arms"></div></div><div id="learned-plots"></div><div id="learned-landscape"></div><p id="learned-distribution-note" class="small"></p><details id="learned-failure-mode"><summary>Inspect failures & matched baselines</summary><div id="learned-failures"></div></details></section><aside id="learned-inspection" class="panel"></aside></div><p class="small">Measured values stay distinct from inference. Barcode-negative cells are not assumed untreated. Population and neighborhood labels are uncertain reference projections.</p>`;
    }
    root.hidden=false;el('assay').replaceChildren();for(const a of assays)option(el('assay'),a.id,a.title);el('assay').value=c.id;el('assay').onchange=()=>window.setCatalog(assays.find(a=>a.id===el('assay').value));el('specimen').replaceChildren();for(const s of c.specimens)option(el('specimen'),s.id,s.title);el('population').replaceChildren();for(const p of c.populations)option(el('population'),p.id,`${p.cellType} · neighborhood ${p.neighborhood} · ${p.anchors} anchors`);el('genes').replaceChildren();for(const g of c.features)option(el('genes'),g,g);
    let saved;try{saved=JSON.parse(localStorage.getItem('wetlab-comparison-'+c.id));}catch{}population=c.populations.some(p=>p.id===saved?.population)?saved.population:(c.populations.find(p=>p.cellType==='neuron')||c.populations[0]).id;el('population').value=population;el('gene').value=c.features.includes(saved?.gene)?saved.gene:'Gfap';selectedTargets.clear();(saved?.targets||['Cfap410','Fasn','Gfap']).filter(t=>c.targets.some(x=>x.target===t)).forEach(t=>selectedTargets.add(t));activeTarget=[...selectedTargets][0];
    el('targets').replaceChildren();for(const t of c.targets){const l=make('label',undefined,'target-choice'),box=make('input');box.type='checkbox';box.value=t.target;box.checked=selectedTargets.has(t.target);box.onchange=()=>{if(box.checked)selectedTargets.add(t.target);else selectedTargets.delete(t.target);activeTarget=[...selectedTargets][0];resetExperiment();};l.append(box,make('span',t.target));el('targets').append(l);}
    for(const old of el('excluded').querySelectorAll('p'))old.remove();for(const t of c.excludedTargets||[])el('excluded').append(make('p',`${t.target||t.guideID}: unavailable — ${t.exclusions.join('; ')}`,'small'));
    for(const m of ['control','predicted','observed','residual']){setupCanvas(m);el(m+'-evidence').onclick=()=>evidence({layer:m,gene:el('gene').value,units:el('units').value,limits:c.limits,source:c.sourceCitation,record:run?.recordDirectory,registration:run?.registration,comparison:support()});}
    el('specimen').onchange=()=>action(async()=>{run=null;el('record').textContent='Comparison draft · all arms will be sealed together';await loadGeometry();});el('population').onchange=()=>{population=el('population').value;selected=null;resetExperiment();};el('role').onchange=()=>{role=el('role').value;saveSelection();renderResults();draw();};el('gene').onchange=()=>action(loadField);el('units').onchange=draw;el('reset').onclick=()=>{camera={scale:1,x:0,y:0};draw();};el('evidence').onclick=()=>evidence({catalog:c,registration:run?.registration,comparison:run?.comparison});
    el('seal').onclick=()=>action(async()=>{notice('Native MLX inference for the selected comparison arms…');run=await request('predict',{assayID:c.id,selection:{specimen:el('specimen').value,population,targets:[...selectedTargets]}});el('record').textContent='Sealed comparison '+run.id;el('reveal').disabled=false;el('replay').disabled=false;notice('All selected arms sealed against the same reference population.');await loadField();});
    el('reveal').onclick=()=>action(async()=>{notice('Verifying sealed predictions, then revealing measured RNA…');run=await request('reveal',{id:run.id});el('reveal').disabled=true;await loadField();notice('Measurements revealed. Failures and coverage limitations are retained in the experiment record.');});
    el('replay').onclick=()=>action(async()=>{notice('Replaying native mean and variance tensors…');const r=await request('verify',{id:run.id});notice(r.status==='verified'?'Native predictions replay bit-exactly. Biological promotion remains blocked.':JSON.stringify(r));});
    el('saved').onclick=()=>action(async()=>{const rows=await request('experiments'),d=document.getElementById('dialog');document.getElementById('dialog-title').textContent='Saved comparison workspace';const list=make('div');for(const r of rows.filter(x=>x.family===c.family)){const b=make('button',r.id.slice(0,8)+' · '+(r.revealed?'revealed':'sealed'));b.onclick=()=>action(async()=>{run=await request('experiments/'+r.id);population=run.registration.plan.population;el('population').value=population;selectedTargets.clear();run.registration.plan.targets.forEach(t=>selectedTargets.add(t));el('targets').querySelectorAll('input').forEach(e=>e.checked=selectedTargets.has(e.value));activeTarget=[...selectedTargets][0];el('specimen').value='chip1';el('record').textContent='Saved comparison '+run.id;el('reveal').disabled=run.revealed;el('replay').disabled=false;d.close();await loadGeometry();});list.append(b);}document.getElementById('dialog-content').replaceChildren(list);d.showModal();});
    if(!legacyHistory){legacyHistory=document.getElementById('history-open').onclick;legacyQualification=document.getElementById('benchmark-open').onclick;}
    document.getElementById('history-open').onclick=()=>el('saved').click();
    document.getElementById('benchmark-open').onclick=()=>action(async()=>evidence({spatial:c.limits,biologicalPromotion:false,arc:await request('qualification')}));
    new ResizeObserver(draw).observe(el('root'));await loadGeometry();if(window.interventionDesign)await window.interventionDesign.mount(el('root'));
  }
  return {mount,unmount:()=>{if(legacyHistory){document.getElementById('history-open').onclick=legacyHistory;document.getElementById('benchmark-open').onclick=legacyQualification;}if(el('root'))el('root').hidden=true;document.querySelector('main').hidden=false;},performance:()=>({specimenCells:index?.points.length,timings}),draw,loadField,pickAt:(x,y,r)=>index.pick(x,y,r),get state(){return {run,field,geometry,population,activeTarget,role,camera};}};
})();
