"use strict";
// Presentation only. NumiVivo owns readouts, objective scores and access checks.
window.populationLab = (() => {
  let catalog, catalogs=[], root, selection, field=null, run=null, activeTarget=null, headerHistory, headerQualification;
  let requestNumber=0, controller, comparisonScale=null, layers=['control'], mode='predict',savingSelection=false,viewTargets=null;
  let normalization='raw_counts', valueOffset=0, metadataOffset=0, metadataSearch='', metadata=[], metadataTotal=0, metadataController, metadataEpoch=0, searchTimer, featureController, featureEpoch=0, featureTimer;
  const valueLimit=128, metadataLimit=32, caps=()=>catalog.capabilities||catalog, measuredOnly=()=>caps().prediction===false&&caps().measuredExploration===true;
  const predictionReason=()=>caps().predictionReason||'No compatible predictive model is registered for this dataset. Register a model bound to this source, feature axis, context and preprocessing before prediction; the older cellular or tissue model is not substituted.';
  const cache=new Map(), $=id=>document.getElementById('population-'+id);
  const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
  const fmt=v=>v==null?'UNAVAILABLE':Number(v).toPrecision(5);
  const withGene=sel=>({...sel,gene:sel.gene||(catalog.features.includes('FOS')?'FOS':catalog.features[0])});
  async function request(path,body,signal){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'X-Wet-Lab-Token':window.WET_LAB_TOKEN,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Readout unavailable');return d;}
  function options(id,values,value){$(id).replaceChildren();for(const v of values){const o=node('option',v.title||v.id);o.value=v.id;$(id).append(o);}$(id).value=value;}
  function sync(){if(!selection)return;const pop=catalog.populations.find(p=>p.id===selection.populationID);const conditions=(catalog.conditions||[]).filter(c=>!pop?.conditionID||c.id===pop.conditionID);if(selection.conditionID&&!conditions.some(c=>c.id===selection.conditionID))conditions.push({id:selection.conditionID,title:selection.conditionID+' · unsupported for this population'});options('condition',conditions,selection.conditionID);for(const [id,key] of [['assay','assayID'],['specimen','specimenID'],['population','populationID'],['condition','conditionID'],['gene','gene']])$(id).value=selection[key]||'';}
  async function editSelection(changed){if(savingSelection)return;savingSelection=true;window.sharedWetLab.invalidateInspection();controller?.abort();requestNumber++;field=null;draw();const next={...selection,assayID:$('assay').value,specimenID:$('specimen').value,populationID:$('population').value,conditionID:$('condition').value,gene:$('gene').value,experimentID:null};const pop=changed==='specimen'?(catalog.populations.find(p=>p.id===next.populationID&&(!p.specimenID||p.specimenID===next.specimenID))||catalog.populations.find(p=>p.specimenID===next.specimenID)):catalog.populations.find(p=>p.id===next.populationID);if(pop){next.populationID=pop.id;next.specimenID=pop.specimenID||next.specimenID;next.conditionID=pop.conditionID||next.conditionID;}sync();for(const id of ['specimen','population','condition','gene'])$(id).disabled=true;$('status').textContent='Saving selection to the shared workspace…';try{await window.sharedWetLab.selection(next);}finally{savingSelection=false;for(const id of ['specimen','population','condition','gene'])$(id).disabled=false;}const accepted=window.sharedWetLab.state.selection;if(!accepted||JSON.stringify(accepted)!==JSON.stringify(next)){$('status').textContent='Selection was not accepted. Review the current shared state.';return;}selection=accepted;viewTargets=null;run=null;comparisonScale=null;valueOffset=0;sync();document.getElementById('shared-genes').value=selection.gene;if(measuredOnly()&&['specimen','population','condition'].includes(changed)){activeTarget=null;metadataOffset=0;await loadInterventions();}else await loadField();}
  function support(){const s=window.sharedWetLab.state?.selectionSupport;if(!s)return 'Owner support is loading.';const r=s.reference||{};return `${s.populationAnchors==null?'Selected population':s.populationAnchors+' selected population cells'} · ${r.referenceCells??r.uniqueCells??s.referenceCells??'Unknown'} distinct reference cells. ${s.reason||''}`;}
  function draw(){if(!root||root.hidden)return;const host=$('readout');host.replaceChildren();$('support').textContent=support();$('record').textContent=run?`${run.revealed?'REVEALED OBSERVATION':'SEALED PREDICTION'} · ${run.id} · ${catalog.id}`:`${mode==='measured'?'MEASURED EVIDENCE REQUEST':'PREVIEW'} · ${catalog.id}`;
    if(!field){host.append(node('p',measuredOnly()?'Choose an intervention and gene to inspect a bounded page of measured cells.':'Choose a population and gene to request a bounded owner readout.'));return;}
    host.append(node('h2',`${field.gene} · ${selection.populationID}`),node('p',`${field.units} · ${field.scope||'Selected population'} · ${field.distributionStatus||'Distribution support unavailable'}`,'small'));
    if(field.measured===false||field.measurementMask===false)host.append(node('p','UNAVAILABLE · this gene is not measured on the selected source axis. Missing measurements are not zero counts. '+(field.missingFeatureReason||''),'diagnostic'));else if(field.modeled===false&&!measuredOnly())host.append(node('p','UNAVAILABLE · this feature is not modeled on the registered axis.','diagnostic'));
    if(measuredOnly()){drawMeasured(host);return;}
    if(mode==='measured'&&!field.arms?.some(a=>a.observed!=null))host.append(node('p','Measured outcomes are unavailable under the current access state. This action does not reveal sealed observations.','diagnostic'));
    const arms=(field.arms||[]).filter(a=>!viewTargets||viewTargets.includes(a.target)), values=arms.flatMap(a=>['control','predicted','observed'].map(k=>a[k]).filter(Number.isFinite));
    const max=comparisonScale?.max??Math.max(1,...values), min=comparisonScale?.min??Math.min(0,...values), range=Math.max(1e-12,max-min);
    const resMax=comparisonScale?.residual??Math.max(1,...arms.map(a=>Math.abs(a.residual||0)));
    const table=node('table');table.className='population-values';const head=node('tr');['Intervention',...layers.map(k=>({control:'Control reference',predicted:'Predicted mean',observed:'Measured endpoint',residual:'Prediction − observation'}[k])),'Support'].forEach(s=>head.append(node('th',s)));table.append(head);
    for(const a of arms){const row=node('tr');row.classList.toggle('active-population-arm',a.target===activeTarget);const label=node('td'),pick=node('button',`${a.target} · ${a.population||selection.populationID}`,'candidate-name');pick.onclick=()=>{activeTarget=a.target;draw();};label.append(pick);row.append(label);
      for(const k of layers){const cell=node('td'),value=a[k],bar=node('div',undefined,'population-bar');cell.append(node('span',fmt(value)));if(Number.isFinite(value)){const fill=node('i');fill.style.width=(k==='residual'?Math.abs(value)/resMax:(value-min)/range)*100+'%';fill.className=k==='residual'?(value<0?'negative':'positive'):k;bar.append(fill);cell.append(bar);}row.append(cell);}row.append(node('td',`${a.controlCells??'Unknown'} controls · ${a.outcomeCells??'sealed'} outcome cells · ${typeof a.evidence==='string'?a.evidence:'MODEL INFERENCE'}`));table.append(row);
    }host.append(table,node('p',`Shared endpoint scale ${fmt(min)} to ${fmt(max)} ${field.units}. Signed error: −${fmt(resMax)} to +${fmt(resMax)}; positive means overprediction.`,'small'));
    host.append(node('p','Population means do not establish a cell trajectory or a response distribution. Model agreement is not calibrated confidence.','diagnostic'));
  }
  function featureOptions(search=''){const prefix=search.trim().toLowerCase(),fill=items=>$('genes').replaceChildren(...items.map(g=>{const o=node('option');o.value=typeof g==='string'?g:g.id;o.textContent=typeof g==='string'?g:g.title||g.id;return o;}));fill(catalog.features.filter(g=>!prefix||g.toLowerCase().includes(prefix)).slice(0,50));clearTimeout(featureTimer);featureController?.abort();const epoch=++featureEpoch;if(!measuredOnly()||!selection)return;featureTimer=setTimeout(async()=>{featureController=new AbortController();const identity=JSON.stringify([catalog.id,selection.specimenID,selection.populationID]);try{const d=await request('readout',{assayID:catalog.id,selection:ownerSelection(),query:{kind:'features',search:search.trim(),offset:0,limit:50,mode:'measured'}},featureController.signal);if(epoch!==featureEpoch||identity!==JSON.stringify([catalog.id,selection.specimenID,selection.populationID])||root.hidden)return;fill(d.items||[]);$('gene').title=`${d.total} matching source features; showing at most 50. Typed genes are validated by the owner.`;}catch(e){if(e.name!=='AbortError'&&epoch===featureEpoch)$('gene').title='Feature discovery unavailable: '+e.message;}},180);}

  function configurePresentation(){const measured=measuredOnly();$('cohort-tools').hidden=!measured;$('prediction-reason').hidden=!measured;$('prediction-reason').textContent=measured?predictionReason():'';$('predict').disabled=measured;$('predict').title=measured?predictionReason():'';root.querySelector('.mast .evidence').textContent=measured?'MEASURED DATA · NO PREDICTOR':'EXPERIMENTAL MODEL';root.querySelector('.mast h1').textContent=measured?'What does this measured population show?':'Which intervention changes this population?';root.querySelector('.mast p').textContent=measured?'Explore source-bound controls and interventions. Reserved outcomes stay closed.':'Define a molecular objective. Compare native predictions with authorized measurements.';for(const b of document.querySelectorAll('[data-view-layer]'))b.disabled=measured&&['predicted','residual'].includes(b.dataset.viewLayer);const comparison=document.getElementById('shared-compare-views');if(comparison)comparison.disabled=measured;$('normalization').value=normalization;$('intervention-search').value=metadataSearch;$('normalization').onchange=()=>{normalization=$('normalization').value;valueOffset=0;comparisonScale=null;loadField();};$('intervention-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{metadataSearch=$('intervention-search').value.trim();metadataOffset=0;loadInterventions(false);},250);};$('target-prev').onclick=()=>{metadataOffset=Math.max(0,metadataOffset-metadataLimit);loadInterventions(false);};$('target-next').onclick=()=>{metadataOffset+=metadataLimit;loadInterventions(false);};}
  function ownerSelection(){return {specimen:selection.specimenID,population:selection.populationID,condition:selection.conditionID,targets:[],objective:{genes:[selection.gene],preserveGenes:[],penalty:0}};}
  async function loadInterventions(loadGene=true){metadataController?.abort();metadataController=new AbortController();const epoch=++metadataEpoch,identity=JSON.stringify([catalog.id,selection.specimenID,selection.populationID,selection.conditionID]);$('metadata-status').textContent='Loading intervention metadata…';try{const d=await request('readout',{assayID:catalog.id,selection:ownerSelection(),query:{kind:'interventions',search:metadataSearch,offset:metadataOffset,limit:metadataLimit,mode:'measured'}},metadataController.signal);if(epoch!==metadataEpoch||identity!==JSON.stringify([catalog.id,selection.specimenID,selection.populationID,selection.conditionID])||root.hidden)return;metadata=d.items||[];metadataTotal=d.total;renderInterventions();if(!activeTarget&&metadata.length){const next={...selection,target:metadata[0].target,experimentID:null};await window.sharedWetLab.selection(next);if(epoch!==metadataEpoch||JSON.stringify(window.sharedWetLab.state.selection)!==JSON.stringify(next))return;selection=next;activeTarget=metadata[0].target;renderInterventions();}if(loadGene)await loadField();}catch(e){if(e.name!=='AbortError'&&epoch===metadataEpoch)$('metadata-status').textContent=e.message;}}
  function renderInterventions(){const host=$('interventions');host.replaceChildren();$('metadata-status').textContent=metadata.length?`Targets ${metadataOffset+1}–${metadataOffset+metadata.length} of ${metadataTotal}. Counts describe cells, not independent biological units.`:'No interventions match this search.';$('target-prev').disabled=metadataOffset===0;$('target-next').disabled=metadataOffset+metadata.length>=metadataTotal;for(const item of metadata){const b=node('button',undefined,'measured-target');b.type='button';b.setAttribute('aria-pressed',String(item.target===activeTarget));b.append(node('strong',item.target),node('span',`${item.controlCells??'Unknown'} controls · ${item.outcomeCells??'unknown'} total outcome cells · ${item.accessibleOutcomeCells??'unknown'} accessible · ${item.reservedOutcomeCells??'unknown'} reserved`),node('span',`${item.supportStatus||''} · ${typeof item.access==='string'?item.access:item.access?.status||'access unavailable'}`));b.onclick=async()=>{const next={...selection,target:item.target,experimentID:null};$('metadata-status').textContent='Saving intervention selection…';await window.sharedWetLab.selection(next);if(JSON.stringify(window.sharedWetLab.state.selection)!==JSON.stringify(next)){$('metadata-status').textContent='Selection changed; rejected edit was not applied.';return;}selection=next;activeTarget=item.target;valueOffset=0;renderInterventions();await loadField();};host.append(b);}}
  function drawMeasured(host){const arms=(field.arms||[]).filter(a=>!activeTarget||a.target===activeTarget);host.append(node('p',`MEASURED EVIDENCE · ${field.units} · ${typeof field.access==='string'?field.access:field.access?.status||'owner-controlled access'}`,'stage-badge'));for(const a of arms){const box=node('section',undefined,'measured-distribution');box.append(node('h3',`${a.target} · ${a.population||selection.populationID}`),node('p',`${a.controlCells??'Unknown'} distinct control cells · ${a.outcomeCells??'Unknown'} total outcome cells · ${a.accessibleOutcomeCells??'Unknown'} accessible · ${a.reservedOutcomeCells??'Unknown'} reserved · ${a.evidence||'UNAVAILABLE'}`,'support-summary'));if(a.observed==null)box.append(node('p',a.missingReason||a.reason||'Outcome values are unavailable under this access or measurement mask. Zero has not been substituted.','diagnostic'));const values=[...(a.controlValues||[]),...(a.observedValues||[])].filter(Number.isFinite),max=Math.max(1,...values,...[a.control,a.observed].filter(Number.isFinite)),ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 700 150');svg.setAttribute('role','img');svg.setAttribute('aria-label',`${field.gene}: bounded control and treated measurements on a shared value axis`);for(const [label,vals,ids,y,cls] of [['Control',a.controlValues||[],a.controlCellIDs||[],42,'control'],['Treated',a.observedValues||[],a.observedCellIDs||[],98,'observed']]){const text=document.createElementNS(ns,'text');text.setAttribute('x','5');text.setAttribute('y',y+4);text.textContent=label;svg.append(text);const line=document.createElementNS(ns,'line');line.setAttribute('x1','78');line.setAttribute('x2','680');line.setAttribute('y1',y);line.setAttribute('y2',y);svg.append(line);vals.forEach((v,i)=>{if(!Number.isFinite(v))return;const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',String(80+v/max*590));dot.setAttribute('cy',String(y+((i%9)-4)*2.5));dot.setAttribute('r','2.3');dot.setAttribute('class',cls);const title=document.createElementNS(ns,'title');title.textContent=`${ids[i]||'Identifier unavailable'}: ${fmt(v)} ${field.units}`;dot.append(title);svg.append(dot);});}box.append(svg,node('p',`Shared measured axis: 0 to ${fmt(max)} ${field.units}. Vertical spacing separates points for visibility; it has no biological meaning.`,'small'));const table=node('table');for(const row of [['Owner-computed mean','Control','Treated'],[field.gene,fmt(a.control),fmt(a.observed)],['Cells displayed on this page',(a.controlValues||[]).length,(a.observedValues||[]).length]]){const tr=node('tr');row.forEach(v=>tr.append(node('td',v)));table.append(tr);}box.append(table,node('p',`Cell rows ${valueOffset+1}–${valueOffset+valueLimit} requested, at most ${valueLimit} per group. The plotted page is not the full population distribution or an independent reproducibility estimate.`,'small'));host.append(box);}
    if(!arms.length)host.append(node('p','No measured readout returned for this selected intervention.','diagnostic'));const nav=node('div',undefined,'measured-page-controls'),prev=node('button','Previous cell page'),next=node('button','Next cell page');prev.disabled=valueOffset===0;next.disabled=!arms.some(a=>(a.controlValues||[]).length===valueLimit||(a.observedValues||[]).length===valueLimit);prev.onclick=()=>{valueOffset=Math.max(0,valueOffset-valueLimit);loadField();};next.onclick=()=>{valueOffset+=valueLimit;loadField();};nav.append(prev,next);host.append(nav,node('p','Prediction unavailable for this admitted cohort. No intervention utility, ranking, trajectory or inferred response is manufactured from these measurements.','diagnostic'));
  }
  async function loadField(){controller?.abort();controller=new AbortController();const number=++requestNumber;field=null;draw();const body={assayID:catalog.id,selection:{specimen:selection.specimenID,population:selection.populationID,condition:selection.conditionID,targets:viewTargets||[],objective:{genes:[selection.gene],preserveGenes:[],penalty:0}},query:{kind:'gene',gene:selection.gene,limit:valueLimit,offset:measuredOnly()?valueOffset:0,mode}};if(measuredOnly()){if(!activeTarget){$('status').textContent='Select a supported intervention to request measurements.';return;}body.query.target=activeTarget;body.query.normalization=normalization;}if(run?.id)body.id=run.id;
    // Access identity changes on reveal; only owner-authorized results share a key.
    const accessIdentity=run?.id?{record:run.id,revealed:run.revealed===true}:catalog.observationAccessFingerprint;const key=JSON.stringify([catalog.datasetFingerprint||catalog.sourceFingerprint||catalog.id,catalog.modelIdentity||catalog.modelBinding||catalog.id,body,accessIdentity]);const cacheable=accessIdentity!=null;$('status').textContent='Loading requested gene; the full expression matrix stays with NumiVivo…';try{const d=(cacheable?cache.get(key):null)||await request('readout',body,controller.signal);if(number!==requestNumber||root.hidden)return;if(cacheable)cache.set(key,d);if(cache.size>32)cache.delete(cache.keys().next().value);field=d;$('status').textContent='Owner readout loaded. No observations were revealed by inspection.';draw();}catch(e){if(e.name==='AbortError'||number!==requestNumber)return;$('status').textContent=e.message;}}
  async function mount(c,assays=[c]){controller?.abort();metadataController?.abort();metadataEpoch++;featureController?.abort();featureEpoch++;clearTimeout(featureTimer);clearTimeout(searchTimer);catalog=c;catalogs=assays;document.querySelector('main').hidden=true;if(!root){root=node('section');root.id='population-root';document.querySelector('main').after(root);root.innerHTML='<div class="mast"><div><div class="eyebrow">CELLULAR EXPERIMENT LABORATORY</div><h1>Which intervention changes this population?</h1><p>Define a molecular objective. Compare native predictions with authorized measurements.</p></div><span class="evidence">EXPERIMENTAL MODEL</span></div><div class="investigation-toolbar panel"><label>Assay<select id="population-assay"></select></label><label>Specimen<select id="population-specimen"></select></label><label>Population<select id="population-population"></select></label><label>Condition<select id="population-condition"></select></label><label>Gene<input id="population-gene" list="population-genes"><datalist id="population-genes"></datalist></label></div><p id="population-support" class="small"></p><p id="population-record" class="stage-badge"></p><div class="population-mode"><button id="population-predict">Predict a response</button><button id="population-measured">Explore accessible measurements</button></div><p id="population-status" role="status"></p><div class="comparison-canvases population-presentation"><section class="panel" id="population-readout" aria-live="polite"></section></div>';}
    if(!$('cohort-tools')){const tools=node('section',undefined,'panel measured-cohort-tools');tools.id='population-cohort-tools';tools.innerHTML='<div class="measured-control-row"><label>Intervention search<input id="population-intervention-search" type="search" placeholder="Search admitted targets"></label><label>Measured units<select id="population-normalization"><option value="raw_counts">Raw counts</option><option value="log1p_10000">log1p(count / source-panel cell total × 10,000)</option></select></label></div><p id="population-metadata-status" role="status"></p><div id="population-interventions" class="measured-interventions"></div><div class="measured-page-controls"><button id="population-target-prev">Previous targets</button><button id="population-target-next">Next targets</button></div>';root.querySelector('.population-mode').after(tools);const reason=node('p',undefined,'diagnostic');reason.id='population-prediction-reason';root.querySelector('.population-mode').after(reason);}
    root.hidden=false;document.querySelector('.version').textContent='v0.4 · experimental models';if(!headerHistory){headerHistory=document.getElementById('history-open').onclick;headerQualification=document.getElementById('benchmark-open').onclick;}document.getElementById('history-open').onclick=()=>{const history=document.getElementById('shared-history');history.closest('details').open=true;history.scrollIntoView({block:'nearest'});};document.getElementById('benchmark-open').onclick=()=>{document.getElementById('dialog-title').textContent='Registered cellular evidence';document.getElementById('dialog-content').replaceChildren(node('pre',JSON.stringify({id:catalog.id,model:catalog.modelIdentity||catalog.modelBinding,evidence:catalog.evidence,limits:catalog.limits,biologicalPromotion:false},null,2)));document.getElementById('dialog').showModal();};const shared=(window.sharedWetLab.state||await request('shared')).selection, matching=shared?.assayID===c.id;selection=matching?withGene(shared):{assayID:c.id,specimenID:c.populations[0]?.specimenID||c.specimens[0]?.id,populationID:c.populations[0]?.id,conditionID:c.populations[0]?.conditionID||c.conditions?.[0]?.id||'measured-endpoint',gene:c.features.includes('FOS')?'FOS':c.features[0]};run=null;field=null;viewTargets=null;activeTarget=selection.target||(measuredOnly()?null:c.targets[0]?.target);comparisonScale=null;metadataOffset=0;metadataSearch='';valueOffset=0;mode=measuredOnly()?'measured':'predict';
    options('assay',assays,c.id);options('specimen',c.specimens,selection.specimenID);options('population',c.populations.map(p=>({...p,title:(p.title||p.id)+(p.specimenID?' · '+p.specimenID:'')})),selection.populationID);options('condition',c.conditions||[{id:'measured-endpoint'}],selection.conditionID);featureOptions(selection.gene);$('gene').oninput=()=>featureOptions($('gene').value);sync();configurePresentation();$('assay').onchange=()=>window.setCatalog(catalogs.find(x=>x.id===$('assay').value));for(const id of ['specimen','population','condition','gene'])$(id).onchange=()=>editSelection(id).catch(e=>{$('status').textContent=e.message;sync();});$('predict').onclick=()=>{if(measuredOnly())return;mode='predict';window.sharedWetLab.view('predicted');loadField();};$('measured').onclick=()=>{mode='measured';window.sharedWetLab.view('observed');loadField();};await window.sharedWetLab.mount(root);const latest=window.sharedWetLab.state.selection;if(latest?.assayID===c.id)selection=withGene(latest);else {await window.sharedWetLab.selection(selection);selection=withGene(window.sharedWetLab.state.selection);}sync();document.getElementById('shared-genes').value=selection.gene;configurePresentation();if(measuredOnly()){window.sharedWetLab.view('observed');await loadInterventions();}else await loadField();
  }
  async function inspectShared(card,gene,target){controller?.abort();const seq=++requestNumber,sel={...card.selection,gene};if(catalog.id!==sel.assayID){const next=await request('catalog?assay='+encodeURIComponent(sel.assayID));if(seq!==requestNumber)return;catalog=next;mode=measuredOnly()?'measured':'predict';options('assay',catalogs,catalog.id);options('specimen',catalog.specimens,sel.specimenID);options('population',catalog.populations.map(p=>({...p,title:(p.title||p.id)+(p.specimenID?' · '+p.specimenID:'')})),sel.populationID);featureOptions(gene);configurePresentation();}const record=card.record?await request('experiments/'+card.record):null;if(seq!==requestNumber)return;const sharedSelection={...sel,experimentID:record?.id||null};await window.sharedWetLab.selection(sharedSelection);if(seq!==requestNumber||JSON.stringify(window.sharedWetLab.state.selection)!==JSON.stringify(sharedSelection))return;selection=sharedSelection;viewTargets=[...card.targets];run=record;activeTarget=target||card.targets[0];comparisonScale=card.comparisonScale;sync();await loadField();}
  function view(layer,multiple){if(measuredOnly()){layers=['control','observed'];draw();return;}layers=multiple?['control','predicted','observed','residual']:[layer];draw();}
  async function acceptSelection(sel){if(sel.assayID!==catalog.id){const c=catalogs.find(x=>x.id===sel.assayID)||await request('catalog?assay='+encodeURIComponent(sel.assayID));await window.setCatalog(c);return;}controller?.abort();requestNumber++;field=null;const previous=selection;selection=withGene(sel);draw();viewTargets=null;run=null;comparisonScale=null;valueOffset=0;sync();document.getElementById('shared-genes').value=selection.gene;if(measuredOnly()&&(previous?.populationID!==selection.populationID||previous?.conditionID!==selection.conditionID)){activeTarget=selection.target||null;metadataOffset=0;await loadInterventions();}else {if(measuredOnly()&&selection.target)activeTarget=selection.target;await loadField();}}
  return {mount,inspectShared,acceptSelection,loadField,draw,view,unmount(){controller?.abort();metadataController?.abort();featureController?.abort();clearTimeout(searchTimer);clearTimeout(featureTimer);requestNumber++;metadataEpoch++;featureEpoch++;if(root)root.hidden=true;if(headerHistory){document.getElementById('history-open').onclick=headerHistory;document.getElementById('benchmark-open').onclick=headerQualification;}},get state(){return {run,field,population:selection?.populationID,activeTarget,role:'direct',modelID:catalog?.id,comparisonScale,measuredOnly:measuredOnly(),normalization,metadataOffset,metadataTotal,valueOffset};}};
})();
