"use strict";
// Presentation only. NumiVivo owns readouts, objective scores and access checks.
window.populationLab = (() => {
  let catalog, catalogs=[], root, selection, field=null, run=null, activeTarget=null, headerHistory, headerQualification;
  let requestNumber=0, controller, comparisonScale=null, layers=['control'], mode='predict',savingSelection=false,viewTargets=null;
  const cache=new Map(), $=id=>document.getElementById('population-'+id);
  const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
  const fmt=v=>v==null?'UNAVAILABLE':Number(v).toPrecision(5);
  const withGene=sel=>({...sel,gene:sel.gene||(catalog.features.includes('FOS')?'FOS':catalog.features[0])});
  async function request(path,body,signal){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'X-Wet-Lab-Token':window.WET_LAB_TOKEN,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Readout unavailable');return d;}
  function options(id,values,value){$(id).replaceChildren();for(const v of values){const o=node('option',v.title||v.id);o.value=v.id;$(id).append(o);}$(id).value=value;}
  function sync(){if(!selection)return;const pop=catalog.populations.find(p=>p.id===selection.populationID);const conditions=(catalog.conditions||[]).filter(c=>!pop?.conditionID||c.id===pop.conditionID);if(selection.conditionID&&!conditions.some(c=>c.id===selection.conditionID))conditions.push({id:selection.conditionID,title:selection.conditionID+' · unsupported for this population'});options('condition',conditions,selection.conditionID);for(const [id,key] of [['assay','assayID'],['specimen','specimenID'],['population','populationID'],['condition','conditionID'],['gene','gene']])$(id).value=selection[key]||'';}
  async function editSelection(changed){if(savingSelection)return;savingSelection=true;window.sharedWetLab.invalidateInspection();controller?.abort();requestNumber++;const next={...selection,assayID:$('assay').value,specimenID:$('specimen').value,populationID:$('population').value,conditionID:$('condition').value,gene:$('gene').value,experimentID:null};const pop=changed==='specimen'?(catalog.populations.find(p=>p.id===next.populationID&&(!p.specimenID||p.specimenID===next.specimenID))||catalog.populations.find(p=>p.specimenID===next.specimenID)):catalog.populations.find(p=>p.id===next.populationID);if(pop){next.populationID=pop.id;next.specimenID=pop.specimenID||next.specimenID;next.conditionID=pop.conditionID||next.conditionID;}sync();for(const id of ['specimen','population','condition','gene'])$(id).disabled=true;$('status').textContent='Saving selection to the shared workspace…';try{await window.sharedWetLab.selection(next);}finally{savingSelection=false;for(const id of ['specimen','population','condition','gene'])$(id).disabled=false;}const accepted=window.sharedWetLab.state.selection;if(!accepted||JSON.stringify(accepted)!==JSON.stringify(next)){$('status').textContent='Selection was not accepted. Review the current shared state.';return;}selection=accepted;viewTargets=null;run=null;comparisonScale=null;sync();document.getElementById('shared-genes').value=selection.gene;await loadField();}
  function support(){const s=window.sharedWetLab.state?.selectionSupport;if(!s)return 'Owner support is loading.';const r=s.reference||{};return `${s.populationAnchors==null?'Selected population':s.populationAnchors+' selected population cells'} · ${r.referenceCells??r.uniqueCells??s.referenceCells??'Unknown'} distinct reference cells. ${s.reason||''}`;}
  function draw(){if(!root||root.hidden)return;const host=$('readout');host.replaceChildren();$('support').textContent=support();$('record').textContent=run?`${run.revealed?'REVEALED OBSERVATION':'SEALED PREDICTION'} · ${run.id} · ${catalog.id}`:`${mode==='measured'?'MEASURED EVIDENCE REQUEST':'PREVIEW'} · ${catalog.id}`;
    if(!field){host.append(node('p','Choose a population and gene to request a bounded owner readout.'));return;}
    host.append(node('h2',`${field.gene} · ${selection.populationID}`),node('p',`${field.units} · ${field.scope||'Selected population'} · ${field.distributionStatus||'Distribution support unavailable'}`,'small'));
    if(field.modeled===false)host.append(node('p','UNAVAILABLE · this feature is not measured or modeled on the registered axis.','diagnostic'));
    if(mode==='measured'&&!field.arms?.some(a=>a.observed!=null))host.append(node('p','Measured outcomes are unavailable under the current access state. This action does not reveal sealed observations.','diagnostic'));
    const arms=(field.arms||[]).filter(a=>!viewTargets||viewTargets.includes(a.target)), values=arms.flatMap(a=>['control','predicted','observed'].map(k=>a[k]).filter(Number.isFinite));
    const max=comparisonScale?.max??Math.max(1,...values), min=comparisonScale?.min??Math.min(0,...values), range=Math.max(1e-12,max-min);
    const resMax=comparisonScale?.residual??Math.max(1,...arms.map(a=>Math.abs(a.residual||0)));
    const table=node('table');table.className='population-values';const head=node('tr');['Intervention',...layers.map(k=>({control:'Control reference',predicted:'Predicted mean',observed:'Measured endpoint',residual:'Prediction − observation'}[k])),'Support'].forEach(s=>head.append(node('th',s)));table.append(head);
    for(const a of arms){const row=node('tr');row.classList.toggle('active-population-arm',a.target===activeTarget);const label=node('td'),pick=node('button',`${a.target} · ${a.population||selection.populationID}`,'candidate-name');pick.onclick=()=>{activeTarget=a.target;draw();};label.append(pick);row.append(label);
      for(const k of layers){const cell=node('td'),value=a[k],bar=node('div',undefined,'population-bar');cell.append(node('span',fmt(value)));if(Number.isFinite(value)){const fill=node('i');fill.style.width=(k==='residual'?Math.abs(value)/resMax:(value-min)/range)*100+'%';fill.className=k==='residual'?(value<0?'negative':'positive'):k;bar.append(fill);cell.append(bar);}row.append(cell);}row.append(node('td',`${a.controlCells??'Unknown'} controls · ${a.outcomeCells??'sealed'} outcome cells · ${typeof a.evidence==='string'?a.evidence:'MODEL INFERENCE'}`));table.append(row);
    }host.append(table,node('p',`Shared endpoint scale ${fmt(min)} to ${fmt(max)} ${field.units}. Signed error: −${fmt(resMax)} to +${fmt(resMax)}; positive means overprediction.`,'small'));
    host.append(node('p','Population means do not establish a cell trajectory or a response distribution. Model agreement is not calibrated confidence.','diagnostic'));
  }
  async function loadField(){controller?.abort();controller=new AbortController();const number=++requestNumber;field=null;draw();const body={assayID:catalog.id,selection:{specimen:selection.specimenID,population:selection.populationID,condition:selection.conditionID,targets:viewTargets||[],objective:{genes:[selection.gene],preserveGenes:[],penalty:0}},query:{kind:'gene',gene:selection.gene,limit:128,offset:0,mode}};if(run?.id)body.id=run.id;
    // Access identity changes on reveal; only owner-authorized results share a key.
    const accessIdentity=run?.id?{record:run.id,revealed:run.revealed===true}:catalog.observationAccessFingerprint;const key=JSON.stringify([catalog.datasetFingerprint||catalog.sourceFingerprint||catalog.id,catalog.modelIdentity||catalog.modelBinding||catalog.id,body,accessIdentity]);const cacheable=accessIdentity!=null;$('status').textContent='Loading requested gene; the full expression matrix stays with NumiVivo…';try{const d=(cacheable?cache.get(key):null)||await request('readout',body,controller.signal);if(number!==requestNumber||root.hidden)return;if(cacheable)cache.set(key,d);if(cache.size>32)cache.delete(cache.keys().next().value);field=d;$('status').textContent='Owner readout loaded. No observations were revealed by inspection.';draw();}catch(e){if(e.name==='AbortError'||number!==requestNumber)return;$('status').textContent=e.message;}}
  async function mount(c,assays=[c]){controller?.abort();catalog=c;catalogs=assays;document.querySelector('main').hidden=true;if(!root){root=node('section');root.id='population-root';document.querySelector('main').after(root);root.innerHTML='<div class="mast"><div><div class="eyebrow">CELLULAR EXPERIMENT LABORATORY</div><h1>Which intervention changes this population?</h1><p>Define a molecular objective. Compare native predictions with authorized measurements.</p></div><span class="evidence">EXPERIMENTAL MODEL</span></div><div class="investigation-toolbar panel"><label>Assay<select id="population-assay"></select></label><label>Specimen<select id="population-specimen"></select></label><label>Population<select id="population-population"></select></label><label>Condition<select id="population-condition"></select></label><label>Gene<input id="population-gene" list="population-genes"><datalist id="population-genes"></datalist></label></div><p id="population-support" class="small"></p><p id="population-record" class="stage-badge"></p><div class="population-mode"><button id="population-predict">Predict a response</button><button id="population-measured">Explore accessible measurements</button></div><p id="population-status" role="status"></p><div class="comparison-canvases population-presentation"><section class="panel" id="population-readout" aria-live="polite"></section></div>';}
    root.hidden=false;document.querySelector('.version').textContent='v0.4 · experimental models';if(!headerHistory){headerHistory=document.getElementById('history-open').onclick;headerQualification=document.getElementById('benchmark-open').onclick;}document.getElementById('history-open').onclick=()=>{const history=document.getElementById('shared-history');history.closest('details').open=true;history.scrollIntoView({block:'nearest'});};document.getElementById('benchmark-open').onclick=()=>{document.getElementById('dialog-title').textContent='Registered cellular evidence';document.getElementById('dialog-content').replaceChildren(node('pre',JSON.stringify({id:catalog.id,model:catalog.modelIdentity||catalog.modelBinding,evidence:catalog.evidence,limits:catalog.limits,biologicalPromotion:false},null,2)));document.getElementById('dialog').showModal();};const shared=(window.sharedWetLab.state||await request('shared')).selection, matching=shared?.assayID===c.id;selection=matching?withGene(shared):{assayID:c.id,specimenID:c.populations[0]?.specimenID||c.specimens[0]?.id,populationID:c.populations[0]?.id,conditionID:c.populations[0]?.conditionID||c.conditions?.[0]?.id||'measured-endpoint',gene:c.features.includes('FOS')?'FOS':c.features[0]};run=null;field=null;viewTargets=null;activeTarget=c.targets[0]?.target;comparisonScale=null;
    options('assay',assays,c.id);options('specimen',c.specimens,selection.specimenID);options('population',c.populations.map(p=>({...p,title:(p.title||p.id)+(p.specimenID?' · '+p.specimenID:'')})),selection.populationID);options('condition',c.conditions||[{id:'measured-endpoint'}],selection.conditionID);$('genes').replaceChildren(...c.features.map(g=>{const o=node('option');o.value=g;return o;}));sync();$('assay').onchange=()=>window.setCatalog(catalogs.find(x=>x.id===$('assay').value));for(const id of ['specimen','population','condition','gene'])$(id).onchange=()=>editSelection(id).catch(e=>{$('status').textContent=e.message;sync();});$('predict').onclick=()=>{mode='predict';window.sharedWetLab.view('predicted');loadField();};$('measured').onclick=()=>{mode='measured';window.sharedWetLab.view('observed');loadField();};await window.sharedWetLab.mount(root);const latest=window.sharedWetLab.state.selection;if(latest?.assayID===c.id)selection=withGene(latest);else {await window.sharedWetLab.selection(selection);selection=withGene(window.sharedWetLab.state.selection);}sync();document.getElementById('shared-genes').value=selection.gene;await loadField();
  }
  async function inspectShared(card,gene,target){controller?.abort();const seq=++requestNumber,sel={...card.selection,gene};if(catalog.id!==sel.assayID){const next=await request('catalog?assay='+encodeURIComponent(sel.assayID));if(seq!==requestNumber)return;catalog=next;options('assay',catalogs,catalog.id);}const record=card.record?await request('experiments/'+card.record):null;if(seq!==requestNumber)return;const sharedSelection={...sel,experimentID:record?.id||null};await window.sharedWetLab.selection(sharedSelection);if(seq!==requestNumber||JSON.stringify(window.sharedWetLab.state.selection)!==JSON.stringify(sharedSelection))return;selection=sharedSelection;viewTargets=[...card.targets];run=record;activeTarget=target||card.targets[0];comparisonScale=card.comparisonScale;sync();await loadField();}
  function view(layer,multiple){layers=multiple?['control','predicted','observed','residual']:[layer];draw();}
  async function acceptSelection(sel){if(sel.assayID!==catalog.id){const c=catalogs.find(x=>x.id===sel.assayID)||await request('catalog?assay='+encodeURIComponent(sel.assayID));await window.setCatalog(c);return;}controller?.abort();requestNumber++;selection=withGene(sel);viewTargets=null;run=null;comparisonScale=null;sync();document.getElementById('shared-genes').value=selection.gene;await loadField();}
  return {mount,inspectShared,acceptSelection,loadField,draw,view,unmount(){controller?.abort();requestNumber++;if(root)root.hidden=true;if(headerHistory){document.getElementById('history-open').onclick=headerHistory;document.getElementById('benchmark-open').onclick=headerQualification;}},get state(){return {run,field,population:selection?.populationID,activeTarget,role:'direct',modelID:catalog?.id,comparisonScale};}};
})();
