"use strict";
window.sharedWetLab=(()=>{
 let state=null,root,busy=false,active=null,refreshingInspection=false;const focusedAxes=new Map();
 const n=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 const api=async(body)=>{const r=await fetch('/api/shared',{method:body?'POST':'GET',headers:{'X-Wet-Lab-Token':window.WET_LAB_TOKEN,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error);return d;};
 const status=text=>{document.getElementById('shared-status').textContent=text;};
 async function change(body){if(busy)return;busy=true;try{state=await api({...body,expectedRevision:state.revision,actor:'human'});render();}catch(e){status(e.message);state=await api();render();status(e.message);}finally{busy=false;}}
 async function selection(sel){if(!state||JSON.stringify(state.selection)===JSON.stringify(sel))return;await change({action:'selection',selection:sel});}
 function button(label,fn){const b=n('button',label);b.onclick=fn;return b;}
 async function show(card,gene,target,role,axis){const previous=active;active=card.id;gene=gene||(previous===card.id?window.learnedLab.state.field?.gene:null)||card.genes[0];axis=axis||focusedAxes.get(card.id)||card.axes?.[0];if(axis)focusedAxes.set(card.id,axis);const result=card.axisResults?.find(r=>r.modelID===axis?.modelID&&r.conditionID===axis?.conditionID);const view={...card,selection:{...card.selection,assayID:axis?.modelID||card.selection.assayID,conditionID:axis?.conditionID},record:result?.record||(!card.axisResults?card.record:null),result:result?.result};const values=[],residuals=[];for(const r of card.axisResults||[])for(const a of r.result.objectiveEvaluation?.arms||[])for(const g of a.genes)if(g.gene===gene){values.push(...[g.control,g.predicted,g.observed].filter(x=>x!=null));if(g.residual!=null)residuals.push(g.residual);}if(!values.length&&card.axisResults?.length){for(const r of card.axisResults){const response=await fetch('/api/spatial-feature',{method:'POST',headers:{'X-Wet-Lab-Token':window.WET_LAB_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({assayID:r.modelID,specimen:card.selection.specimenID,gene,id:r.record})});const f=await response.json();if(!response.ok){status(f.error);return;}for(const arm of f.arms){values.push(...[arm.control,arm.predicted,arm.observed].filter(x=>x!=null));if(arm.residual!=null)residuals.push(arm.residual);}}}view.comparisonScale=values.length?TissueIndex.sharedScale([values],[residuals]):null;try{await window.learnedLab.inspectShared(view,gene,target,role);}catch(e){status('Inspection failed: '+e.message);}}
 function render(){if(!root||!state)return;const container=document.getElementById('shared-cards');container.replaceChildren();
  document.getElementById('shared-selection').textContent=state.selection?`Selected: ${state.selection.specimenID} / ${state.selection.populationID} · workspace revision ${state.revision}`:'Select a population on the tissue to begin.';
  for(const d of state.drafts){const card=n('article');card.className='shared-card';card.dataset.id=d.id;card.append(n('h3',d.title),n('p',`${d.selection.specimenID} · ${d.selection.populationID} · ${d.status} · ${d.id.slice(0,8)}`));
   const axes=n('div');axes.className='model-condition-comparison';axes.append(n('strong','Compare model versions × supported conditions'));
   for(const m of state.models||[]){const label=n('label'),check=n('input');check.type='checkbox';check.checked=(d.modelIDs||[d.selection.assayID]).includes(m.id);check.disabled=d.status!=='draft';check.onchange=()=>change({action:'edit',id:d.id,modelIDs:check.checked?[...new Set([...(d.modelIDs||[d.selection.assayID]),m.id])]:(d.modelIDs||[d.selection.assayID]).filter(x=>x!==m.id)});label.append(check,n('span',`${m.version} · ${m.evidence}`));axes.append(label);}
   const conditions=[...new Set((state.models||[]).filter(m=>(d.modelIDs||[d.selection.assayID]).includes(m.id)).flatMap(m=>m.conditions.map(c=>c.id)))];for(const id of conditions){const label=n('label'),check=n('input');check.type='checkbox';check.checked=(d.conditionIDs||['measured-endpoint']).includes(id);check.disabled=d.status!=='draft';check.onchange=()=>change({action:'edit',id:d.id,conditionIDs:check.checked?[...new Set([...(d.conditionIDs||['measured-endpoint']),id])]:(d.conditionIDs||['measured-endpoint']).filter(x=>x!==id)});label.append(check,n('span',id));axes.append(label);}
   axes.append(n('p','Only registered condition/control pairs can execute. Dose, duration and receiving-population preservation remain unavailable for this spatial specimen.'));
   for(const a of d.axes||[]){axes.append(n('p',`${a.modelID} / ${a.conditionID}: ${a.canExecute?'MODEL INFERENCE · '+(d.result?.revealed?'REVEALED OBSERVATION + SEALED PREDICTION':d.record?'SEALED PREDICTION':'PREVIEW'): 'BLOCKED · '+a.reason}`));if(a.binding)axes.append(button('Inspect model and specimen binding',()=>{const dialog=document.getElementById('dialog');document.getElementById('dialog-title').textContent='Exact model / specimen / feature evidence';document.getElementById('dialog-content').replaceChildren(n('pre',JSON.stringify(a,null,2)));dialog.showModal();}));if(!a.canExecute&&d.status==='draft')for(const c of a.corrections||[]){if(c.conditionID)axes.append(button('Use supported condition '+c.conditionID,()=>change({action:'edit',id:d.id,conditionIDs:[c.conditionID]})));if(c.modelID)axes.append(button('Use registered model '+c.modelID,()=>change({action:'edit',id:d.id,modelIDs:[c.modelID]})));if(c.removeUnsupportedGenes&&d.genes.some(g=>!c.removeUnsupportedGenes.includes(g)))axes.append(button('Revise objective: remove '+c.removeUnsupportedGenes.join(', '),()=>change({action:'edit',id:d.id,genes:d.genes.filter(g=>!c.removeUnsupportedGenes.includes(g))})));}if(a.canExecute)axes.append(button('Inspect '+a.modelID+' / '+a.conditionID,()=>show(d,undefined,undefined,undefined,a)));}
   card.append(axes);
   const input=n('input');input.value=d.genes.join(', ');input.setAttribute('aria-label','Objective genes '+d.id.slice(0,8));input.disabled=d.status!=='draft';input.onchange=()=>change({action:'edit',id:d.id,genes:input.value.split(',').map(x=>x.trim()).filter(Boolean)});card.append(input);
   const cov=n('div');for(const g of d.coverage.genes){const b=button(`${g.gene}: ${g.referenceQuantity} specimen reference ${g.detectedReferenceCells}/${g.referenceCells} detected · ${g.predictionQuantity}`,()=>show(d,g.gene));cov.append(b);}card.append(cov,n('p','Objective: '+d.coverage.objective),n('p','Spatial preservation disabled: '+d.coverage.preservationReason));
   const candidates=n('div');candidates.className='candidate-tray';for(const t of d.supportedTargets){const b=button(t,()=>{if(d.status==='draft')change({action:'edit',id:d.id,targets:[...new Set([...d.targets,t])]});});b.disabled=d.status!=='draft';b.draggable=d.status==='draft';b.ondragstart=e=>e.dataTransfer.setData('text/plain',t);candidates.append(b);}card.append(candidates);
   const drop=n('div');drop.className='comparison-drop';drop.setAttribute('aria-label','Persistent comparison '+d.id.slice(0,8));drop.append(n('strong','Comparison · drag candidates here'));for(const t of d.targets)drop.append(button(t,()=>show(d,undefined,t)));drop.append(n('span','No intervention: reference change = 0'));drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();const t=e.dataTransfer.getData('text/plain');if(d.status==='draft'&&d.supportedTargets.includes(t))change({action:'edit',id:d.id,targets:[...new Set([...d.targets,t])]});};card.append(drop);const effects=n('div');effects.append(n('p',d.coverage.previewReference+' No reliable winner.'));for(const e of d.coverage.candidateEffects||[])if(d.targets.includes(e.target))effects.append(button(`${e.target} / ${e.role}: provisional utility ${e.predictedUtility.toFixed(4)} · locate population`,()=>show(d,undefined,e.target,e.role)));if(!d.record)card.append(effects);for(const a of d.axes||[])if(a.canExecute){const ev=d.axisResults?.find(x=>x.modelID===a.modelID&&x.conditionID===a.conditionID)?.result.objectiveEvaluation;const candidates=ev?.arms||a.coverage.candidateEffects||[];const table=n('div');table.append(n('strong',`${a.modelID} / ${a.conditionID} · ${ev?'SEALED PREDICTION':'PREVIEW'} · no calibrated winner`));for(const e of candidates)if(d.targets.includes(e.target))table.append(button(`${e.target} / ${e.role}: change from no intervention ${(-e.predictedUtility).toFixed(4)} log1p(CPM)${e.observedUtility!=null?' · observed '+(-e.observedUtility).toFixed(4):''}`,()=>show(d,undefined,e.target,e.role,a)));card.append(table);}const choices=(d.axisResults||[]).map(x=>x.result.objectiveEvaluation.numericalChoice);if(choices.length>1)card.append(n('p',new Set(choices).size===1?'Numerical rankings choose the same candidate across model versions; no demonstrated condition-sensitive advantage.':'Numerical model choices differ; inspect measured discrepancies. Neither ranking has calibrated confidence.'));
   const actions=n('div');actions.className='design-actions';if(d.status==='draft'){actions.append(button('Undo draft edit',()=>change({action:'undo',id:d.id})),button('Seal and execute comparison',()=>change({action:'seal',id:d.id})));}else{actions.append(button('Create editable revision',()=>change({action:'revise',id:d.id})));}
   if(d.record){actions.append(button('Inspect predicted effects',()=>show(d)),button('Replay',()=>change({action:'replay',id:d.id})));if(!d.result?.revealed)actions.append(button('Authorize reveal of measurements',()=>change({action:'reveal',id:d.id,authorizeReveal:true})));}
   if(d.status==='running')actions.append(button('Cancel operation',()=>change({action:'cancel',id:d.id})));
   if(d.status==='interrupted')actions.append(button('Recover stopped operation',()=>change({action:'recover',id:d.id})));
   card.append(actions);const op=state.operations.find(o=>o.id===d.operation);if(op)card.append(n('p',op.status+' · '+op.progress));
   if(d.result?.objectiveEvaluation){const ev=d.result.objectiveEvaluation;card.append(n('p','Numerical choice: '+ev.numericalChoice+' · '+ev.scope));if(ev.scores)card.append(n('p',`Observed choice utility ${ev.scores.selectedObservedUtility.toFixed(4)}; regret ${ev.scores.regret.toFixed(4)}; gain over random ${ev.scores.gainOverRandom.toFixed(4)}; gain over no intervention ${ev.scores.gainOverNoIntervention.toFixed(4)}.`));for(const a of ev.arms)for(const g of a.genes)card.append(button(`${a.target} / ${a.role} · ${g.gene} · predicted ${g.predicted?.toFixed(3)??'unavailable'} · observed ${g.observed?.toFixed(3)??'sealed'} · residual ${g.residual?.toFixed(3)??'unavailable'}`,()=>show(d,g.gene,a.target,a.role)));}
   if(d.result?.revealed){const fails=d.result.comparison.arms.filter(a=>a.diagnostics?.length);card.append(n('h4','Investigate discrepancies'));for(const a of fails)card.append(button(`${a.target} / ${a.role}: ${a.diagnostics.join('; ')}`,()=>show(d,undefined,a.target,a.role)));}
   container.append(card);
  }
  const history=document.getElementById('shared-history');history.replaceChildren();for(const h of state.history.slice(-15).reverse())history.append(n('li',`${new Date(h.time*1000).toLocaleTimeString()} · ${h.actor||'owner'} · ${h.action} · ${(h.draftID||'selection').slice(0,8)}`));
 }
 async function poll(){if(!root||busy||root.contains(document.activeElement)&&/INPUT/.test(document.activeElement.tagName))return;try{const next=await api();if(next.revision!==state?.revision){state=next;render();const d=state.drafts.find(x=>x.id===active),current=window.learnedLab.state.run,axis=focusedAxes.get(active);const result=d?.axisResults?.find(x=>x.modelID===axis?.modelID&&x.conditionID===axis?.conditionID);if(!refreshingInspection&&current&&result&&current.id===result.record&&current.revealed!==result.result.revealed){refreshingInspection=true;try{await show(d);}finally{refreshingInspection=false;}}}}catch(e){status('Workspace reconnecting: '+e.message);}}
 async function mount(parent){if(root)return;root=n('section');root.className='panel shared-workspace';root.innerHTML='<div class="eyebrow">SHARED WITH CODEX</div><h2>Design an experiment with this population</h2><p id="shared-selection"></p><p>Tell Codex which RNA program to change. Proposals appear here as editable cards. Human edits are checked before the next agent action.</p><div class="design-controls"><label>Reduce these genes<input id="shared-genes" value="Gfap" aria-label="New molecular objective"></label><button id="shared-propose">Create experiment proposal</button></div><p id="shared-status" role="status">Draft edits can be undone. Sealed experiments require a new revision. Observations open only on explicit authorization.</p><div id="shared-cards"></div><details><summary>Visual experiment history</summary><ol id="shared-history"></ol></details>';const grid=n('div');grid.className='shared-visual-grid';const canvases=parent.querySelector('.comparison-canvases');canvases.before(grid);grid.append(root,canvases);const advanced=n('details');advanced.className='panel';advanced.append(n('summary','Other experiment controls and receiver development inspection'));const arms=parent.querySelector('.arm-designer');const receiver=document.getElementById('learned-receiver-select')?.closest('.panel');if(arms)advanced.append(arms);if(receiver)advanced.append(receiver);parent.append(advanced);const old=document.getElementById('design-root');if(old){const fold=n('details');fold.append(n('summary','Dissociated assay comparisons · separate from this tissue'));fold.append(old);parent.append(fold);}state=await api();render();document.getElementById('shared-propose').onclick=()=>change({action:'propose',genes:document.getElementById('shared-genes').value.split(',').map(x=>x.trim()).filter(Boolean),targets:[]});setInterval(poll,1000);}
 return {mount,selection,get state(){return state;}};
})();
