"use strict";
// Shared cards and read-only decision evidence. NumiVivo owns every prediction.
window.sharedWetLab=(()=>{
 let state=null,root,active=null,layer='control',compare=false,editing=Promise.resolve(),inspecting=Promise.resolve(),busy=0;
 const focusedAxes=new Map(),opened=new Set(),timers=new Map();
 const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const api=async(body,path='/api/shared')=>{const r=await fetch(path,{method:body?'POST':'GET',headers:{'X-Wet-Lab-Token':window.WET_LAB_TOKEN,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error);return d;};
 const status=text=>{document.getElementById('shared-status').textContent=text;};
 const button=(text,fn,cls)=>{const b=n('button',text,cls);b.type='button';b.onclick=fn;return b;};
 const fmt=v=>v==null?'UNAVAILABLE':Number(v).toFixed(4);
 function change(body){editing=editing.then(async()=>{busy++;status('Updating shared proposal and population coverage…');try{const request=typeof body==='function'?body(state):body;state=await api({...request,expectedRevision:state.revision,actor:'human'});if(request.action==='propose'){active=state.drafts.at(-1).id;opened.add(active);}render();status('Shared proposal saved. Coverage updated; numerical order is not a recommendation.');}catch(e){state=await api();render();status(e.message+' Your rejected edit was not applied. Review the shared proposal.');}finally{busy--;}});return editing;}
 async function selection(sel){if(!state||JSON.stringify(state.selection)===JSON.stringify(sel))return;await change({action:'selection',selection:sel});}
 function view(mode=layer,multiple=compare){layer=mode;compare=multiple;const lab=document.getElementById('learned-root');lab.classList.toggle('single-specimen',!compare);lab.dataset.layer=layer;for(const b of document.querySelectorAll('[data-view-layer]'))b.setAttribute('aria-pressed',String(b.dataset.viewLayer===layer));document.getElementById('shared-compare-views').setAttribute('aria-pressed',String(compare));window.learnedLab.draw();}
 function show(...args){inspecting=inspecting.then(()=>showNow(...args)).catch(e=>status('Inspection failed: '+e.message));return inspecting;}
 async function showNow(card,gene,target,role,axis){const previous=active;active=card.id;opened.add(active);gene=gene||(previous===card.id?window.learnedLab.state.field?.gene:null)||card.genes[0];axis=axis||focusedAxes.get(card.id)||card.axes?.find(x=>x.canExecute);if(!axis)return;focusedAxes.set(card.id,axis);const result=card.axisResults?.find(r=>r.modelID===axis.modelID&&r.conditionID===axis.conditionID);const v={...card,selection:{...card.selection,assayID:axis.modelID,conditionID:axis.conditionID},record:result?.record||(!card.axisResults?card.record:null),result:result?.result};const values=[],residuals=[];
  for(const r of card.axisResults||[])for(const a of r.result.objectiveEvaluation?.arms||[])for(const g of a.genes)if(g.gene===gene){values.push(...[g.control,g.predicted,g.observed].filter(x=>x!=null));if(g.residual!=null)residuals.push(g.residual);}
  if(!values.length&&card.axisResults?.length)for(const r of card.axisResults){const f=await api({assayID:r.modelID,specimen:card.selection.specimenID,gene,id:r.record},'/api/spatial-feature');for(const a of f.arms){values.push(...[a.control,a.predicted,a.observed].filter(x=>x!=null));if(a.residual!=null)residuals.push(a.residual);}}
  v.comparisonScale=values.length?TissueIndex.sharedScale([values],[residuals]):null;await window.learnedLab.inspectShared(v,gene,target,role);view(result?.result.revealed?'residual':'predicted');render();await evidence(card,axis,gene,window.learnedLab.state.activeTarget,window.learnedLab.state.role);
 }
 function supportLine(s){if(!s)return 'Population support unavailable';const r=s.reference;return `${s.outcomeCells} outcome cells · ${r.referenceCells} reference cells (${r.safeHarbourCells} safe-harbour, ${r.barcodeNegativeCells} barcode-negative) · training target ${s.trainingTargetSeen===null?'unknown':s.trainingTargetSeen?'seen':'unseen'} / population groups ${s.trainingPopulationGroups??'unknown'} · biological units ${JSON.stringify(s.biologicalUnits)} · ${s.trainingContext}`;}
 async function evidence(card,axis,gene,target,role){const panel=document.getElementById('shared-decision-evidence');panel.replaceChildren(n('h2',`${target} · ${card.selection.populationID} · ${gene}`));const s=(axis.populationSupport||card.decisionSupport)?.candidates.find(x=>x.target===target&&x.role===role);panel.append(n('p',supportLine(s),'support-summary'),n('p','Numerical ordering only. Model agreement is not calibrated confidence.','diagnostic'));if(s)for(const reason of s.reasons)panel.append(n('p',reason,'small'));
  const result=card.axisResults?.find(r=>r.modelID===axis.modelID&&r.conditionID===axis.conditionID);if(!result){panel.append(n('p','PREVIEW · anchor-matched campaign reference. Seal to compute the exact pooled-reference prediction.'));return;}
  const d=await api({assayID:axis.modelID,id:result.record,gene,target,role},'/api/gene-evidence');panel.append(n('p',`${d.stage} · ${axis.modelID} · ${d.units}`));const table=n('table'),head=n('tr');['Quantity','Value','Prediction − observation'].forEach(x=>head.append(n('th',x)));table.append(head);for(const [label,value,error] of [['Model',d.predicted,d.predictedResidual],['Measured endpoint',d.observed,null],['No change',d.control,d.noChangeResidual],['Matched baseline',d.matchedBaseline,d.matchedResidual]]){const row=n('tr');[label,fmt(value),fmt(error)].forEach(x=>row.append(n('td',x)));table.append(row);}panel.append(table,n('p',`${d.population} / ${role} · ${d.outcomeCells==null?'Measurements sealed':d.outcomeCells+' measured outcome cells'}. Fitted training-ranking comparator unavailable.`,'small'));
  const genes=n('div');genes.append(n('span','Objective contributors: '));for(const g of card.genes)genes.append(button(g,()=>show(card,g,target,role,axis),'chip'));panel.append(genes);panel.hidden=false;
 }
 function coverage(parent,support){if(!support)return;const r=support.reference;parent.append(n('p',`${support.populationAnchors} selected population anchors · ${r.referenceCells} reference cells · ${r.safeHarbourCells} verified safe-harbour controls`,'support-summary'));if(r.barcodeNegativeCells)parent.append(n('p',`${r.barcodeNegativeCells} barcode-negative references: untreated status is unknown.`,'diagnostic'));for(const g of support.genes)parent.append(n('p',`${g.gene}: ${g.status} · ${g.detectedReferenceCells}/${g.referenceCells} selected-reference cells detected · ${g.predictionStatus}`,'small'));parent.append(n('p',support.reason,'small'));}
 function modelChanges(card,parent){const d=card.modelDifference;if(!d?.available){parent.append(n('p',d?.reason||'Seal a comparison to inspect exact model differences.','small'));return;}for(const c of d.comparisons){const section=n('details');section.append(n('summary',`${c.leftModel} → ${c.rightModel}: ${c.rankingsChanged?'candidate ranks changed':'same numerical ordering'}`));section.append(n('p','Rank agreement does not establish confidence. Gene contributions below sum to the change in objective utility.','small'));for(const a of c.candidates){const row=n('div',undefined,'rank-difference');row.append(button(`${a.target}: rank ${a.leftRank} → ${a.rightRank}; utility ${fmt(a.leftUtility)} → ${fmt(a.rightUtility)}`,()=>show(card,undefined,a.target==='no-intervention'?undefined:a.target)));for(const g of a.genes)row.append(button(`${g.gene}: contribution ${fmt(g.utilityDifference)}`,()=>show(card,g.gene,a.target,'direct',card.axes.find(x=>x.modelID===c.rightModel&&x.conditionID===c.rightCondition)),'chip'));section.append(row);}parent.append(section);}}
 function flush(){for(const [id,t] of timers){clearTimeout(t.timer);timers.delete(id);change(t.body);}return editing;}
 function render(){if(!root||!state)return;const focused=document.activeElement,focusKey=focused?.dataset.editKey,pos=focused?.selectionStart;const container=document.getElementById('shared-cards');container.replaceChildren();const sel=state.selection;document.getElementById('shared-selection').textContent=sel?`${sel.populationID} · ${sel.specimenID}`:'Select a population on the specimen';const summary=document.getElementById('shared-population-support');summary.replaceChildren();coverage(summary,state.selectionSupport);const markers=document.getElementById('shared-marker-options');markers.replaceChildren();for(const g of state.selectionSupport?.availableMarkers||[])markers.append(button(`${g.gene} ${g.detectedReferenceCells}/${g.referenceCells}`,()=>{document.getElementById('shared-genes').value=g.gene;},'chip'));markers.append(n('p','Available markers, not recommended biological programs. Define the molecular objective with Codex.','small'));
  for(const d of [...state.drafts].reverse()){const wrap=n('details');wrap.className='proposal';wrap.open=opened.has(d.id)||(active===null&&d===state.drafts.at(-1));wrap.ontoggle=()=>{if(wrap.open)opened.add(d.id);else opened.delete(d.id);};wrap.append(n('summary',`${d.title} · ${d.status}`));const card=n('article');card.dataset.id=d.id;card.className='shared-card';card.append(n('p',`${d.selection.populationID} / ${d.selection.specimenID} · ${d.id.slice(0,8)}`,'small'));const stage=d.status==='draft'?'PREVIEW':d.result?.revealed?'REVEALED OBSERVATION':'SEALED PREDICTION';card.append(n('strong',stage,'stage-badge'));const label=n('label','Reduce mean log1p(CPM) of '),input=n('input');input.value=d.genes.join(', ');input.disabled=d.status!=='draft';input.dataset.editKey=d.id;input.setAttribute('aria-label','Objective genes '+d.id.slice(0,8));input.oninput=()=>{status('Objective edit pending; coverage will update before execution.');for(const b of card.querySelectorAll('button'))if(b.textContent==='Seal and execute')b.disabled=true;const genes=input.value.split(',').map(x=>x.trim()).filter(Boolean);if(!genes.length)return;const prior=timers.get(d.id);if(prior)clearTimeout(prior.timer);const body={action:'edit',id:d.id,genes};timers.set(d.id,{body,timer:setTimeout(()=>{timers.delete(d.id);change(body);},350)});};label.append(input);card.append(label);coverage(card,d.decisionSupport);card.append(n('p','Readouts: direct and neighboring population RNA, fixed measured geometry. Spatial preservation unavailable.','small'));
   const candidates=n('div');candidates.className='candidate-tray';for(const t of d.supportedTargets){const b=button(`${d.targets.includes(t)?'✓ ':''}${t}`,()=>change(s=>{const current=s.drafts.find(x=>x.id===d.id);return {action:'edit',id:d.id,targets:current.targets.includes(t)?current.targets.filter(x=>x!==t):[...current.targets,t]};}),'chip');b.disabled=d.status!=='draft';b.draggable=false;let pointer=null,suppressClick=false;const toggle=b.onclick;b.onclick=e=>{if(!suppressClick)toggle(e);};b.onpointerdown=e=>{pointer={id:e.pointerId,x:e.clientX,y:e.clientY};b.setPointerCapture(e.pointerId);};b.onpointerup=e=>{if(!pointer)return;const moved=Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>6;pointer=null;if(!moved)return;suppressClick=true;setTimeout(()=>{suppressClick=false;},0);const destination=document.elementFromPoint(e.clientX,e.clientY)?.closest('.comparison-drop')?.closest('.shared-card');const targetCard=state.drafts.find(x=>x.id===destination?.dataset.id);if(targetCard?.status==='draft'&&targetCard.supportedTargets.includes(t))change(s=>({action:'edit',id:targetCard.id,targets:[...new Set([...s.drafts.find(x=>x.id===targetCard.id).targets,t])]}));};b.onpointercancel=()=>{pointer=null;};candidates.append(b);}card.append(candidates);const drop=n('div');drop.className='comparison-drop';drop.setAttribute('aria-label','Persistent comparison '+d.id.slice(0,8));drop.append(n('strong','Candidate comparison'));for(const target of d.targets){const support=d.decisionSupport?.candidates.find(x=>x.target===target&&x.role==='direct');const row=n('div',undefined,'candidate-support');row.append(button(target,()=>show(d,undefined,target),'candidate-name'),n('p',support?`${support.outcomeCells} outcome cells · ${support.reference.safeHarbourCells} verified controls · ${support.trainingTargetSeen?'training target seen':'training overlap unavailable'}`:'Unsupported intervention; request retained','small'),n('p',support?'Insufficient evidence to recommend':'Choose an explicit supported correction','diagnostic'));drop.append(row);}drop.append(n('p','No intervention · objective change = 0','small'));drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();const t=e.dataTransfer.getData('text/plain');if(d.status==='draft'&&d.supportedTargets.includes(t))change(s=>({action:'edit',id:d.id,targets:[...new Set([...s.drafts.find(x=>x.id===d.id).targets,t])]}));};card.append(drop);
   const axes=n('details');axes.append(n('summary',`${d.modelIDs?.length||1} models · ${(d.conditionIDs||['measured-endpoint']).join(', ')}`));for(const m of state.models||[]){const label=n('label'),check=n('input');check.type='checkbox';check.checked=(d.modelIDs||[d.selection.assayID]).includes(m.id);check.disabled=d.status!=='draft';check.onchange=()=>change({action:'edit',id:d.id,modelIDs:check.checked?[...new Set([...(d.modelIDs||[d.selection.assayID]),m.id])]:(d.modelIDs||[d.selection.assayID]).filter(x=>x!==m.id)});label.append(check,n('span',m.version));axes.append(label);}for(const id of [...new Set((state.models||[]).filter(m=>d.modelIDs?.includes(m.id)).flatMap(m=>m.conditions.map(c=>c.id)))]){const label=n('label'),check=n('input');check.type='checkbox';check.checked=d.conditionIDs?.includes(id);check.disabled=d.status!=='draft';check.onchange=()=>change({action:'edit',id:d.id,conditionIDs:check.checked?[...new Set([...(d.conditionIDs||[]),id])]:(d.conditionIDs||[]).filter(x=>x!==id)});label.append(check,n('span',id));axes.append(label);}card.append(axes);
   for(const a of d.axes||[]){if(!a.canExecute){const blocked=n('div',undefined,'blocked-intent');blocked.append(n('b',a.modelID+' · BLOCKED'),n('p',a.reason));for(const c of a.corrections||[]){if(c.conditionID)blocked.append(button('Explicit correction: '+c.conditionID,()=>change({action:'edit',id:d.id,conditionIDs:[c.conditionID]})));if(c.removeUnsupportedGenes&&d.genes.some(g=>!c.removeUnsupportedGenes.includes(g)))blocked.append(button('Revise objective: remove '+c.removeUnsupportedGenes.join(', '),()=>change({action:'edit',id:d.id,genes:d.genes.filter(g=>!c.removeUnsupportedGenes.includes(g))})));if(c.removeUnsupportedTargets&&d.targets.some(t=>!c.removeUnsupportedTargets.includes(t)))blocked.append(button('Revise candidates: remove '+c.removeUnsupportedTargets.join(', '),()=>change({action:'edit',id:d.id,targets:d.targets.filter(t=>!c.removeUnsupportedTargets.includes(t))})));if(c.specimenID||c.populationID)blocked.append(n('p','Select '+(c.specimenID?'specimen '+c.specimenID:'population '+c.populationID)+' in the specimen toolbar and create a new proposal; this request is retained.','small'));if(c.modelID)blocked.append(button('Use registered model '+c.modelID,()=>change({action:'edit',id:d.id,modelIDs:[c.modelID]})));}card.append(blocked);continue;}
    const result=d.axisResults?.find(x=>x.modelID===a.modelID&&x.conditionID===a.conditionID);card.append(button('Inspect '+a.modelID,()=>show(d,undefined,undefined,undefined,a),'inspect-model'));const ev=result?.result.objectiveEvaluation;const arms=ev?.arms||a.coverage?.candidateEffects||[];for(const arm of arms.filter(x=>d.targets.includes(x.target)&&x.role==='direct'))card.append(button(`${arm.target}: predicted change ${fmt(-arm.predictedUtility)}${arm.observedUtility!=null?' · observed '+fmt(-arm.observedUtility):''}`,()=>show(d,undefined,arm.target,arm.role,a),'effect-link'));if(ev?.scores)card.append(button(`Inspect failed objective · choice ${ev.numericalChoice} · measured utility ${fmt(ev.scores.selectedObservedUtility)} · regret ${fmt(ev.scores.regret)}`,()=>{view('residual',true);show(d,d.genes[0],ev.numericalChoice==='no-intervention'?d.targets[0]:ev.numericalChoice,'direct',a);},'failure-link'));}
   modelChanges(d,card);card.append(n('p',d.decisionSupport?.trainingRankingComparator||'Fitted training-ranking comparator unavailable.','small'));const actions=n('div',undefined,'design-actions');if(d.status==='draft'){actions.append(button('Undo draft edit',()=>change({action:'undo',id:d.id})));const seal=button('Seal and execute',async()=>{await flush();change({action:'seal',id:d.id});},'primary');seal.disabled=!d.coverage.canExecute||!d.targets.length;actions.append(seal);}else actions.append(button('Create editable revision',()=>change({action:'revise',id:d.id})));
   if(d.record){actions.append(button('Replay',()=>change({action:'replay',id:d.id})));if(!d.result?.revealed)actions.append(button('Authorize reveal of measurements',()=>change({action:'reveal',id:d.id,authorizeReveal:true})));}if(d.status==='running')actions.append(button('Cancel operation',()=>change({action:'cancel',id:d.id})));if(d.status==='interrupted')actions.append(button('Recover stopped operation',()=>change({action:'recover',id:d.id})));card.append(actions);const op=state.operations.find(x=>x.id===d.operation);if(op)card.append(n('p',op.progress,'small'));wrap.append(card);container.append(wrap);
  }
  const history=document.getElementById('shared-history');history.replaceChildren();for(const h of state.history.slice(-15).reverse())history.append(n('li',`${new Date(h.time*1000).toLocaleTimeString()} · ${h.actor||'owner'} · ${h.action} · ${(h.draftID||'selection').slice(0,8)}`));if(focusKey){const el=[...root.querySelectorAll('[data-edit-key]')].find(x=>x.dataset.editKey===focusKey);if(el){el.focus({preventScroll:true});if(pos!=null)el.setSelectionRange(pos,pos);}}
 }
 async function poll(){if(!root||busy||timers.size||root.contains(document.activeElement)&&/INPUT/.test(document.activeElement.tagName))return;try{const next=await api();if(next.revision!==state?.revision){state=next;render();const d=state.drafts.find(x=>x.id===active),axis=focusedAxes.get(active),r=d?.axisResults?.find(x=>x.modelID===axis?.modelID&&x.conditionID===axis?.conditionID);if(r&&window.learnedLab.state.run?.id===r.record&&window.learnedLab.state.run.revealed!==r.result.revealed)show(d);}}catch(e){status('Workspace reconnecting: '+e.message);}}
 async function mount(parent){if(root)return;root=n('section',undefined,'panel shared-workspace');root.innerHTML='<div class="eyebrow">DESIGN WITH CODEX</div><h2 id="shared-selection"></h2><details><summary>Population measurement support</summary><div id="shared-population-support"></div></details><label>Molecular objective<input id="shared-genes" value="Clu" aria-label="New molecular objective"></label><div id="shared-marker-options"></div><button id="shared-propose" class="primary">Propose experiment</button><p id="shared-status" role="status">Tell Codex your desired molecular change. Draft edits are shared. Reveal is a separate authorized action.</p><div id="shared-cards"></div><details><summary>Visual experiment history</summary><ol id="shared-history"></ol></details>';
  const grid=n('div',undefined,'shared-visual-grid'),canvasColumn=n('div',undefined,'specimen-column'),canvases=parent.querySelector('.comparison-canvases'),toolbar=n('div',undefined,'specimen-view-controls');for(const mode of ['control','predicted','observed','residual']){const b=button({control:'Specimen / reference',predicted:'Prediction',observed:'Observation',residual:'Error'}[mode],()=>view(mode), 'chip');b.dataset.viewLayer=mode;toolbar.append(b);}const compareButton=button('Compare synchronized views',()=>view(layer,!compare));compareButton.id='shared-compare-views';toolbar.append(compareButton);const info=n('section',undefined,'panel decision-evidence');info.id='shared-decision-evidence';info.append(n('p','Select a candidate to inspect its population support, gene contributions and baseline differences.'));canvases.before(grid);canvasColumn.append(toolbar,canvases,info);grid.append(canvasColumn,root);
  const advanced=n('details',undefined,'panel');advanced.append(n('summary','Additional assay controls and receiver development'));for(const el of [parent.querySelector('.arm-designer'),document.getElementById('learned-receiver-select')?.closest('.panel'),parent.querySelector('.investigation-bottom'),parent.querySelector('.reveal-strip')])if(el)advanced.append(el);parent.append(advanced);const old=document.getElementById('design-root');if(old){const fold=n('details');fold.append(n('summary','Dissociated assay comparisons'));fold.append(old);parent.append(fold);}state=await api();render();view();document.getElementById('shared-propose').onclick=()=>change({action:'propose',genes:document.getElementById('shared-genes').value.split(',').map(x=>x.trim()).filter(Boolean),targets:[],title:'Molecular response objective'});setInterval(poll,1000);
 }
 return {mount,selection,view,show,get state(){return state;}};
})();
