// GENERATED FILE: python/generate_contact_scatter_abi.py
#pragma once

#include "metalrobo/gpu_types.h"

// One schema owns host and Metal argument tables. Changing a
// binding requires an ABI-version change.
#define MR_CONTACT_SCATTER_ABI_VERSION 1u

enum MRWorldManifoldRecordScatterBuffer : mr_u32 {
    MR_RECORD_SCATTER_DISPATCH = 0u,
    MR_RECORD_SCATTER_ELIGIBLE_PAIRS = 1u,
    MR_RECORD_SCATTER_RAW_STAGING = 2u,
    MR_RECORD_SCATTER_MANIFOLD_HEADERS = 3u,
    MR_RECORD_SCATTER_MANIFOLD_POINTS = 4u,
    MR_RECORD_SCATTER_RECORDS = 5u,
    MR_RECORD_SCATTER_STATUSES = 6u,
    MR_RECORD_SCATTER_OUTPUT_PAIRS = 7u,
    MR_RECORD_SCATTER_OUTPUT_RAW_CONTACTS = 8u,
    MR_RECORD_SCATTER_OUTPUT_RAW_PAIR_INDICES = 9u,
    MR_RECORD_SCATTER_OUTPUT_MANIFOLD_HEADERS = 10u,
    MR_RECORD_SCATTER_OUTPUT_MANIFOLD_POINTS = 11u,
    MR_RECORD_SCATTER_BUFFER_COUNT = 12u,
};

enum MRWorldManifoldIRScatterBuffer : mr_u32 {
    MR_IR_SCATTER_DISPATCH = 0u,
    MR_IR_SCATTER_SHAPES = 1u,
    MR_IR_SCATTER_MATERIALS = 2u,
    MR_IR_SCATTER_BODIES = 3u,
    MR_IR_SCATTER_ARTICULATIONS = 4u,
    MR_IR_SCATTER_ELIGIBLE_PAIRS = 5u,
    MR_IR_SCATTER_MANIFOLD_HEADERS = 6u,
    MR_IR_SCATTER_MANIFOLD_POINTS = 7u,
    MR_IR_SCATTER_RECORDS = 8u,
    MR_IR_SCATTER_STATUSES = 9u,
    MR_IR_SCATTER_CONTACTS = 10u,
    MR_IR_SCATTER_CONTACT_METADATA = 11u,
    MR_IR_SCATTER_BLOCKS = 12u,
    MR_IR_SCATTER_ENDPOINTS = 13u,
    MR_IR_SCATTER_ENDPOINT_RUNTIME = 14u,
    MR_IR_SCATTER_ROWS = 15u,
    MR_IR_SCATTER_CONES = 16u,
    MR_IR_SCATTER_POINT_QUERIES = 17u,
    MR_IR_SCATTER_BODY_DYNAMIC_NODES = 18u,
    MR_IR_SCATTER_BODY_PARAMETERS = 19u,
    MR_IR_SCATTER_BUFFER_COUNT = 20u,
};

#if defined(__cplusplus)
static_assert(MR_RECORD_SCATTER_BUFFER_COUNT <= 31u);
static_assert(MR_IR_SCATTER_BUFFER_COUNT <= 31u);
#endif
