// GENERATED FILE: python/generate_runtime_abi.py
#pragma once

#include "metalrobo/gpu_types.h"

// One schema owns the native resource table and shared kernel
// bindings. Any persisted layout change increments this version.
#define MR_RUNTIME_ABI_VERSION 20u
#define MR_RUNTIME_PIPELINE_COUNT 92u
#define MR_RUNTIME_PIPELINE_GROUP_COUNT 11u
#define MR_SENSOR_PROGRAM_ABI_VERSION 9u
#define MR_SENSOR_DISPATCH_HAS_RESETS 1u
#define MR_SENSOR_DISPATCH_HAS_CONTACTS 2u

typedef struct MR_ALIGN16 MRSensorProgramHeaderGPU {
    mr_u64 sensorFingerprint;
    mr_u64 worldFingerprint;
    mr_uint4 counts;
    mr_uint4 executionCounts;
    mr_uint4 layout;
    mr_uint4 reserved;
} MRSensorProgramHeaderGPU;

typedef struct MR_ALIGN16 MRSensorDescriptorGPU {
    mr_uint4 identity;
    mr_uint4 output;
    mr_uint4 schedule;
    mr_uint4 dimensions;
    mr_uint4 source;
    mr_uint4 filter;
    mr_uint4 randomIdentity;
    mr_float4 localPosition;
    mr_float4 localOrientation;
    mr_float4 timing;
    mr_float4 noise;
    mr_float4 range;
    mr_float4 intrinsics;
    mr_float4 distortion;
} MRSensorDescriptorGPU;

typedef struct MR_ALIGN16 MRSensorDispatchGPU {
    mr_uint4 counts;
    mr_uint4 controlPeriodAndStrides;
    mr_u64 seed;
    mr_u64 sensorFingerprint;
} MRSensorDispatchGPU;

typedef struct MR_ALIGN16 MRSensorRuntimeStateGPU {
    mr_uint4 phaseAndSequence;
    mr_uint4 timestampAgeValidity;
    mr_uint4 previousSampleTimestamp;
    mr_uint4 randomIdentity;
    mr_float4 previousPointVelocity;
} MRSensorRuntimeStateGPU;

typedef struct MR_ALIGN16 MRSensorSampleMetadataGPU {
    mr_uint4 sequenceAndTimestamp;
    mr_uint4 ageValidityAndLayout;
} MRSensorSampleMetadataGPU;

typedef struct MR_ALIGN16 MRActuatorRuntimeStateGPU {
    mr_float4 command;
    mr_float4 effort;
    mr_float4 envelope;
    mr_uint4 status;
} MRActuatorRuntimeStateGPU;

typedef struct MR_ALIGN16 MRTaskKinematicFrameGPU {
    mr_uint4 layout;
    mr_uint4 coordinates;
} MRTaskKinematicFrameGPU;

typedef struct MR_ALIGN16 MRLearningPublicationDispatchGPU {
    mr_uint4 floatCounts;
    mr_uint4 recordCounts;
    mr_u64 policyRevision;
    mr_u64 taskFingerprint;
    mr_u64 validationToken;
    mr_u64 reserved;
} MRLearningPublicationDispatchGPU;

typedef struct MR_ALIGN16 MRLearningPublicationStatusGPU {
    mr_uint4 result;
    mr_uint4 checkedCounts;
    mr_u64 policyRevision;
    mr_u64 taskFingerprint;
    mr_u64 validationToken;
    mr_u64 reserved;
} MRLearningPublicationStatusGPU;

enum MRWorldManifoldRecordScatterBuffer : mr_u32 {
    MR_RECORD_SCATTER_DISPATCH = 0u,
    MR_RECORD_SCATTER_ELIGIBLE_PAIRS = 1u,
    MR_RECORD_SCATTER_RAW_STAGING = 2u,
    MR_RECORD_SCATTER_MANIFOLD_HEADERS = 3u,
    MR_RECORD_SCATTER_MANIFOLD_POINTS = 4u,
    MR_RECORD_SCATTER_RECORDS = 5u,
    MR_RECORD_SCATTER_STATUSES = 6u,
    MR_RECORD_SCATTER_OUTPUT_PAIRS = 7u,
    MR_RECORD_SCATTER_OUTPUT_RAW_CONTACTS = 8u,
    MR_RECORD_SCATTER_OUTPUT_RAW_PAIR_INDICES = 9u,
    MR_RECORD_SCATTER_OUTPUT_MANIFOLD_HEADERS = 10u,
    MR_RECORD_SCATTER_OUTPUT_MANIFOLD_POINTS = 11u,
    MR_RECORD_SCATTER_BUFFER_COUNT = 12u,
};

enum MRWorldManifoldIRScatterBuffer : mr_u32 {
    MR_IR_SCATTER_DISPATCH = 0u,
    MR_IR_SCATTER_SHAPES = 1u,
    MR_IR_SCATTER_MATERIALS = 2u,
    MR_IR_SCATTER_BODIES = 3u,
    MR_IR_SCATTER_ARTICULATIONS = 4u,
    MR_IR_SCATTER_ELIGIBLE_PAIRS = 5u,
    MR_IR_SCATTER_MANIFOLD_HEADERS = 6u,
    MR_IR_SCATTER_MANIFOLD_POINTS = 7u,
    MR_IR_SCATTER_RECORDS = 8u,
    MR_IR_SCATTER_STATUSES = 9u,
    MR_IR_SCATTER_CONTACTS = 10u,
    MR_IR_SCATTER_CONTACT_METADATA = 11u,
    MR_IR_SCATTER_BLOCKS = 12u,
    MR_IR_SCATTER_ENDPOINTS = 13u,
    MR_IR_SCATTER_ENDPOINT_RUNTIME = 14u,
    MR_IR_SCATTER_ROWS = 15u,
    MR_IR_SCATTER_CONES = 16u,
    MR_IR_SCATTER_POINT_QUERIES = 17u,
    MR_IR_SCATTER_BODY_DYNAMIC_NODES = 18u,
    MR_IR_SCATTER_BODY_PARAMETERS = 19u,
    MR_IR_SCATTER_BUFFER_COUNT = 20u,
};

enum MRWorldNumiPreparationBuffer : mr_u32 {
    MR_NUMI_PREPARE_DISPATCH = 0u,
    MR_NUMI_PREPARE_NUMERICS = 1u,
    MR_NUMI_PREPARE_SCENE_BODY_INDICES = 2u,
    MR_NUMI_PREPARE_ARTICULATION_FACTORS = 3u,
    MR_NUMI_PREPARE_POINT_JACOBIANS = 4u,
    MR_NUMI_PREPARE_CANDIDATE_VELOCITY = 5u,
    MR_NUMI_PREPARE_CANDIDATE_BODIES = 6u,
    MR_NUMI_PREPARE_CONTACTS = 7u,
    MR_NUMI_PREPARE_ENDPOINTS = 8u,
    MR_NUMI_PREPARE_BLOCKS = 9u,
    MR_NUMI_PREPARE_EVALUATED_ROWS = 10u,
    MR_NUMI_PREPARE_EVALUATED_CONES = 11u,
    MR_NUMI_PREPARE_STATUSES = 12u,
    MR_NUMI_PREPARE_SOLVER_BLOCKS = 13u,
    MR_NUMI_PREPARE_DYNAMICS = 14u,
    MR_NUMI_PREPARE_JACOBIAN = 15u,
    MR_NUMI_PREPARE_BIAS = 16u,
    MR_NUMI_PREPARE_FREE_VELOCITY = 17u,
    MR_NUMI_PREPARE_WARM_VELOCITY = 18u,
    MR_NUMI_PREPARE_WARM_IMPULSES = 19u,
    MR_NUMI_PREPARE_ROD_NODES = 20u,
    MR_NUMI_PREPARE_ROD_EDGES = 21u,
    MR_NUMI_PREPARE_ROD_COLLIDERS = 22u,
    MR_NUMI_PREPARE_ROD_WITNESSES = 23u,
    MR_NUMI_PREPARE_ROD_WITNESS_INDICES = 24u,
    MR_NUMI_PREPARE_ROD_FACTOR_CACHES = 25u,
    MR_NUMI_PREPARE_ROD_OPERATOR_ARENA = 26u,
    MR_NUMI_PREPARE_BUFFER_COUNT = 27u,
};

enum MRTaskFrameRefreshBuffer : mr_u32 {
    MR_TASK_FRAME_REFRESH_DISPATCH = 0u,
    MR_TASK_FRAME_REFRESH_PROGRAM = 1u,
    MR_TASK_FRAME_REFRESH_ARENA = 2u,
    MR_TASK_FRAME_REFRESH_PASS = 3u,
    MR_TASK_FRAME_REFRESH_RESET_MASKS = 4u,
    MR_TASK_FRAME_REFRESH_BODY_POSES = 5u,
    MR_TASK_FRAME_REFRESH_BODY_STATES = 6u,
    MR_TASK_FRAME_REFRESH_SCENE_BODIES = 7u,
    MR_TASK_FRAME_REFRESH_TASK_STATES = 8u,
    MR_TASK_FRAME_REFRESH_SENSOR_BIAS = 9u,
    MR_TASK_FRAME_REFRESH_ACTOR_HISTORY = 10u,
    MR_TASK_FRAME_REFRESH_CLEAN_HISTORY = 11u,
    MR_TASK_FRAME_REFRESH_CRITIC_HISTORY = 12u,
    MR_TASK_FRAME_REFRESH_ACTOR_OBSERVATIONS = 13u,
    MR_TASK_FRAME_REFRESH_CRITIC_OBSERVATIONS = 14u,
    MR_TASK_FRAME_REFRESH_BUFFER_COUNT = 15u,
};

enum MRSensorSampleBuffer : mr_u32 {
    MR_SENSOR_SAMPLE_DISPATCH = 0u,
    MR_SENSOR_SAMPLE_PROGRAM = 1u,
    MR_SENSOR_SAMPLE_DESCRIPTORS = 2u,
    MR_SENSOR_SAMPLE_FILTER_BODIES = 3u,
    MR_SENSOR_SAMPLE_PASS = 4u,
    MR_SENSOR_SAMPLE_RESET_MASKS = 5u,
    MR_SENSOR_SAMPLE_GENERALIZED_Q = 6u,
    MR_SENSOR_SAMPLE_GENERALIZED_V = 7u,
    MR_SENSOR_SAMPLE_BODY_POSES = 8u,
    MR_SENSOR_SAMPLE_BODY_STATES = 9u,
    MR_SENSOR_SAMPLE_SCENE_BODIES = 10u,
    MR_SENSOR_SAMPLE_CONTACT_DISPATCH = 11u,
    MR_SENSOR_SAMPLE_CONTACTS = 12u,
    MR_SENSOR_SAMPLE_CONTACT_STATUSES = 13u,
    MR_SENSOR_SAMPLE_WORLD_STATUSES = 14u,
    MR_SENSOR_SAMPLE_WORLD = 15u,
    MR_SENSOR_SAMPLE_STATES = 16u,
    MR_SENSOR_SAMPLE_HISTORY = 17u,
    MR_SENSOR_SAMPLE_OUTPUTS = 18u,
    MR_SENSOR_SAMPLE_METADATA = 19u,
    MR_SENSOR_SAMPLE_CHECKPOINT_STATES = 20u,
    MR_SENSOR_SAMPLE_CHECKPOINT_HISTORY = 21u,
    MR_SENSOR_SAMPLE_CHECKPOINT_OUTPUTS = 22u,
    MR_SENSOR_SAMPLE_CHECKPOINT_METADATA = 23u,
    MR_SENSOR_SAMPLE_ACTUATOR_STATES = 24u,
    MR_SENSOR_SAMPLE_BUFFER_COUNT = 25u,
};

enum MRTaskSensorRefreshBuffer : mr_u32 {
    MR_TASK_SENSOR_REFRESH_DISPATCH = 0u,
    MR_TASK_SENSOR_REFRESH_PROGRAM = 1u,
    MR_TASK_SENSOR_REFRESH_ARENA = 2u,
    MR_TASK_SENSOR_REFRESH_SENSOR_PROGRAM = 3u,
    MR_TASK_SENSOR_REFRESH_PASS = 4u,
    MR_TASK_SENSOR_REFRESH_RESET_MASKS = 5u,
    MR_TASK_SENSOR_REFRESH_TASK_STATES = 6u,
    MR_TASK_SENSOR_REFRESH_SENSOR_OUTPUTS = 7u,
    MR_TASK_SENSOR_REFRESH_SENSOR_METADATA = 8u,
    MR_TASK_SENSOR_REFRESH_SENSOR_BIAS = 9u,
    MR_TASK_SENSOR_REFRESH_ACTOR_HISTORY = 10u,
    MR_TASK_SENSOR_REFRESH_CLEAN_HISTORY = 11u,
    MR_TASK_SENSOR_REFRESH_CRITIC_HISTORY = 12u,
    MR_TASK_SENSOR_REFRESH_ACTOR_OBSERVATIONS = 13u,
    MR_TASK_SENSOR_REFRESH_CRITIC_OBSERVATIONS = 14u,
    MR_TASK_SENSOR_REFRESH_BUFFER_COUNT = 15u,
};

enum MRLearningPublicationValidationBuffer : mr_u32 {
    MR_LEARNING_VALIDATE_DISPATCH = 0u,
    MR_LEARNING_VALIDATE_ACTOR_OBSERVATIONS = 1u,
    MR_LEARNING_VALIDATE_CRITIC_OBSERVATIONS = 2u,
    MR_LEARNING_VALIDATE_LATENTS = 3u,
    MR_LEARNING_VALIDATE_LOG_PROBABILITIES = 4u,
    MR_LEARNING_VALIDATE_VALUES = 5u,
    MR_LEARNING_VALIDATE_TRANSITIONS = 6u,
    MR_LEARNING_VALIDATE_STATUS = 7u,
    MR_LEARNING_VALIDATE_BUFFER_COUNT = 8u,
};

enum MRWorldPrepareBuffer : mr_u32 {
    MR_WORLD_PREPARE_DISPATCH = 0u,
    MR_WORLD_PREPARE_PASS = 1u,
    MR_WORLD_PREPARE_EFFORT_TRAJECTORY = 2u,
    MR_WORLD_PREPARE_RESET_MASKS = 3u,
    MR_WORLD_PREPARE_RESET_Q = 4u,
    MR_WORLD_PREPARE_RESET_V = 5u,
    MR_WORLD_PREPARE_STATE_Q = 6u,
    MR_WORLD_PREPARE_STATE_V = 7u,
    MR_WORLD_PREPARE_CHECKPOINT_Q = 8u,
    MR_WORLD_PREPARE_CHECKPOINT_V = 9u,
    MR_WORLD_PREPARE_WORKING_EFFORT = 10u,
    MR_WORLD_PREPARE_STATUSES = 11u,
    MR_WORLD_PREPARE_WORLD = 12u,
    MR_WORLD_PREPARE_ARTICULATIONS = 13u,
    MR_WORLD_PREPARE_DOFS = 14u,
    MR_WORLD_PREPARE_ACTUATOR_PROFILES = 15u,
    MR_WORLD_PREPARE_TASK_CONTROLLER_PARAMETERS = 16u,
    MR_WORLD_PREPARE_ACTUATOR_STATES = 17u,
    MR_WORLD_PREPARE_ACTUATOR_COMMAND_HISTORY = 18u,
    MR_WORLD_PREPARE_CHECKPOINT_ACTUATOR_STATES = 19u,
    MR_WORLD_PREPARE_CHECKPOINT_ACTUATOR_COMMAND_HISTORY = 20u,
    MR_WORLD_PREPARE_BUFFER_COUNT = 21u,
};

enum MRWorldCommitBuffer : mr_u32 {
    MR_WORLD_COMMIT_DISPATCH = 0u,
    MR_WORLD_COMMIT_PASS = 1u,
    MR_WORLD_COMMIT_ABA_STATUSES = 2u,
    MR_WORLD_COMMIT_CANDIDATE_Q = 3u,
    MR_WORLD_COMMIT_CANDIDATE_V = 4u,
    MR_WORLD_COMMIT_DESTINATION_Q = 5u,
    MR_WORLD_COMMIT_DESTINATION_V = 6u,
    MR_WORLD_COMMIT_STATUSES = 7u,
    MR_WORLD_COMMIT_CHECKPOINT_Q = 8u,
    MR_WORLD_COMMIT_CHECKPOINT_V = 9u,
    MR_WORLD_COMMIT_WORLD = 10u,
    MR_WORLD_COMMIT_ACTUATOR_STATES = 11u,
    MR_WORLD_COMMIT_ACTUATOR_COMMAND_HISTORY = 12u,
    MR_WORLD_COMMIT_CHECKPOINT_ACTUATOR_STATES = 13u,
    MR_WORLD_COMMIT_CHECKPOINT_ACTUATOR_COMMAND_HISTORY = 14u,
    MR_WORLD_COMMIT_ACTUATOR_PROFILES = 15u,
    MR_WORLD_COMMIT_BUFFER_COUNT = 16u,
};

enum MRContactPrepareBuffer : mr_u32 {
    MR_CONTACT_PREPARE_WORLD_DISPATCH = 0u,
    MR_CONTACT_PREPARE_CONTACT_DISPATCH = 1u,
    MR_CONTACT_PREPARE_PASS = 2u,
    MR_CONTACT_PREPARE_RESET_MASKS = 3u,
    MR_CONTACT_PREPARE_RESET_SCENE_BODIES = 4u,
    MR_CONTACT_PREPARE_KINEMATIC_TARGETS = 5u,
    MR_CONTACT_PREPARE_BODY_PROPERTIES = 6u,
    MR_CONTACT_PREPARE_SCENE_BODY_INDICES = 7u,
    MR_CONTACT_PREPARE_SCENE_STATE = 8u,
    MR_CONTACT_PREPARE_CHECKPOINT_SCENE_STATE = 9u,
    MR_CONTACT_PREPARE_MANIFOLD_HEADERS = 10u,
    MR_CONTACT_PREPARE_MANIFOLD_POINTS = 11u,
    MR_CONTACT_PREPARE_MANIFOLD_COUNTS = 12u,
    MR_CONTACT_PREPARE_CHECKPOINT_HEADERS = 13u,
    MR_CONTACT_PREPARE_CHECKPOINT_POINTS = 14u,
    MR_CONTACT_PREPARE_CHECKPOINT_COUNTS = 15u,
    MR_CONTACT_PREPARE_STATUSES = 16u,
    MR_CONTACT_PREPARE_CONVEX_CACHES = 17u,
    MR_CONTACT_PREPARE_GENERALIZED_WARM_STATE = 18u,
    MR_CONTACT_PREPARE_CHECKPOINT_GENERALIZED_WARM_STATE = 19u,
    MR_CONTACT_PREPARE_CHECKPOINT_CONVEX_CACHES = 20u,
    MR_CONTACT_PREPARE_BUFFER_COUNT = 21u,
};

enum MRConvexCachePublishBuffer : mr_u32 {
    MR_CONVEX_CACHE_PUBLISH_DISPATCH = 0u,
    MR_CONVEX_CACHE_PUBLISH_ELIGIBLE_PAIRS = 1u,
    MR_CONVEX_CACHE_PUBLISH_OVERLAP_FLAGS = 2u,
    MR_CONVEX_CACHE_PUBLISH_STATUSES = 3u,
    MR_CONVEX_CACHE_PUBLISH_CANDIDATE_CACHES = 4u,
    MR_CONVEX_CACHE_PUBLISH_PUBLISHED_CACHES = 5u,
    MR_CONVEX_CACHE_PUBLISH_WORLD_DISPATCH = 6u,
    MR_CONVEX_CACHE_PUBLISH_PASS = 7u,
    MR_CONVEX_CACHE_PUBLISH_RESET_MASKS = 8u,
    MR_CONVEX_CACHE_PUBLISH_CHECKPOINT_CACHES = 9u,
    MR_CONVEX_CACHE_PUBLISH_WORLD_STATUSES = 10u,
    MR_CONVEX_CACHE_PUBLISH_BUFFER_COUNT = 11u,
};

enum MRTaskTransactionBuffer : mr_u32 {
    MR_TASK_TRANSACTION_DISPATCH = 0u,
    MR_TASK_TRANSACTION_PROGRAM = 1u,
    MR_TASK_TRANSACTION_PASS = 2u,
    MR_TASK_TRANSACTION_RESET_MASKS = 3u,
    MR_TASK_TRANSACTION_WORLD_STATUSES = 4u,
    MR_TASK_TRANSACTION_CONTACT_STATUSES = 5u,
    MR_TASK_TRANSACTION_STATE = 6u,
    MR_TASK_TRANSACTION_ACTION_HISTORY = 7u,
    MR_TASK_TRANSACTION_ACTOR_HISTORY = 8u,
    MR_TASK_TRANSACTION_CLEAN_HISTORY = 9u,
    MR_TASK_TRANSACTION_CRITIC_HISTORY = 10u,
    MR_TASK_TRANSACTION_PREVIOUS_JOINT_VELOCITY = 11u,
    MR_TASK_TRANSACTION_ENCODER_BIAS = 12u,
    MR_TASK_TRANSACTION_BODY_PARAMETERS = 13u,
    MR_TASK_TRANSACTION_CONTROLLER_PARAMETERS = 14u,
    MR_TASK_TRANSACTION_CONTACT_COMPACT = 15u,
    MR_TASK_TRANSACTION_CHECKPOINT_STATE = 16u,
    MR_TASK_TRANSACTION_CHECKPOINT_ACTION_HISTORY = 17u,
    MR_TASK_TRANSACTION_CHECKPOINT_ACTOR_HISTORY = 18u,
    MR_TASK_TRANSACTION_CHECKPOINT_CLEAN_HISTORY = 19u,
    MR_TASK_TRANSACTION_CHECKPOINT_CRITIC_HISTORY = 20u,
    MR_TASK_TRANSACTION_CHECKPOINT_PREVIOUS_JOINT_VELOCITY = 21u,
    MR_TASK_TRANSACTION_CHECKPOINT_ENCODER_BIAS = 22u,
    MR_TASK_TRANSACTION_CHECKPOINT_BODY_PARAMETERS = 23u,
    MR_TASK_TRANSACTION_CHECKPOINT_CONTROLLER_PARAMETERS = 24u,
    MR_TASK_TRANSACTION_CHECKPOINT_CONTACT_COMPACT = 25u,
    MR_TASK_TRANSACTION_BUFFER_COUNT = 26u,
};

enum MRTaskPhysicalCheckpointBuffer : mr_u32 {
    MR_TASK_PHYSICAL_CHECKPOINT_WORLD_DISPATCH = 0u,
    MR_TASK_PHYSICAL_CHECKPOINT_CONTACT_DISPATCH = 1u,
    MR_TASK_PHYSICAL_CHECKPOINT_PASS = 2u,
    MR_TASK_PHYSICAL_CHECKPOINT_STATE_Q = 3u,
    MR_TASK_PHYSICAL_CHECKPOINT_STATE_V = 4u,
    MR_TASK_PHYSICAL_CHECKPOINT_SCENE_STATE = 5u,
    MR_TASK_PHYSICAL_CHECKPOINT_CHECKPOINT_Q = 6u,
    MR_TASK_PHYSICAL_CHECKPOINT_CHECKPOINT_V = 7u,
    MR_TASK_PHYSICAL_CHECKPOINT_CHECKPOINT_SCENE_STATE = 8u,
    MR_TASK_PHYSICAL_CHECKPOINT_BUFFER_COUNT = 9u,
};

#if defined(__cplusplus) && !defined(__METAL_VERSION__)
#include <array>
#include <cstddef>
#include <cstdint>

namespace metalrobo::runtime_abi {

enum BufferIndex : std::size_t {
    kWorld = 0u,
    kArticulations = 1u,
    kJoints = 2u,
    kDofs = 3u,
    kBodies = 4u,
    kABADispatch = 5u,
    kStateQA = 6u,
    kStateVA = 7u,
    kWorkingEffort = 8u,
    kBodyWrenchPlaceholder = 9u,
    kCandidateAcceleration = 10u,
    kCandidateV = 11u,
    kCandidateQ = 12u,
    kABAStatuses = 13u,
    kStateQB = 14u,
    kStateVB = 15u,
    kEffortTrajectory = 16u,
    kResetMasks = 17u,
    kResetQ = 18u,
    kResetV = 19u,
    kObservations = 20u,
    kAccelerationTrajectory = 21u,
    kPublicStatuses = 22u,
    kWorldDispatch = 23u,
    kEnvironmentStatuses = 24u,
    kCheckpointQ = 25u,
    kCheckpointV = 26u,
    kShapes = 27u,
    kMaterials = 28u,
    kSceneBodyIndices = 29u,
    kEligiblePairs = 30u,
    kContactDispatch = 31u,
    kOperatorKinematicsDispatch = 32u,
    kOperatorFactorDispatch = 33u,
    kInitialSceneBodies = 34u,
    kResetSceneBodies = 35u,
    kKinematicTargets = 36u,
    kSceneBodiesA = 37u,
    kSceneBodiesB = 38u,
    kCheckpointSceneBodies = 39u,
    kBodyPoses = 40u,
    kPointWorld = 41u,
    kFactorMatrix = 42u,
    kPointJacobians = 43u,
    kGeneralizedImpulse = 44u,
    kDeltaVelocity = 45u,
    kOperatorStatuses = 46u,
    kCurrentBodies = 47u,
    kCandidateBodies = 48u,
    kManifoldHeadersA = 49u,
    kManifoldPointsA = 50u,
    kManifoldCountsA = 51u,
    kManifoldHeadersB = 52u,
    kManifoldPointsB = 53u,
    kManifoldCountsB = 54u,
    kCandidateManifoldHeaders = 55u,
    kCandidateManifoldPoints = 56u,
    kCandidateManifoldCounts = 57u,
    kCheckpointManifoldHeaders = 58u,
    kCheckpointManifoldPoints = 59u,
    kCheckpointManifoldCounts = 60u,
    kCandidatePairs = 61u,
    kRawContacts = 62u,
    kRawPairIndices = 63u,
    kContacts = 64u,
    kContactMetadata = 65u,
    kIRBlocks = 66u,
    kIREndpoints = 67u,
    kIRRows = 68u,
    kIRCones = 69u,
    kPointQueries = 70u,
    kEvaluatedRows = 71u,
    kEvaluatedCones = 72u,
    kFactorCaches = 73u,
    kIslands = 74u,
    kResponseColumns = 75u,
    kContactStatuses = 76u,
    kPublicContactStatuses = 77u,
    kActiveIndirectDispatch = 78u,
    kProjectedColliders = 79u,
    kPairOverlapFlags = 80u,
    kWorkQueueHeaders = 81u,
    kPairWorkQueue = 82u,
    kPairRawCounts = 83u,
    kCompactionOffsets = 84u,
    kCompactionScratch = 85u,
    kCompactionFlags = 86u,
    kConvexCaches = 92u,
    kCCDPairs = 93u,
    kGeometryHeaders = 94u,
    kGeometryVertices = 95u,
    kGeometryIndices = 96u,
    kConvexFaces = 97u,
    kConvexHalfEdges = 98u,
    kMeshBvhNodes = 99u,
    kMeshTriangles = 100u,
    kPairRawContactStaging = 101u,
    kFutureBodyPoses = 104u,
    kFutureProjectedColliders = 105u,
    kCandidateConvexCaches = 106u,
    kCCDEventStatesA = 107u,
    kCCDEventStatesB = 108u,
    kCCDImpactClusters = 109u,
    kPairManifoldHeaders = 111u,
    kPairManifoldPoints = 112u,
    kManifoldIRScatter = 113u,
    kEndpointRuntime = 114u,
    kQualityDispatch = 115u,
    kQualityBlocks = 116u,
    kQualityDynamics = 117u,
    kQualityJacobian = 118u,
    kQualityBias = 119u,
    kQualityFreeVelocity = 120u,
    kQualityWarmVelocity = 121u,
    kQualityWarmImpulses = 122u,
    kQualityOutputVelocity = 123u,
    kQualityOutputImpulses = 124u,
    kQualityDerivatives = 125u,
    kQualityHessian = 126u,
    kQualityStatuses = 127u,
    kQualityWorkQueue = 128u,
    kQualityWorkPackets = 129u,
    kDynamicNodes = 130u,
    kBodyDynamicNodes = 131u,
    kIslandNodeReferences = 132u,
    kIslandConstraintReferences = 133u,
    kRodFactorCaches = 134u,
    kOperatorVelocityArena = 135u,
    kInitialRodNodes = 136u,
    kInitialRodEdges = 137u,
    kResetRodNodes = 138u,
    kResetRodEdges = 139u,
    kRodNodesA = 140u,
    kRodEdgesA = 141u,
    kRodNodesB = 142u,
    kRodEdgesB = 143u,
    kCheckpointRodNodes = 144u,
    kCheckpointRodEdges = 145u,
    kRodDispatches = 146u,
    kRodRestLengths = 147u,
    kRodRestTwists = 148u,
    kRodRestCurvatures = 149u,
    kRodInverseMasses = 150u,
    kRodInverseRotationalInertias = 151u,
    kRodStretchStiffness = 152u,
    kRodBendStiffness = 153u,
    kRodTwistStiffness = 154u,
    kRodInputPositions = 155u,
    kRodInputVelocities = 156u,
    kRodInputTwists = 157u,
    kRodInputTwistRates = 158u,
    kRodOutputPositions = 159u,
    kRodOutputVelocities = 160u,
    kRodOutputTwists = 161u,
    kRodOutputTwistRates = 162u,
    kRodStatuses = 163u,
    kRodAttachments = 164u,
    kRodReactions = 165u,
    kFactorMatrixStaging = 166u,
    kPointJacobiansStaging = 167u,
    kRodColliders = 168u,
    kRodShapeSources = 169u,
    kRodToolPairs = 170u,
    kRodWitnessCounts = 171u,
    kRodWitnessesA = 172u,
    kRodWitnessesB = 173u,
    kCandidateRodWitnesses = 174u,
    kCheckpointRodWitnesses = 175u,
    kRodConstraintWitnessIndices = 176u,
    kRodCollisionDispatches = 177u,
    kRodContactScratch = 178u,
    kAuthoredIRBlocks = 179u,
    kAuthoredIREndpoints = 180u,
    kAuthoredIRRows = 181u,
    kAuthoredIRCones = 182u,
    kAuthoredIRWarmImpulses = 183u,
    kCCDEventRodNodesA = 184u,
    kCCDEventRodEdgesA = 185u,
    kCCDEventRodWitnessesA = 186u,
    kCCDEventRodNodesB = 187u,
    kCCDEventRodEdgesB = 188u,
    kCCDEventRodWitnessesB = 189u,
    kProjectedRodColliders = 190u,
    kFutureProjectedRodColliders = 191u,
    kActuatorProfiles = 192u,
    kTaskDispatch = 193u,
    kTaskActions = 194u,
    kTaskState = 195u,
    kTaskActionHistory = 196u,
    kTaskActorHistory = 197u,
    kTaskCleanHistory = 198u,
    kTaskCriticHistory = 199u,
    kTaskPreviousJointVelocity = 200u,
    kTaskEncoderBias = 201u,
    kTaskBodyParameters = 202u,
    kTaskControllerParameters = 203u,
    kTaskActorObservations = 204u,
    kTaskCriticObservations = 205u,
    kTaskTransitions = 206u,
    kTaskContactCompact = 207u,
    kTaskDefaultQ = 208u,
    kTaskProgramHeader = 209u,
    kTaskProgramArena = 210u,
    kPolicyProgramHeaderA = 211u,
    kPolicyProgramArenaA = 212u,
    kPolicyScratchA = 213u,
    kPolicyScratchB = 214u,
    kPolicyActorMean = 215u,
    kPolicyLatents = 216u,
    kPolicyLogProbabilities = 217u,
    kPolicyValues = 218u,
    kTaskCurriculumState = 219u,
    kGeneralizedWarmState = 220u,
    kCheckpointGeneralizedWarmState = 221u,
    kSensorProgramHeader = 222u,
    kSensorDescriptors = 223u,
    kSensorRuntimeStates = 224u,
    kSensorHistory = 225u,
    kSensorOutputs = 226u,
    kSensorMetadata = 227u,
    kPolicyProgramHeaderB = 228u,
    kPolicyProgramArenaB = 229u,
    kLearningPublicationStatus = 230u,
    kSensorCheckpointStates = 231u,
    kSensorCheckpointHistory = 232u,
    kSensorCheckpointOutputs = 233u,
    kSensorCheckpointMetadata = 234u,
    kCheckpointConvexCaches = 235u,
    kTaskCheckpointState = 236u,
    kTaskCheckpointActionHistory = 237u,
    kTaskCheckpointActorHistory = 238u,
    kTaskCheckpointCleanHistory = 239u,
    kTaskCheckpointCriticHistory = 240u,
    kTaskCheckpointPreviousJointVelocity = 241u,
    kTaskCheckpointEncoderBias = 242u,
    kTaskCheckpointBodyParameters = 243u,
    kTaskCheckpointControllerParameters = 244u,
    kTaskCheckpointContactCompact = 245u,
    kSensorFilterBodies = 246u,
    kActuatorRuntimeStates = 247u,
    kActuatorCommandHistory = 248u,
    kCheckpointActuatorRuntimeStates = 249u,
    kCheckpointActuatorCommandHistory = 250u,
    kTaskKinematicDispatches = 251u,
    kTaskKinematicQueries = 252u,
    kTaskKinematicPointWorld = 253u,
    kRawBufferCount = 254u,
};

enum class BufferLifetime : std::uint8_t {
    boundary = 0u,
    immutable = 1u,
    persistent = 2u,
    transient = 3u,
    unused = 4u,
};

inline constexpr std::array<BufferLifetime, kRawBufferCount>
    kBufferLifetimes{{
        BufferLifetime::boundary,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::boundary,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::persistent,
        BufferLifetime::boundary,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::boundary,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::boundary,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::unused,
        BufferLifetime::unused,
        BufferLifetime::unused,
        BufferLifetime::unused,
        BufferLifetime::unused,
        BufferLifetime::persistent,
        BufferLifetime::transient,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::transient,
        BufferLifetime::unused,
        BufferLifetime::unused,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::unused,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::boundary,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::boundary,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::boundary,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::transient,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::boundary,
        BufferLifetime::transient,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::immutable,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::persistent,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::boundary,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::transient,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::immutable,
        BufferLifetime::immutable,
        BufferLifetime::boundary,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::immutable,
        BufferLifetime::persistent,
        BufferLifetime::persistent,
        BufferLifetime::transient,
        BufferLifetime::transient,
        BufferLifetime::boundary,
        BufferLifetime::immutable,
        BufferLifetime::transient,
    }};
inline constexpr std::array<bool, kRawBufferCount>
    kPersistentInputs{{
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
    }};
inline constexpr std::array<const char*, kRawBufferCount>
    kBufferDebugNames{{
        "world",
        "articulations",
        "joints",
        "dofs",
        "bodies",
        "aba dispatch",
        "state qa",
        "state va",
        "working effort",
        "body wrench placeholder",
        "candidate acceleration",
        "candidate v",
        "candidate q",
        "aba statuses",
        "state qb",
        "state vb",
        "effort trajectory",
        "reset masks",
        "reset q",
        "reset v",
        "observations",
        "acceleration trajectory",
        "public statuses",
        "world dispatch",
        "environment statuses",
        "checkpoint q",
        "checkpoint v",
        "shapes",
        "materials",
        "scene body indices",
        "eligible pairs",
        "contact dispatch",
        "operator kinematics dispatch",
        "operator factor dispatch",
        "initial scene bodies",
        "reset scene bodies",
        "kinematic targets",
        "scene bodies a",
        "scene bodies b",
        "checkpoint scene bodies",
        "body poses",
        "point world",
        "factor matrix",
        "point jacobians",
        "generalized impulse",
        "delta velocity",
        "operator statuses",
        "current bodies",
        "candidate bodies",
        "manifold headers a",
        "manifold points a",
        "manifold counts a",
        "manifold headers b",
        "manifold points b",
        "manifold counts b",
        "candidate manifold headers",
        "candidate manifold points",
        "candidate manifold counts",
        "checkpoint manifold headers",
        "checkpoint manifold points",
        "checkpoint manifold counts",
        "candidate pairs",
        "raw contacts",
        "raw pair indices",
        "contacts",
        "contact metadata",
        "ir blocks",
        "ir endpoints",
        "ir rows",
        "ir cones",
        "point queries",
        "evaluated rows",
        "evaluated cones",
        "factor caches",
        "islands",
        "response columns",
        "contact statuses",
        "public contact statuses",
        "active indirect dispatch",
        "projected colliders",
        "pair overlap flags",
        "work queue headers",
        "pair work queue",
        "pair raw counts",
        "compaction offsets",
        "compaction scratch",
        "compaction flags",
        "reserved 87",
        "reserved 88",
        "reserved 89",
        "reserved 90",
        "reserved 91",
        "convex caches",
        "ccd pairs",
        "geometry headers",
        "geometry vertices",
        "geometry indices",
        "convex faces",
        "convex half edges",
        "mesh bvh nodes",
        "mesh triangles",
        "pair raw contact staging",
        "reserved 102",
        "reserved 103",
        "future body poses",
        "future projected colliders",
        "candidate convex caches",
        "ccd event states a",
        "ccd event states b",
        "ccd impact clusters",
        "reserved 110",
        "pair manifold headers",
        "pair manifold points",
        "manifold ir scatter",
        "endpoint runtime",
        "quality dispatch",
        "quality blocks",
        "quality dynamics",
        "quality jacobian",
        "quality bias",
        "quality free velocity",
        "quality warm velocity",
        "quality warm impulses",
        "quality output velocity",
        "quality output impulses",
        "quality derivatives",
        "quality hessian",
        "quality statuses",
        "quality work queue",
        "quality work packets",
        "dynamic nodes",
        "body dynamic nodes",
        "island node references",
        "island constraint references",
        "rod factor caches",
        "operator velocity arena",
        "initial rod nodes",
        "initial rod edges",
        "reset rod nodes",
        "reset rod edges",
        "rod nodes a",
        "rod edges a",
        "rod nodes b",
        "rod edges b",
        "checkpoint rod nodes",
        "checkpoint rod edges",
        "rod dispatches",
        "rod rest lengths",
        "rod rest twists",
        "rod rest curvatures",
        "rod inverse masses",
        "rod inverse rotational inertias",
        "rod stretch stiffness",
        "rod bend stiffness",
        "rod twist stiffness",
        "rod input positions",
        "rod input velocities",
        "rod input twists",
        "rod input twist rates",
        "rod output positions",
        "rod output velocities",
        "rod output twists",
        "rod output twist rates",
        "rod statuses",
        "rod attachments",
        "rod reactions",
        "factor matrix staging",
        "point jacobians staging",
        "rod colliders",
        "rod shape sources",
        "rod tool pairs",
        "rod witness counts",
        "rod witnesses a",
        "rod witnesses b",
        "candidate rod witnesses",
        "checkpoint rod witnesses",
        "rod constraint witness indices",
        "rod collision dispatches",
        "rod contact scratch",
        "authored ir blocks",
        "authored ir endpoints",
        "authored ir rows",
        "authored ir cones",
        "authored ir warm impulses",
        "ccd event rod nodes a",
        "ccd event rod edges a",
        "ccd event rod witnesses a",
        "ccd event rod nodes b",
        "ccd event rod edges b",
        "ccd event rod witnesses b",
        "projected rod colliders",
        "future projected rod colliders",
        "actuator profiles",
        "task dispatch",
        "task actions",
        "task state",
        "task action history",
        "task actor history",
        "task clean history",
        "task critic history",
        "task previous joint velocity",
        "task encoder bias",
        "task body parameters",
        "task controller parameters",
        "task actor observations",
        "task critic observations",
        "task transitions",
        "task contact compact",
        "task default q",
        "task program header",
        "task program arena",
        "policy program header a",
        "policy program arena a",
        "policy scratch a",
        "policy scratch b",
        "policy actor mean",
        "policy latents",
        "policy log probabilities",
        "policy values",
        "task curriculum state",
        "generalized warm state",
        "checkpoint generalized warm state",
        "sensor program header",
        "sensor descriptors",
        "sensor runtime states",
        "sensor history",
        "sensor outputs",
        "sensor metadata",
        "policy program header b",
        "policy program arena b",
        "learning publication status",
        "sensor checkpoint states",
        "sensor checkpoint history",
        "sensor checkpoint outputs",
        "sensor checkpoint metadata",
        "checkpoint convex caches",
        "task checkpoint state",
        "task checkpoint action history",
        "task checkpoint actor history",
        "task checkpoint clean history",
        "task checkpoint critic history",
        "task checkpoint previous joint velocity",
        "task checkpoint encoder bias",
        "task checkpoint body parameters",
        "task checkpoint controller parameters",
        "task checkpoint contact compact",
        "sensor filter bodies",
        "actuator runtime states",
        "actuator command history",
        "checkpoint actuator runtime states",
        "checkpoint actuator command history",
        "task kinematic dispatches",
        "task kinematic queries",
        "task kinematic point world",
    }};

[[nodiscard]] constexpr bool validBufferIndex(
    const std::size_t index
) noexcept {
    return index < kRawBufferCount &&
        kBufferLifetimes[index] != BufferLifetime::unused;
}

[[nodiscard]] constexpr bool isImmutable(
    const std::size_t index
) noexcept {
    return index < kRawBufferCount &&
        kBufferLifetimes[index] == BufferLifetime::immutable;
}

[[nodiscard]] constexpr bool isPersistent(
    const std::size_t index
) noexcept {
    return index < kRawBufferCount &&
        kBufferLifetimes[index] == BufferLifetime::persistent;
}

[[nodiscard]] constexpr bool isPersistentInput(
    const std::size_t index
) noexcept {
    return index < kRawBufferCount && kPersistentInputs[index];
}

[[nodiscard]] constexpr bool isTransient(
    const std::size_t index
) noexcept {
    return index < kRawBufferCount &&
        kBufferLifetimes[index] == BufferLifetime::transient;
}

static_assert(kBufferLifetimes.size() == kRawBufferCount);
static_assert(kPersistentInputs.size() == kRawBufferCount);
static_assert(kBufferDebugNames.size() == kRawBufferCount);
static_assert(sizeof(MRSensorProgramHeaderGPU) == 80u);
static_assert(alignof(MRSensorProgramHeaderGPU) == 16u);
static_assert(offsetof(MRSensorProgramHeaderGPU, sensorFingerprint) == 0u);
static_assert(offsetof(MRSensorProgramHeaderGPU, worldFingerprint) == 8u);
static_assert(offsetof(MRSensorProgramHeaderGPU, counts) == 16u);
static_assert(offsetof(MRSensorProgramHeaderGPU, executionCounts) == 32u);
static_assert(offsetof(MRSensorProgramHeaderGPU, layout) == 48u);
static_assert(offsetof(MRSensorProgramHeaderGPU, reserved) == 64u);
static_assert(sizeof(MRSensorDescriptorGPU) == 224u);
static_assert(alignof(MRSensorDescriptorGPU) == 16u);
static_assert(offsetof(MRSensorDescriptorGPU, identity) == 0u);
static_assert(offsetof(MRSensorDescriptorGPU, output) == 16u);
static_assert(offsetof(MRSensorDescriptorGPU, schedule) == 32u);
static_assert(offsetof(MRSensorDescriptorGPU, dimensions) == 48u);
static_assert(offsetof(MRSensorDescriptorGPU, source) == 64u);
static_assert(offsetof(MRSensorDescriptorGPU, filter) == 80u);
static_assert(offsetof(MRSensorDescriptorGPU, randomIdentity) == 96u);
static_assert(offsetof(MRSensorDescriptorGPU, localPosition) == 112u);
static_assert(offsetof(MRSensorDescriptorGPU, localOrientation) == 128u);
static_assert(offsetof(MRSensorDescriptorGPU, timing) == 144u);
static_assert(offsetof(MRSensorDescriptorGPU, noise) == 160u);
static_assert(offsetof(MRSensorDescriptorGPU, range) == 176u);
static_assert(offsetof(MRSensorDescriptorGPU, intrinsics) == 192u);
static_assert(offsetof(MRSensorDescriptorGPU, distortion) == 208u);
static_assert(sizeof(MRSensorDispatchGPU) == 48u);
static_assert(alignof(MRSensorDispatchGPU) == 16u);
static_assert(offsetof(MRSensorDispatchGPU, counts) == 0u);
static_assert(offsetof(MRSensorDispatchGPU, controlPeriodAndStrides) == 16u);
static_assert(offsetof(MRSensorDispatchGPU, seed) == 32u);
static_assert(offsetof(MRSensorDispatchGPU, sensorFingerprint) == 40u);
static_assert(sizeof(MRSensorRuntimeStateGPU) == 80u);
static_assert(alignof(MRSensorRuntimeStateGPU) == 16u);
static_assert(offsetof(MRSensorRuntimeStateGPU, phaseAndSequence) == 0u);
static_assert(offsetof(MRSensorRuntimeStateGPU, timestampAgeValidity) == 16u);
static_assert(offsetof(MRSensorRuntimeStateGPU, previousSampleTimestamp) == 32u);
static_assert(offsetof(MRSensorRuntimeStateGPU, randomIdentity) == 48u);
static_assert(offsetof(MRSensorRuntimeStateGPU, previousPointVelocity) == 64u);
static_assert(sizeof(MRSensorSampleMetadataGPU) == 32u);
static_assert(alignof(MRSensorSampleMetadataGPU) == 16u);
static_assert(offsetof(MRSensorSampleMetadataGPU, sequenceAndTimestamp) == 0u);
static_assert(offsetof(MRSensorSampleMetadataGPU, ageValidityAndLayout) == 16u);
static_assert(sizeof(MRActuatorRuntimeStateGPU) == 64u);
static_assert(alignof(MRActuatorRuntimeStateGPU) == 16u);
static_assert(offsetof(MRActuatorRuntimeStateGPU, command) == 0u);
static_assert(offsetof(MRActuatorRuntimeStateGPU, effort) == 16u);
static_assert(offsetof(MRActuatorRuntimeStateGPU, envelope) == 32u);
static_assert(offsetof(MRActuatorRuntimeStateGPU, status) == 48u);
static_assert(sizeof(MRTaskKinematicFrameGPU) == 32u);
static_assert(alignof(MRTaskKinematicFrameGPU) == 16u);
static_assert(offsetof(MRTaskKinematicFrameGPU, layout) == 0u);
static_assert(offsetof(MRTaskKinematicFrameGPU, coordinates) == 16u);
static_assert(sizeof(MRLearningPublicationDispatchGPU) == 64u);
static_assert(alignof(MRLearningPublicationDispatchGPU) == 16u);
static_assert(offsetof(MRLearningPublicationDispatchGPU, floatCounts) == 0u);
static_assert(offsetof(MRLearningPublicationDispatchGPU, recordCounts) == 16u);
static_assert(offsetof(MRLearningPublicationDispatchGPU, policyRevision) == 32u);
static_assert(offsetof(MRLearningPublicationDispatchGPU, taskFingerprint) == 40u);
static_assert(offsetof(MRLearningPublicationDispatchGPU, validationToken) == 48u);
static_assert(offsetof(MRLearningPublicationDispatchGPU, reserved) == 56u);
static_assert(sizeof(MRLearningPublicationStatusGPU) == 64u);
static_assert(alignof(MRLearningPublicationStatusGPU) == 16u);
static_assert(offsetof(MRLearningPublicationStatusGPU, result) == 0u);
static_assert(offsetof(MRLearningPublicationStatusGPU, checkedCounts) == 16u);
static_assert(offsetof(MRLearningPublicationStatusGPU, policyRevision) == 32u);
static_assert(offsetof(MRLearningPublicationStatusGPU, taskFingerprint) == 40u);
static_assert(offsetof(MRLearningPublicationStatusGPU, validationToken) == 48u);
static_assert(offsetof(MRLearningPublicationStatusGPU, reserved) == 56u);
static_assert(MR_RECORD_SCATTER_BUFFER_COUNT <= 31u);
static_assert(MR_IR_SCATTER_BUFFER_COUNT <= 31u);
static_assert(MR_NUMI_PREPARE_BUFFER_COUNT <= 31u);
static_assert(MR_TASK_FRAME_REFRESH_BUFFER_COUNT <= 31u);
static_assert(MR_SENSOR_SAMPLE_BUFFER_COUNT <= 31u);
static_assert(MR_TASK_SENSOR_REFRESH_BUFFER_COUNT <= 31u);
static_assert(MR_LEARNING_VALIDATE_BUFFER_COUNT <= 31u);
static_assert(MR_WORLD_PREPARE_BUFFER_COUNT <= 31u);
static_assert(MR_WORLD_COMMIT_BUFFER_COUNT <= 31u);
static_assert(MR_CONTACT_PREPARE_BUFFER_COUNT <= 31u);
static_assert(MR_CONVEX_CACHE_PUBLISH_BUFFER_COUNT <= 31u);
static_assert(MR_TASK_TRANSACTION_BUFFER_COUNT <= 31u);
static_assert(MR_TASK_PHYSICAL_CHECKPOINT_BUFFER_COUNT <= 31u);

} // namespace metalrobo::runtime_abi
#endif
