// Synthetic native measurement/publication controls only; no physical stepping.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include <CommonCrypto/CommonDigest.h>
#include "metalrobo/MetalHumanBehaviorTelemetry.hpp"
#include "metalrobo/compensated_translation_gpu.h"
#include <cmath>
#include <cstdio>
#include <cstring>
#include <stdexcept>
using namespace metalrobo;
namespace {
void need(bool value,const char* why){if(!value)throw std::runtime_error(why);}
std::uint64_t hashFence(const MRNumanXHumanMatterJointPublicationFenceGPU& f){
    const auto* p=reinterpret_cast<const std::uint8_t*>(&f);std::uint64_t h=14695981039346656037ull;
    for(unsigned i=0;i<120;++i){h^=p[i];h*=1099511628211ull;}return h;
}
std::uint64_t hashTraceRecord(const mrnx_behavior_trace_record_v1& r){
    const auto* p=reinterpret_cast<const std::uint8_t*>(&r);std::uint64_t h=14695981039346656037ull;
    for(std::size_t i=0;i<offsetof(mrnx_behavior_trace_record_v1,record_fingerprint);++i){h^=p[i];h*=1099511628211ull;}return h;
}
std::array<std::uint8_t,32> hashStateComponentRecord(
    const mrnx_behavior_trace_state_component_record_v1& r){
    std::array<std::uint8_t,32> result{};
    need(CC_SHA256(&r,static_cast<CC_LONG>(offsetof(
        mrnx_behavior_trace_state_component_record_v1,record_sha256)),result.data())!=nullptr,
        "state-component test SHA256 failed");
    return result;
}
void fillDigest(std::uint8_t* digest,std::uint8_t value){std::memset(digest,value,32);}
CompiledHumanBehaviorProgram program(){HumanBehaviorProgramSource s;s.bodyCount=1;s.nq=7;s.nv=6;s.task=2;s.timestepNanoseconds=kNumiHumanBehaviorTimestepNanoseconds;
    for(auto& h:s.sourceSHA256)h.fill(1);s.numerical={0,0,0,0,0,1,1,0,0,0,0,1,1.0+std::ldexp(1.0,-24),.3,1,.5};
    s.forbiddenBodies={{{0,0}}};HumanBehaviorCompileBinding b;b.bodyCount=1;b.nq=7;b.nv=6;b.timestepNanoseconds=kNumiHumanBehaviorTimestepNanoseconds;
    b.sourceArchiveSHA256=s.sourceSHA256[0];b.rigidSHA256=s.sourceSHA256[1];b.sourceToCore={{{0,0}}};b.cookedCOMOffset={{{0,0,0}}};
    CompiledHumanBehaviorProgram out;std::string error;need(compileHumanBehaviorProgram(s,b,out,error),error.c_str());return out;
}
struct Driver {
    id<MTLDevice> device=MTLCreateSystemDefaultDevice();id<MTLCommandQueue> queue;
    id<MTLBuffer> bodies,low,jacobian,velocity;std::string path,error;CompiledHumanBehaviorProgram cooked=program();
    Driver(const char* p):queue([device newCommandQueue]),path(p){need(device!=nil&&queue!=nil,"physical Metal device unavailable");
        auto buffer=[&](NSUInteger size){id<MTLBuffer> b=[device newBufferWithLength:size options:MTLResourceStorageModeShared];need(b!=nil,"test buffer allocation");std::memset(b.contents,0,size);return b;};
        bodies=buffer(sizeof(MRArticulatedBodyPoseGPU));low=buffer(sizeof(mr_float4));jacobian=buffer(72*sizeof(float));velocity=buffer(6*sizeof(float));
        auto* pose=static_cast<MRArticulatedBodyPoseGPU*>(bodies.contents);pose->orientation={0,0,0,1};
        auto* j=static_cast<float*>(jacobian.contents);j[0]=j[7]=j[14]=1;static_cast<float*>(velocity.contents)[0]=.75f;
    }
    MetalHumanBehaviorTelemetry telemetry(std::uint64_t timestamp=100000){return MetalHumanBehaviorTelemetry((__bridge void*)device,cooked,path,1,4,timestamp);}
    void command(const auto& encode){id<MTLCommandBuffer> cb=[queue commandBuffer];need(cb!=nil,"test command allocation");need(encode((__bridge void*)cb),error.c_str());[cb commit];[cb waitUntilCompleted];need(cb.status==MTLCommandBufferStatusCompleted,"test Metal command failure");}
    void initial(MetalHumanBehaviorTelemetry& t){command([&](void* cb){MRCompensatedRootTranslationGPU root{};root.reference={0,0,1,0};root.displacement={0,0,std::ldexp(1.0f,-24),0};root.correction={0,0,0,0};const auto position=mrCompensatedTranslationPosition(root,{0,0,0,0});static_cast<MRArticulatedBodyPoseGPU*>(bodies.contents)->position=position.high;*static_cast<mr_float4*>(low.contents)=position.low;MetalNumanXHumanMatterPass p{};p.phase=MetalNumanXHumanMatterPhase::preDynamics;p.commandBuffer=cb;p.environmentCount=1;p.physicsSubstepCount=1;p.bodyPoses=(__bridge void*)bodies;p.bodyPositionLow=(__bridge void*)low;p.pointJacobians=(__bridge void*)jacobian;p.v=(__bridge void*)velocity;p.bodyPoseStride=1;p.bodyCount=1;p.qCoordinateCount=7;p.dofCount=6;p.vStride=6;p.pointWorldStride=4;p.pointJacobianStride=72;p.transactionFingerprint=99;p.linearizationEpoch=19;p.slotGeneration=1;return t.encodeInitial(p,error);});}
    void flush(MetalHumanBehaviorTelemetry& t){command([&](void* cb){return t.encodeFlush(cb,error);});}
    void measure(MetalHumanBehaviorTelemetry& t,std::uint64_t serial,float correction,std::uint64_t acceptedOrdinal=0){
        if(acceptedOrdinal==0)acceptedOrdinal=serial;
        MRCompensatedRootTranslationGPU root{};root.reference={0,0,1,0};root.displacement={0,0,std::ldexp(1.0f,-24),0};root.correction={0,0,correction,0};
        const auto position=mrCompensatedTranslationPosition(root,{0,0,0,0});
        static_cast<MRArticulatedBodyPoseGPU*>(bodies.contents)->position=position.high;*static_cast<mr_float4*>(low.contents)=position.low;
        command([&](void* cb){if(!t.encodeFlush(cb,error))return false;MetalNumanXHumanMatterPass p{};
            p.phase=MetalNumanXHumanMatterPhase::postDynamics;p.commandBuffer=cb;p.environmentCount=1;p.stepCount=1;p.physicsSubstepCount=1;
            p.bodyPoses=(__bridge void*)bodies;p.bodyPositionLow=(__bridge void*)low;p.pointJacobians=(__bridge void*)jacobian;p.v=(__bridge void*)velocity;
            p.bodyPoseStride=1;p.bodyCount=1;p.qCoordinateCount=7;p.dofCount=6;p.vStride=6;p.pointWorldStride=4;p.pointJacobianStride=72;
            p.transactionFingerprint=100+serial;p.linearizationEpoch=20+serial;p.slotGeneration=serial;
            return t.encodeCandidate(p,4+acceptedOrdinal,100000+acceptedOrdinal*kNumiHumanBehaviorTimestepNanoseconds,error);});
    }
    auto fence(std::uint64_t serial,std::uint32_t abi=MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION){MRNumanXHumanMatterJointPublicationFenceGPU f{};
        f.abiVersion=abi;f.structBytes=sizeof(f);f.status=MR_NUMANX_HUMAN_MATTER_PUBLICATION_COMMITTED;f.controlStep=static_cast<std::uint32_t>(serial);f.physicsSubstepCount=1;
        f.ownerProgramFingerprint=10;f.transactionFingerprint=100+serial;f.linearizationEpoch=20+serial;f.slotGeneration=serial;
        f.physicsTokenFingerprint=11+serial;f.brainProgramFingerprint=12;f.brainShadowStateFingerprint=13;f.brainWitnessFingerprint=14;f.appliedDecisionFingerprint=15;f.jointCommitFingerprint=16;f.brainGeneration=serial;
        f.fenceFingerprint=hashFence(f);return f;
    }
    auto release(MetalHumanBehaviorTelemetry& t,std::uint64_t serial,bool accepted,std::uint64_t acceptedOrdinal=0,std::uint32_t fenceABI=MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION){if(acceptedOrdinal==0)acceptedOrdinal=serial;MRHumanBehaviorReleaseGPU r{};
        r.programFingerprint=t.fingerprint();r.transactionFingerprint=100+serial;r.linearizationEpoch=20+serial;r.slotGeneration=serial;
        r.physicsGeneration=4+acceptedOrdinal;r.acceptedTimestampNanoseconds=100000+acceptedOrdinal*kNumiHumanBehaviorTimestepNanoseconds;r.publicationSerial=t.completedAttempts()+1;r.released=accepted?1:2;
        if(accepted)r.jointFenceFingerprint=fence(serial,fenceABI).fenceFingerprint;return r;
    }
    HumanBehaviorTraceBinding traceBinding(){HumanBehaviorTraceBinding b{};b.metricProgramSHA256.fill(0x5a);b.modelSourceFingerprint=0x501;b.acceptedStateProofProgramFingerprint=0x502;b.clockDomain=MRNX_PHYSICAL_CLOCK_DOMAIN_EXACT_NANOSECONDS;b.clockQuantumNanoseconds=MRNX_EXACT_CLOCK_QUANTUM_NANOSECONDS;return b;}
    HumanBehaviorTraceAttemptContext traceContext(const MRHumanBehaviorReleaseGPU& r,bool accepted,std::uint64_t baseEpoch,std::uint64_t basePhysics,std::uint64_t baseTimestamp,std::uint64_t baseToken,std::uint64_t basePublicationFingerprint,bool candidateProof=true){HumanBehaviorTraceAttemptContext c{};c.controlStep=static_cast<std::uint32_t>(r.slotGeneration);c.basePublicationEpoch=baseEpoch;c.basePhysicsGeneration=basePhysics;c.baseAcceptedTimestampNanoseconds=baseTimestamp;c.baseAcceptedTokenFingerprint=baseToken;c.basePublicationFingerprint=basePublicationFingerprint;
        c.auditCoveredMask=MR_HUMAN_BEHAVIOR_AUDIT_ROOT_ASSISTANCE|MR_HUMAN_BEHAVIOR_AUDIT_UNACCEPTED_PUBLICATION;
        if(candidateProof){c.candidateStateProofFingerprint=0x1000+r.slotGeneration;c.candidateAcceptedTokenFingerprint=accepted?fence(r.slotGeneration,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2).physicsTokenFingerprint:0x2000+r.slotGeneration;c.candidatePublicationFingerprint=0x3000+r.slotGeneration;}
        if(accepted){c.afterPublicationEpoch=baseEpoch+1;c.afterPhysicsGeneration=r.physicsGeneration;c.afterAcceptedTimestampNanoseconds=r.acceptedTimestampNanoseconds;c.afterAcceptedTokenFingerprint=c.candidateAcceptedTokenFingerprint;c.afterPublicationFingerprint=0x4000+r.slotGeneration;}
        else{c.afterPublicationEpoch=baseEpoch;c.afterPhysicsGeneration=basePhysics;c.afterAcceptedTimestampNanoseconds=baseTimestamp;c.afterAcceptedTokenFingerprint=baseToken;c.afterPublicationFingerprint=basePublicationFingerprint;}return c;}
    mrnx_behavior_trace_state_component_bundle_v1 stateComponents(
        const MRHumanBehaviorReleaseGPU& r,bool accepted,std::uint8_t seed,
        std::uint32_t coverage=MRNX_BEHAVIOR_TRACE_STATE_COMPONENT_COMPLETE_MASK_V1){
        mrnx_behavior_trace_state_component_bundle_v1 c{};c.abi_version=MRNX_BEHAVIOR_TRACE_ABI_V1;
        c.struct_size=sizeof(c);c.covered_mask=coverage;c.attempt_index=r.publicationSerial;
        c.transaction_fingerprint=r.transactionFingerprint;
        if(coverage&MRNX_BEHAVIOR_TRACE_STATE_COMPONENT_SENSOR_V1){fillDigest(c.before_sensor_sha256,seed);
            fillDigest(c.candidate_sensor_sha256,static_cast<std::uint8_t>(seed+1));
            if(accepted)std::memcpy(c.after_sensor_sha256,c.candidate_sensor_sha256,32);
            else std::memcpy(c.after_sensor_sha256,c.before_sensor_sha256,32);}
        if(coverage&MRNX_BEHAVIOR_TRACE_STATE_COMPONENT_PUBLICATION_V1){fillDigest(c.before_publication_sha256,static_cast<std::uint8_t>(seed+3));
            if(accepted)fillDigest(c.after_publication_sha256,static_cast<std::uint8_t>(seed+4));
            else std::memcpy(c.after_publication_sha256,c.before_publication_sha256,32);}
        return c;
    }
    HumanBehaviorTraceFinalContext traceFinal(std::uint64_t epoch,std::uint64_t physics,std::uint64_t timestamp,std::uint64_t token,std::uint64_t publication){HumanBehaviorTraceFinalContext f{};f.quiescent=true;f.publicationEpoch=epoch;f.physicsGeneration=physics;f.brainGeneration=epoch;f.sensorGeneration=epoch;f.timestampNanoseconds=timestamp;f.acceptedTokenFingerprint=token;f.publicationFingerprint=publication;return f;}
};
}
int main(int argc,const char* argv[]){@autoreleasepool{try{
    need(argc==2,"usage: human_behavior_telemetry_check MetalRobo.metallib");Driver d(argv[1]);auto t=d.telemetry();
    d.initial(t);need(t.initialObservationEncoded(),"pre-dynamics reset observation was not encoded");
    d.measure(t,1,std::ldexp(1.0f,-50));auto first=d.fence(1);auto release=d.release(t,1,true);need(t.terminal(release,&first,d.error),d.error.c_str());
    const auto pending=t.snapshot();need(pending.reduction[0].acceptedRootCount==0,"pending sample prematurely counted");
    d.flush(t);const auto accepted=t.snapshot();const auto& a=accepted.reduction[0];
    need(a.status==0&&a.acceptedRootCount==1&&a.metricSampleCount==1&&a.endNanoseconds==112500,"accepted nonzero epoch reduction failed");
    need(a.postureViolationCount==0&&a.speedErrorSampleCount==1&&std::abs(double(a.extremaHigh.w)+a.extremaLow.w-.0625)<1e-12,"threshold/SSE measurement failed");
    need(a.auditCoveredRootCount==0&&a.auditCoveredAttemptCount==0&&a.initialPostureValid==1&&a.initialSettled==1,"reset posture/settled measurement missing");
    auto rolledBack=d.telemetry();const auto pristine=rolledBack.snapshot();d.initial(rolledBack);need(rolledBack.initialObservationEncoded(),"initial observation host state was not set");need(rolledBack.restore(pristine,d.error),d.error.c_str());need(!rolledBack.initialObservationEncoded(),"pre-submit initial observation rollback retained host state");d.initial(rolledBack);d.measure(rolledBack,1,std::ldexp(1.0f,-50));auto rolledBackRelease=d.release(rolledBack,1,true);need(rolledBack.terminal(rolledBackRelease,&first,d.error),d.error.c_str());d.flush(rolledBack);const auto rolledBackResult=rolledBack.snapshot().reduction[0];need(std::memcmp(&a,&rolledBackResult,sizeof(a))==0,"initial observation rollback changed accepted telemetry");
    d.flush(t);auto repeated=t.snapshot();need(std::memcmp(&a,&repeated.reduction[0],sizeof(a))==0,"duplicate flush changed metrics");
    need(t.restore(pending,d.error),d.error.c_str());d.flush(t);auto replay=t.snapshot();need(std::memcmp(&a,&replay.reduction[0],sizeof(a))==0,"pending checkpoint replay changed metrics");
    // Current root rejects before postDynamics: beginStep consumes pending,
    // then terminal records a rejection with no matching candidate sample.
    need(t.restore(pending,d.error),d.error.c_str());d.flush(t);auto rejected=d.release(t,2,false);need(t.terminal(rejected,nullptr,d.error),d.error.c_str());d.flush(t);
    const auto afterReject=t.snapshot();need(afterReject.reduction[0].status==0&&afterReject.reduction[0].acceptedRootCount==1&&afterReject.reduction[0].rejectedAttemptCount==1&&afterReject.reduction[0].metricSampleCount==1,"early rejection lost accepted sample or counted stale metrics");
    need(t.restore(afterReject,d.error),"checkpoint after early rejected attempt was denied");d.flush(t);
    d.measure(t,3,std::ldexp(1.0f,-50),2);auto retryFence=d.fence(3,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto retryRelease=d.release(t,3,true,2,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);
    need(t.terminal(retryRelease,&retryFence,d.error),d.error.c_str());d.flush(t);const auto retry=t.snapshot();
    need(retry.reduction[0].status==0&&retry.reduction[0].acceptedRootCount==2&&retry.reduction[0].rejectedAttemptCount==1&&retry.reduction[0].endNanoseconds==125000,"rejection retry clock/count drift");
    auto wrongEpoch=d.telemetry(200000);need(!wrongEpoch.restore(pending,d.error),"checkpoint from mismatched reset epoch admitted");
    auto delayed=d.telemetry();auto delayedReject=d.release(delayed,1,false);need(delayed.terminal(delayedReject,nullptr,d.error),d.error.c_str());d.flush(delayed);need(!delayed.initialObservationEncoded(),"early rejection invented a reset observation");d.initial(delayed);d.measure(delayed,2,std::ldexp(1.0f,-50),1);auto delayedFence=d.fence(2);auto delayedRelease=d.release(delayed,2,true,1);need(delayed.terminal(delayedRelease,&delayedFence,d.error),d.error.c_str());d.flush(delayed);const auto delayedResult=delayed.snapshot().reduction[0];need(delayedResult.status==0&&delayedResult.initialPostureValid==1&&delayedResult.initialSettled==1&&delayedResult.rejectedAttemptCount==1&&delayedResult.acceptedRootCount==1,"reset observation did not recover after an early first-attempt rejection");
    auto below=d.telemetry();d.measure(below,1,-std::ldexp(1.0f,-50));auto belowRelease=d.release(below,1,true);need(below.terminal(belowRelease,&first,d.error),d.error.c_str());d.flush(below);need(below.snapshot().reduction[0].postureViolationCount==1,"negative low threshold side lost");
    auto bad=d.telemetry();d.measure(bad,1,std::ldexp(1.0f,-50));auto corrupted=first;corrupted.brainShadowStateFingerprint=0;corrupted.fenceFingerprint=hashFence(corrupted);auto badRelease=d.release(bad,1,true);badRelease.jointFenceFingerprint=corrupted.fenceFingerprint;need(bad.terminal(badRelease,&corrupted,d.error),d.error.c_str());d.flush(bad);need(bad.snapshot().reduction[0].status!=0&&bad.snapshot().reduction[0].acceptedRootCount==0,"invalid root fence counted");
    auto unknownABI=d.telemetry();auto unknownFence=d.fence(1);unknownFence.abiVersion=3;unknownFence.fenceFingerprint=hashFence(unknownFence);auto unknownRelease=d.release(unknownABI,1,true);unknownRelease.jointFenceFingerprint=unknownFence.fenceFingerprint;need(!unknownABI.terminal(unknownRelease,&unknownFence,d.error),"unknown publication-fence ABI admitted");
    auto wrongSize=d.telemetry();auto wrongSizeFence=d.fence(1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);wrongSizeFence.structBytes=sizeof(wrongSizeFence)-16;wrongSizeFence.fenceFingerprint=hashFence(wrongSizeFence);auto wrongSizeRelease=d.release(wrongSize,1,true,1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);wrongSizeRelease.jointFenceFingerprint=wrongSizeFence.fenceFingerprint;need(!wrongSize.terminal(wrongSizeRelease,&wrongSizeFence,d.error),"wrong publication-fence byte count admitted");
    auto corruptV2=d.telemetry();d.measure(corruptV2,1,std::ldexp(1.0f,-50));auto corruptV2Fence=d.fence(1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);corruptV2Fence.brainWitnessFingerprint^=1;auto corruptV2Release=d.release(corruptV2,1,true,1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);need(corruptV2.terminal(corruptV2Release,&corruptV2Fence,d.error),d.error.c_str());d.flush(corruptV2);need(corruptV2.snapshot().reduction[0].status!=0&&corruptV2.snapshot().reduction[0].acceptedRootCount==0,"corrupt v2 publication-fence hash counted");
    mrnx_behavior_trace_config_v1 traceConfig{};traceConfig.abi_version=MRNX_BEHAVIOR_TRACE_ABI_V1;traceConfig.struct_size=sizeof(traceConfig);traceConfig.record_capacity=4;traceConfig.expected_accepted_roots=2;
    auto traced=d.telemetry();need(traced.traceAttach(traceConfig,d.traceBinding(),d.error),d.error.c_str());need(traced.traceAttached()&&!traced.traceFinalized(),"trace attach state missing");d.initial(traced);
    d.measure(traced,1,std::ldexp(1.0f,-50));auto traceFence1=d.fence(1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto traceRelease1=d.release(traced,1,true,1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto traceContext1=d.traceContext(traceRelease1,true,0,4,100000,0,0);auto traceComponents1=d.stateComponents(traceRelease1,true,0x10);need(traced.terminal(traceRelease1,&traceFence1,&traceContext1,traceComponents1,d.error),d.error.c_str());d.flush(traced);d.flush(traced);
    d.measure(traced,2,std::ldexp(1.0f,-50),2);auto traceReject=d.release(traced,2,false,2);auto traceRejectContext=d.traceContext(traceReject,false,1,5,112500,traceFence1.physicsTokenFingerprint,0x4001,true);auto traceRejectComponents=d.stateComponents(traceReject,false,0x20);need(traced.terminal(traceReject,nullptr,&traceRejectContext,traceRejectComponents,d.error),d.error.c_str());d.flush(traced);
    d.measure(traced,3,std::ldexp(1.0f,-50),2);auto traceFence3=d.fence(3,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto traceRelease3=d.release(traced,3,true,2,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto traceContext3=d.traceContext(traceRelease3,true,1,5,112500,traceFence1.physicsTokenFingerprint,0x4001);auto traceComponents3=d.stateComponents(traceRelease3,true,0x30);need(traced.terminal(traceRelease3,&traceFence3,&traceContext3,traceComponents3,d.error),d.error.c_str());d.flush(traced);
    std::array<mrnx_behavior_trace_record_v1,2> undersized{};mrnx_behavior_trace_chunk_v1 unchangedChunk{};unchangedChunk.abi_version=99;need(!traced.traceDrain(unchangedChunk,undersized,d.error)&&unchangedChunk.abi_version==99,"undersized trace drain mutated output or succeeded");
    std::array<mrnx_behavior_trace_record_v1,4> traceRecords{};traceRecords[0].abi_version=97;std::array<mrnx_behavior_trace_state_component_record_v1,2> undersizedComponents{};undersizedComponents[0].abi_version=96;mrnx_behavior_trace_chunk_v1 unchangedComponentChunk{};unchangedComponentChunk.abi_version=98;need(!traced.traceDrain(unchangedComponentChunk,traceRecords,undersizedComponents,d.error)&&unchangedComponentChunk.abi_version==98&&traceRecords[0].abi_version==97&&undersizedComponents[0].abi_version==96,"undersized component drain mutated output or succeeded");
    auto* overlappingComponentRecords=reinterpret_cast<mrnx_behavior_trace_state_component_record_v1*>(traceRecords.data());std::span<mrnx_behavior_trace_state_component_record_v1> overlappingComponents(overlappingComponentRecords,traceRecords.size());mrnx_behavior_trace_chunk_v1 overlappingChunk{};overlappingChunk.abi_version=95;need(!traced.traceDrain(overlappingChunk,traceRecords,overlappingComponents,d.error)&&overlappingChunk.abi_version==95&&traceRecords[0].abi_version==97,"overlapping component drain mutated output or advanced");
    std::array<mrnx_behavior_trace_state_component_record_v1,4> traceComponentRecords{};mrnx_behavior_trace_chunk_v1 traceChunk{};need(traced.traceDrain(traceChunk,traceRecords,traceComponentRecords,d.error),d.error.c_str());need(traceChunk.trace_status==MRNX_BEHAVIOR_TRACE_STATUS_READY_V1&&traceChunk.record_count==3&&traceChunk.observed_attempt_count==3&&traceChunk.total_record_count==3&&traceChunk.drained_record_count==3&&traceChunk.dropped_record_count==0,"bounded trace chunk accounting failed");
    constexpr std::uint32_t partialNativeAudit=MR_HUMAN_BEHAVIOR_AUDIT_ROOT_ASSISTANCE|MR_HUMAN_BEHAVIOR_AUDIT_UNACCEPTED_PUBLICATION;
    need(traceRecords[0].disposition==MRNX_BEHAVIOR_TRACE_JOINTLY_PUBLISHED_V1&&traceRecords[0].metric_kind==MRNX_BEHAVIOR_TRACE_METRIC_ACCEPTED_V1&&traceRecords[0].audit_covered_mask==partialNativeAudit&&traceRecords[0].audit_violation_mask==0&&traceRecords[0].record_fingerprint==hashTraceRecord(traceRecords[0]),"accepted trace record invalid");
    need(traceRecords[1].disposition==MRNX_BEHAVIOR_TRACE_REJECTED_RELEASED_V1&&traceRecords[1].metric_kind==MRNX_BEHAVIOR_TRACE_METRIC_REJECTED_CANDIDATE_V1&&traceRecords[1].audit_covered_mask==partialNativeAudit&&traceRecords[1].audit_violation_mask==0&&traceRecords[1].after_publication_epoch==traceRecords[1].base_publication_epoch&&traceRecords[1].after_physics_generation==traceRecords[1].base_physics_generation&&traceRecords[1].after_accepted_timestamp_nanoseconds==traceRecords[1].base_accepted_timestamp_nanoseconds&&traceRecords[1].after_accepted_token_fingerprint==traceRecords[1].base_accepted_token_fingerprint&&traceRecords[1].joint_fence_fingerprint==0,"rejected trace published a consequence");
    need(traceRecords[1].previous_record_fingerprint==traceRecords[0].record_fingerprint&&traceRecords[2].previous_record_fingerprint==traceRecords[1].record_fingerprint&&traceRecords[2].record_fingerprint==hashTraceRecord(traceRecords[2]),"trace fingerprint chain failed");
    const std::array<std::uint8_t,32> zeroSHA{};need(traceComponentRecords[0].abi_version==MRNX_BEHAVIOR_TRACE_ABI_V1&&traceComponentRecords[0].struct_size==sizeof(traceComponentRecords[0])&&traceComponentRecords[0].covered_mask==MRNX_BEHAVIOR_TRACE_STATE_COMPONENT_COMPLETE_MASK_V1&&traceComponentRecords[0].attempt_index==traceRecords[0].attempt_index&&traceComponentRecords[0].disposition==traceRecords[0].disposition&&traceComponentRecords[0].transaction_fingerprint==traceRecords[0].transaction_fingerprint&&std::memcmp(traceComponentRecords[0].previous_record_sha256,zeroSHA.data(),zeroSHA.size())==0,"first state-component companion identity failed");
    const auto componentHash0=hashStateComponentRecord(traceComponentRecords[0]);const auto componentHash1=hashStateComponentRecord(traceComponentRecords[1]);const auto componentHash2=hashStateComponentRecord(traceComponentRecords[2]);
    need(std::memcmp(traceComponentRecords[0].record_sha256,componentHash0.data(),componentHash0.size())==0&&std::memcmp(traceComponentRecords[1].previous_record_sha256,traceComponentRecords[0].record_sha256,32)==0&&std::memcmp(traceComponentRecords[1].record_sha256,componentHash1.data(),componentHash1.size())==0&&std::memcmp(traceComponentRecords[2].previous_record_sha256,traceComponentRecords[1].record_sha256,32)==0&&std::memcmp(traceComponentRecords[2].record_sha256,componentHash2.data(),componentHash2.size())==0,"state-component SHA256 chain failed");
    need(traceComponentRecords[1].attempt_index==traceRecords[1].attempt_index&&traceComponentRecords[1].disposition==MRNX_BEHAVIOR_TRACE_REJECTED_RELEASED_V1&&std::memcmp(traceComponentRecords[1].before_sensor_sha256,traceComponentRecords[1].after_sensor_sha256,32)==0&&std::memcmp(traceComponentRecords[1].before_publication_sha256,traceComponentRecords[1].after_publication_sha256,32)==0,"rejected state-component companion changed accepted state");
    mrnx_behavior_trace_terminal_request_v1 completeRequest{};completeRequest.abi_version=MRNX_BEHAVIOR_TRACE_ABI_V1;completeRequest.struct_size=sizeof(completeRequest);completeRequest.reason=MRNX_BEHAVIOR_TRACE_TERMINAL_COMPLETED_V1;auto finalTraceContext=d.traceFinal(2,6,125000,traceFence3.physicsTokenFingerprint,0x4003);mrnx_behavior_trace_terminal_v1 traceTerminal{};need(traced.traceFinalize(completeRequest,finalTraceContext,traceTerminal,d.error),d.error.c_str());
    constexpr std::uint32_t unavailableTraceEvidence=MRNX_BEHAVIOR_TRACE_EVIDENCE_NATIVE_AUDIT_V1|MRNX_BEHAVIOR_TRACE_EVIDENCE_FORBIDDEN_CONTACT_V1|MRNX_BEHAVIOR_TRACE_EVIDENCE_ACCEPTED_ROOT_PROOF_V1|MRNX_BEHAVIOR_TRACE_EVIDENCE_FULL_BEHAVIOR_V1|MRNX_BEHAVIOR_TRACE_EVIDENCE_PHYSICAL_V1|MRNX_BEHAVIOR_TRACE_EVIDENCE_BIOLOGICAL_V1|MRNX_BEHAVIOR_TRACE_EVIDENCE_PERFORMANCE_V1|MRNX_BEHAVIOR_TRACE_EVIDENCE_PRODUCTION_V1;
    need(traceTerminal.capture_status==MRNX_BEHAVIOR_TRACE_CAPTURE_COMPLETE_V1&&traceTerminal.accepted_root_count==2&&traceTerminal.rejected_attempt_count==1&&traceTerminal.completed_attempt_count==3&&traceTerminal.total_record_count==3&&traceTerminal.drained_record_count==3&&traceTerminal.chunk_count==1&&traceTerminal.qualification_flags==MRNX_BEHAVIOR_TRACE_EVIDENCE_SOURCE_BOUND_METRIC_V1&&traceTerminal.unavailable_evidence_flags==unavailableTraceEvidence&&traceTerminal.terminal_fingerprint!=0&&traced.traceFinalized(),"trace terminal completion or evidence boundary failed");
    mrnx_behavior_trace_terminal_v1 repeatedTerminal{};need(traced.traceFinalize(completeRequest,finalTraceContext,repeatedTerminal,d.error)&&std::memcmp(&traceTerminal,&repeatedTerminal,sizeof(traceTerminal))==0,"trace finalization is not idempotent");auto differentRequest=completeRequest;differentRequest.reason=MRNX_BEHAVIOR_TRACE_TERMINAL_CANCELLED_V1;mrnx_behavior_trace_terminal_v1 unchangedTerminal{};unchangedTerminal.abi_version=99;need(!traced.traceFinalize(differentRequest,finalTraceContext,unchangedTerminal,d.error)&&unchangedTerminal.abi_version==99,"different repeated trace finalization admitted");
    auto invalidConfig=traceConfig;invalidConfig.flags=1;auto invalidAttach=d.telemetry();need(!invalidAttach.traceAttach(invalidConfig,d.traceBinding(),d.error)&&!invalidAttach.traceAttached(),"invalid trace configuration attached");
    auto acceptedComponentNegative=d.telemetry();auto acceptedComponentConfig=traceConfig;acceptedComponentConfig.expected_accepted_roots=1;need(acceptedComponentNegative.traceAttach(acceptedComponentConfig,d.traceBinding(),d.error),d.error.c_str());d.measure(acceptedComponentNegative,1,std::ldexp(1.0f,-50));auto acceptedComponentFence=d.fence(1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto acceptedComponentRelease=d.release(acceptedComponentNegative,1,true,1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto acceptedComponentContext=d.traceContext(acceptedComponentRelease,true,0,4,100000,0,0);auto changedAcceptedComponents=d.stateComponents(acceptedComponentRelease,true,0x50);changedAcceptedComponents.after_sensor_sha256[0]^=1u;need(!acceptedComponentNegative.terminal(acceptedComponentRelease,&acceptedComponentFence,&acceptedComponentContext,changedAcceptedComponents,d.error)&&acceptedComponentNegative.completedAttempts()==0,"accepted state-component post-sensor diverged from candidate");
    auto componentNegative=d.telemetry();auto componentConfig=traceConfig;componentConfig.expected_accepted_roots=1;need(componentNegative.traceAttach(componentConfig,d.traceBinding(),d.error),d.error.c_str());d.measure(componentNegative,1,std::ldexp(1.0f,-50));auto componentReject=d.release(componentNegative,1,false,1);auto componentRejectContext=d.traceContext(componentReject,false,0,4,100000,0,0,true);auto validRejectedComponents=d.stateComponents(componentReject,false,0x60);
    auto zeroCoverageComponents=validRejectedComponents;zeroCoverageComponents.covered_mask=0;need(!componentNegative.terminal(componentReject,nullptr,&componentRejectContext,zeroCoverageComponents,d.error)&&componentNegative.completedAttempts()==0,"zero state-component coverage admitted or mutated terminal state");
    auto unknownCoverageComponents=validRejectedComponents;unknownCoverageComponents.covered_mask|=4u;need(!componentNegative.terminal(componentReject,nullptr,&componentRejectContext,unknownCoverageComponents,d.error)&&componentNegative.completedAttempts()==0,"unknown state-component coverage admitted");
    auto zeroDigestComponents=validRejectedComponents;std::memset(zeroDigestComponents.candidate_sensor_sha256,0,32);need(!componentNegative.terminal(componentReject,nullptr,&componentRejectContext,zeroDigestComponents,d.error)&&componentNegative.completedAttempts()==0,"covered zero state-component digest admitted");
    auto changedRejectedComponents=validRejectedComponents;changedRejectedComponents.after_publication_sha256[0]^=1u;need(!componentNegative.terminal(componentReject,nullptr,&componentRejectContext,changedRejectedComponents,d.error)&&componentNegative.completedAttempts()==0,"rejected state-component publication mutation admitted");
    auto wrongComponentIdentity=validRejectedComponents;++wrongComponentIdentity.transaction_fingerprint;need(!componentNegative.terminal(componentReject,nullptr,&componentRejectContext,wrongComponentIdentity,d.error)&&componentNegative.completedAttempts()==0,"mismatched state-component identity admitted");
    need(componentNegative.terminal(componentReject,nullptr,&componentRejectContext,validRejectedComponents,d.error),d.error.c_str());d.flush(componentNegative);std::array<mrnx_behavior_trace_record_v1,4> componentNegativeCore{};std::array<mrnx_behavior_trace_state_component_record_v1,4> componentNegativeRecords{};mrnx_behavior_trace_chunk_v1 componentNegativeChunk{};need(componentNegative.traceDrain(componentNegativeChunk,componentNegativeCore,componentNegativeRecords,d.error)&&componentNegativeChunk.record_count==1&&componentNegativeRecords[0].attempt_index==1,"valid rejected state-component bundle did not drain atomically");
    auto missingComponent=d.telemetry();need(missingComponent.traceAttach(componentConfig,d.traceBinding(),d.error),d.error.c_str());d.measure(missingComponent,1,std::ldexp(1.0f,-50));auto missingRelease=d.release(missingComponent,1,false,1);auto missingContext=d.traceContext(missingRelease,false,0,4,100000,0,0,true);need(missingComponent.terminal(missingRelease,nullptr,&missingContext,d.error),d.error.c_str());d.flush(missingComponent);std::array<mrnx_behavior_trace_record_v1,4> missingCore{};missingCore[0].abi_version=95;std::array<mrnx_behavior_trace_state_component_record_v1,4> missingRecords{};missingRecords[0].abi_version=94;mrnx_behavior_trace_chunk_v1 missingChunk{};missingChunk.abi_version=93;need(!missingComponent.traceDrain(missingChunk,missingCore,missingRecords,d.error)&&missingChunk.abi_version==93&&missingCore[0].abi_version==95&&missingRecords[0].abi_version==94,"missing state-component bundle did not fail atomically");need(missingComponent.traceDrain(missingChunk,missingCore,d.error)&&missingChunk.record_count==1,"core-only drain changed after missing companion failure");
    auto boundedComponents=d.telemetry();auto boundedConfig=componentConfig;boundedConfig.record_capacity=1;need(boundedComponents.traceAttach(boundedConfig,d.traceBinding(),d.error),d.error.c_str());d.measure(boundedComponents,1,std::ldexp(1.0f,-50),1);auto boundedRelease1=d.release(boundedComponents,1,false,1);auto boundedContext1=d.traceContext(boundedRelease1,false,0,4,100000,0,0,true);auto boundedBundle1=d.stateComponents(boundedRelease1,false,0x70);need(boundedComponents.terminal(boundedRelease1,nullptr,&boundedContext1,boundedBundle1,d.error),d.error.c_str());d.flush(boundedComponents);d.measure(boundedComponents,2,std::ldexp(1.0f,-50),1);auto boundedRelease2=d.release(boundedComponents,2,false,1);auto boundedContext2=d.traceContext(boundedRelease2,false,0,4,100000,0,0,true);auto boundedBundle2=d.stateComponents(boundedRelease2,false,0x80);need(boundedComponents.terminal(boundedRelease2,nullptr,&boundedContext2,boundedBundle2,d.error),"bounded companion capacity poisoned terminal behavior");d.flush(boundedComponents);std::array<mrnx_behavior_trace_record_v1,1> boundedCore{};boundedCore[0].abi_version=92;std::array<mrnx_behavior_trace_state_component_record_v1,1> boundedRecords{};boundedRecords[0].abi_version=91;mrnx_behavior_trace_chunk_v1 boundedChunk{};boundedChunk.abi_version=90;need(!boundedComponents.traceDrain(boundedChunk,boundedCore,boundedRecords,d.error)&&boundedChunk.abi_version==90&&boundedCore[0].abi_version==92&&boundedRecords[0].abi_version==91,"bounded companion overflow did not fail atomically");need(boundedComponents.traceDrain(boundedChunk,boundedCore,d.error)&&boundedChunk.trace_status==MRNX_BEHAVIOR_TRACE_STATUS_OVERFLOW_V1&&boundedChunk.record_count==1&&boundedChunk.dropped_record_count==1,"bounded companion overflow changed core trace accounting");
    auto overflow=d.telemetry();auto overflowConfig=traceConfig;overflowConfig.record_capacity=1;need(overflow.traceAttach(overflowConfig,d.traceBinding(),d.error),d.error.c_str());d.measure(overflow,1,std::ldexp(1.0f,-50));auto overflowFence1=d.fence(1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto overflowRelease1=d.release(overflow,1,true,1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto overflowContext1=d.traceContext(overflowRelease1,true,0,4,100000,0,0);need(overflow.terminal(overflowRelease1,&overflowFence1,&overflowContext1,d.error),d.error.c_str());d.flush(overflow);d.measure(overflow,2,std::ldexp(1.0f,-50),2);auto overflowFence2=d.fence(2,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto overflowRelease2=d.release(overflow,2,true,2,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto overflowContext2=d.traceContext(overflowRelease2,true,1,5,112500,overflowFence1.physicsTokenFingerprint,0x4001);need(overflow.terminal(overflowRelease2,&overflowFence2,&overflowContext2,d.error),d.error.c_str());d.flush(overflow);const auto overflowAggregate=overflow.snapshot().reduction[0];need(overflowAggregate.status==0&&overflowAggregate.acceptedRootCount==2,"trace overflow poisoned behavior aggregate");std::array<mrnx_behavior_trace_record_v1,1> overflowRecords{};mrnx_behavior_trace_chunk_v1 overflowChunk{};need(overflow.traceDrain(overflowChunk,overflowRecords,d.error)&&overflowChunk.trace_status==MRNX_BEHAVIOR_TRACE_STATUS_OVERFLOW_V1&&overflowChunk.record_count==1&&overflowChunk.observed_attempt_count==2&&overflowChunk.total_record_count==1&&overflowChunk.dropped_record_count==1,"trace overflow was not typed");auto overflowFinal=d.traceFinal(2,6,125000,overflowFence2.physicsTokenFingerprint,0x4002);mrnx_behavior_trace_terminal_v1 overflowTerminal{};need(overflow.traceFinalize(completeRequest,overflowFinal,overflowTerminal,d.error)&&overflowTerminal.capture_status==MRNX_BEHAVIOR_TRACE_CAPTURE_PARTIAL_V1&&overflowTerminal.qualification_flags==MRNX_BEHAVIOR_TRACE_EVIDENCE_SOURCE_BOUND_METRIC_V1,"overflow trace claimed completion or lost source boundary");
    auto invalidTrace=d.telemetry();auto invalidTraceConfig=traceConfig;invalidTraceConfig.expected_accepted_roots=1;need(invalidTrace.traceAttach(invalidTraceConfig,d.traceBinding(),d.error),d.error.c_str());d.measure(invalidTrace,1,std::ldexp(1.0f,-50));auto invalidTraceFence=d.fence(1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto invalidTraceRelease=d.release(invalidTrace,1,true,1,MR_NUMANX_HUMAN_MATTER_PUBLICATION_FENCE_ABI_VERSION_V2);auto invalidTraceContext=d.traceContext(invalidTraceRelease,true,0,4,100000,0,0);++invalidTraceContext.afterPhysicsGeneration;need(invalidTrace.terminal(invalidTraceRelease,&invalidTraceFence,&invalidTraceContext,d.error),d.error.c_str());d.flush(invalidTrace);const auto invalidTraceAggregate=invalidTrace.snapshot().reduction[0];need(invalidTraceAggregate.status==0&&invalidTraceAggregate.acceptedRootCount==1,"invalid trace context poisoned behavior aggregate");std::array<mrnx_behavior_trace_record_v1,2> invalidTraceRecords{};mrnx_behavior_trace_chunk_v1 invalidTraceChunk{};need(invalidTrace.traceDrain(invalidTraceChunk,invalidTraceRecords,d.error)&&invalidTraceChunk.trace_status==MRNX_BEHAVIOR_TRACE_STATUS_INVALID_V1&&invalidTraceChunk.record_count==0&&invalidTraceChunk.observed_attempt_count==1&&invalidTraceChunk.dropped_record_count==1,"invalid trace context was not isolated");auto invalidFinal=d.traceFinal(1,5,112500,invalidTraceFence.physicsTokenFingerprint,0x4001);mrnx_behavior_trace_terminal_v1 invalidTerminal{};need(invalidTrace.traceFinalize(completeRequest,invalidFinal,invalidTerminal,d.error)&&invalidTerminal.capture_status==MRNX_BEHAVIOR_TRACE_CAPTURE_FAILED_V1,"invalid trace context claimed completion");
    std::printf("human_behavior_telemetry=pass controls=21 pending_publication=denied committed=once early_reject=preserved retry=pass delayed_initial=pass initial_rollback=bitwise v2_fence=pass v2_negatives=pass checkpoint_replay=bitwise double_flush=bitwise nonzero_epoch=pass mismatched_reset=denied paired_threshold=pass audit_coverage=partial_native_transport trace_chunk=o1 trace_reject=no_consequence trace_overflow=partial trace_invalid=isolated trace_terminal=idempotent clock=12500ns physical_steps=0\n");return 0;
}catch(const std::exception& e){std::fprintf(stderr,"human_behavior_telemetry=fail %s\n",e.what());return 1;}}}
