// Opt-in local qualification against an admitted REAL cohort service.
// Browser automation is not uncoached researcher usability, physical touch or Safari evidence.
// Usage: NODE_PATH=<installed Playwright modules> node this-file.cjs URL OUTPUT_DIRECTORY
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const url=process.argv[2],out=process.argv[3];if(!url||!out)throw Error('Pass service URL and output directory');
fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.NUMILAB_BROWSER_CHANNEL||'chrome'}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),network=[],pending=[],pageErrors=[];const t0=performance.now();let firstGene=null,initialCohortCatalog=null;const requestStarts=new WeakMap();
 page.on('request',req=>requestStarts.set(req,performance.now()));
 page.on('pageerror',e=>pageErrors.push(String(e)));
 page.on('response',res=>{if(!res.url().includes('/api/'))return;const req=res.request(),p=(async()=>{const started=performance.now();let q;try{q=req.postDataJSON();}catch{}const bytes=await res.body(),entry={path:new URL(res.url()).pathname,status:res.status(),bytes:bytes.length,completedMs:performance.now()-t0,requestDurationMs:performance.now()-(requestStarts.get(req)||t0)};if(entry.path==='/api/assays'){const admitted=JSON.parse(bytes).find(c=>c.id==='replogle-nadig-engineering-256');if(admitted)initialCohortCatalog={features:admitted.features,featuresTotal:admitted.featuresTotal,populations:admitted.populations?.length};}if(q?.query){const d=JSON.parse(bytes);entry.query={assayID:q.assayID,kind:q.query.kind,gene:q.query.gene,target:q.query.target,normalization:q.query.normalization,limit:q.query.limit,offset:q.query.offset};entry.items=d.items?.length;entry.arms=d.arms?.length;entry.values=(d.arms||[]).map(a=>({target:a.target,control:(a.controlValues||[]).length,observed:(a.observedValues||[]).length,observedUnavailable:a.observed==null}));entry.access=d.access;entry.responseBodyReadMs=performance.now()-started;if(q.assayID==='replogle-nadig-engineering-256'&&q.query.kind==='gene'&&!firstGene)firstGene={completedMs:entry.completedMs,...entry.query,bytes:entry.bytes};}network.push(entry);})();pending.push(p.catch(e=>network.push({error:String(e),path:new URL(res.url()).pathname})));});
 let report;try{await page.goto(url,{waitUntil:'domcontentloaded'});await page.locator('#population-assay option[value="replogle-nadig-engineering-256"]').waitFor({state:'attached'});if(await page.locator('#population-assay').inputValue()!=='replogle-nadig-engineering-256')await page.locator('#population-assay').selectOption('replogle-nadig-engineering-256');await page.waitForFunction(()=>window.populationLab.state.measuredOnly&&document.querySelectorAll('#population-population option').length>=4&&document.querySelector('#population-interventions button'));const metadataReadyMs=performance.now()-t0;await page.locator('#population-readout .measured-distribution').waitFor();const firstUsableCohortMs=performance.now()-t0;
 assert(await page.locator('#population-predict').isDisabled());assert.match(await page.locator('#population-prediction-reason').innerText(),/Register a model|compatible/i);
 const selectPopulation=async source=>{const value=await page.locator('#population-population option').evaluateAll((opts,prefix)=>opts.find(o=>o.value.startsWith(prefix+'|'))?.value,source);assert(value,'Missing population '+source);if(await page.locator('#population-population').inputValue()!==value)await page.locator('#population-population').selectOption(value);await page.waitForFunction(pop=>window.populationLab.state.population===pop&&window.populationLab.state.field?.arms?.some(a=>a.population===pop),value);return value;};
 assert(initialCohortCatalog&&!initialCohortCatalog.features.includes('NOC2L'),'NOC2L must exercise feature lookup beyond the initial catalog page');const hepPopulation=await selectPopulation('nadig-hepg2');await page.locator('#population-gene').fill('NOC2L');await page.waitForFunction(()=>[...document.querySelectorAll('#population-genes option')].some(o=>o.value==='NOC2L'));await page.locator('#population-gene').press('Tab');await page.waitForFunction(()=>window.populationLab.state.field?.gene==='NOC2L');
 const firstOpenButton=page.locator('#population-interventions button').filter({hasText:'MEASURED'}).first();await firstOpenButton.waitFor();await firstOpenButton.click();await page.waitForFunction(()=>window.populationLab.state.field?.gene==='NOC2L'&&window.populationLab.state.field?.arms?.[0]?.observed!=null);await page.locator('#population-normalization').selectOption('raw_counts');await page.waitForFunction(()=>window.populationLab.state.normalization==='raw_counts'&&window.populationLab.state.field?.arms?.[0]?.observed!=null);const raw=await page.evaluate(()=>({population:window.populationLab.state.population,gene:window.populationLab.state.field.gene,units:window.populationLab.state.field.units,target:window.populationLab.state.activeTarget,values:window.populationLab.state.field.arms.map(a=>({control:a.controlValues?.length,observed:a.observedValues?.length,controlCells:a.controlCells,outcomeCells:a.outcomeCells,evidence:a.evidence}))}));await page.locator('#population-readout').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'cohort-raw.png')});
 await page.locator('#population-normalization').selectOption('log1p_10000');await page.waitForFunction(()=>window.populationLab.state.normalization==='log1p_10000'&&window.populationLab.state.field?.units?.includes('log1p'));const normalized=await page.evaluate(()=>({units:window.populationLab.state.field.units,gene:window.populationLab.state.field.gene,target:window.populationLab.state.activeTarget}));await page.locator('#population-readout').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'cohort-normalized.png')});
 const reservedPopulation=await selectPopulation('replogle-rpe1');await page.waitForFunction(()=>window.populationLab.state.field?.arms?.length>0);const reserved=await page.evaluate(()=>({population:window.populationLab.state.population,model:window.populationLab.state.modelID,access:window.populationLab.state.field.access,arms:window.populationLab.state.field.arms.map(a=>({target:a.target,observed:a.observed,observedValues:a.observedValues?.length,evidence:a.evidence}))}));assert(reserved.arms.every(a=>a.observed===null&&a.observedValues===0),'Reserved RPE1 observations leaked');assert.equal(reserved.model,'replogle-nadig-engineering-256');assert(await page.locator('#population-predict').isDisabled());await page.locator('#population-readout').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'cohort-rpe1-reserved.png')});
 await selectPopulation('nadig-hepg2');await page.waitForFunction(()=>window.populationLab.state.field?.gene==='NOC2L');const measuredDraftID=await page.evaluate(()=>window.sharedWetLab.state.drafts.find(d=>d.selection.assayID==='replogle-nadig-engineering-256')?.id);assert(measuredDraftID,'Expected retained measured-cohort proposal');const measuredCard=page.locator(`.shared-card[data-id="${measuredDraftID}"]`);assert.equal(await measuredCard.locator('.stage-badge').innerText(),'UNEXECUTED PROPOSAL');assert.match(await measuredCard.innerText(),/Proposed RNA program/);assert.doesNotMatch(await measuredCard.innerText(),/Spatial preservation|mean log1p\(CPM\)/);await page.locator('#population-readout').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'cohort-final-hepg2.png')});await Promise.allSettled(pending);const cohortReads=network.filter(n=>n.query?.assayID==='replogle-nadig-engineering-256');assert(cohortReads.filter(n=>n.query.kind==='gene').every(n=>n.query.limit<=128&&n.values.every(v=>v.control<=128&&v.observed<=128)));assert(!network.some(n=>['/api/predict','/api/reveal'].includes(n.path)));assert.equal(pageErrors.length,0,pageErrors.join('\n'));
 report={format:'numilab-real-cohort-browser-qualification/v1',status:'passed',scope:'Actual admitted data browser engineering; no biological promotion or researcher usability claim',url,browser:'Headless Chrome via Playwright, fresh browser context; OS/disk cache not cleared',timings:{metadataReadyMs,firstUsableCohortMs,firstGeneRead:firstGene},initialCohortCatalog:{featureCount:initialCohortCatalog.features.length,featuresTotal:initialCohortCatalog.featuresTotal,populations:initialCohortCatalog.populations,NOC2LInInitialPage:false},populationIDs:{hepg2:hepPopulation,rpe1:reservedPopulation},raw,normalized,reserved,finalPopulation:await page.locator('#population-population').inputValue(),measuredProposalSurvivesSelectionEdits:true,predictionBlocked:true,noFallback:true,noPredictOrRevealRequested:true,pageErrors,network,requestBounds:{maxGeneValuesPerGroup:128,maxFeatureMetadata:50,maxInterventionMetadata:32},researcherUsability:'explicitly pending',Safari:'not tested',physicalTouch:'not tested'};
 }catch(e){report={status:'failed',error:String(e),scope:'Real cohort browser engineering only',pageErrors,network};try{await page.screenshot({path:path.join(out,'cohort-failure.png')});}catch{}throw e;}finally{fs.writeFileSync(path.join(out,'real-cohort-browser-qualification.json'),JSON.stringify(report,null,2)+'\n');await context.close();await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
