// Local browser contract test with synthetic owner replies. No biological/usability claim.
// Run with NODE_PATH pointing to an installed Playwright package; no browser download here.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');
const assets=path.join(__dirname,'../metalrobo/wet_lab'),requests=[],errors=[];
const targets=Array.from({length:70},(_,i)=>({target:'TARGET'+String(i+1).padStart(3,'0')}));
const measured={id:'measured-fixture',title:'Measured engineering fixture',family:'measured-cellular-cohort',presentation:'population',features:['FOS','MISSING'],featuresTotal:3,specimens:[{id:'study',title:'Source study'}],populations:[{id:'population',title:'Cells',specimenID:'study',conditionID:'context'},{id:'population2',title:'Second population',specimenID:'study',conditionID:'context'}],conditions:[{id:'context'}],targets,datasetFingerprint:'synthetic-source-hash',observationAccessFingerprint:'synthetic-access-v1',capabilities:{presentation:'population',prediction:false,observationComparison:false,measuredExploration:true}};
const frozen={...measured,id:'frozen-fixture',title:'Existing frozen predictor fixture',family:'learned-cellular-response',targets:[{target:'KNOWN'}],capabilities:{prediction:true,observationComparison:true},observationAccessFingerprint:undefined};
const draft=(assay,id)=>({id,title:id,status:'draft',selection:{assayID:assay.id,specimenID:'study',populationID:'population',conditionID:'context'},genes:['FOS'],targets:['TARGET001'],supportedTargets:['TARGET001'],modelIDs:[assay.id],conditionIDs:['context'],coverage:{canExecute:false,executionReason:'No execution-compatible model.'},axes:[{modelID:assay.id,conditionID:'context',canExecute:false,reason:'No execution-compatible model.',corrections:[{registerCompatibleModel:true}]}]});
let state={revision:0,selection:null,drafts:[draft(frozen,'frozen-draft'),draft(measured,'measured-draft')],operations:[],history:[],datasets:[measured],models:[{...frozen,version:'Frozen predictor'}]};
const server=http.createServer(async(req,res)=>{try{let raw='';for await(const chunk of req)raw+=chunk;const body=raw?JSON.parse(raw):null;const reply=(value,status=200)=>{if(res.destroyed)return;res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value));};
 if(req.url==='/api/assays')return reply([measured,frozen]);
 if(req.url.startsWith('/api/catalog'))return reply(req.url.includes('frozen')?frozen:measured);
 if(req.url==='/api/shared'){if(body){assert.equal(body.action,'selection','Fixture permits only selection updates');assert.equal(body.expectedRevision,state.revision);state={...state,selection:body.selection,revision:state.revision+1};}return reply(state);}
 if(req.url==='/api/readout'){requests.push(body);const q=body.query;if(q.kind==='features'){assert(q.limit<=128);const items=['FOS','JUN','MISSING'].filter(g=>g.includes((q.search||'').toUpperCase())).map(g=>({id:g,title:g}));return reply({items:items.slice(q.offset,q.offset+q.limit),total:items.length});}if(q.kind==='interventions'){assert(q.limit<=64);let items=targets.filter(x=>x.target.includes((q.search||'').toUpperCase())).map(x=>({...x,controlCells:384,outcomeCells:256,supportStatus:'source supported',access:{status:x.target==='TARGET036'?'reserved':'development-open'}}));return reply({items:items.slice(q.offset,q.offset+q.limit),total:items.length,offset:q.offset,limit:q.limit});}
 assert.equal(q.kind,'gene');assert(q.limit<=128);if(body.assayID==='frozen-fixture')return reply({gene:q.gene,units:'log1p(CPM)',modeled:true,arms:[{target:'KNOWN',role:'direct',population:'population',control:1,predicted:2,observed:null,residual:null,controlCells:32,outcomeCells:16,evidence:'MODEL INFERENCE'}],distributionStatus:'Population mean only'});
 assert.equal(q.mode,'measured');assert(q.target,'Measured queries must name a target');assert(['raw_counts','log1p_10000'].includes(q.normalization));const reserved=q.target==='TARGET036',missing=q.gene==='MISSING',vals=missing?[]:Array.from({length:Math.max(0,Math.min(q.limit,384-q.offset))},(_,i)=>q.normalization==='raw_counts'?i%11:(i%11)/10),observed=reserved||missing?[]:vals.slice(0,Math.max(0,256-q.offset));const d={gene:q.gene,units:q.normalization==='raw_counts'?'raw counts':'log1p(count/whole-cell-total*10000)',measured:!missing,modeled:false,access:{status:reserved?'reserved':'development-open'},scope:'Synthetic owner response fixture',distributionStatus:'Bounded measured rows',arms:[{target:q.target,population:body.selection.population,control:missing?null:4.8,observed:reserved||missing?null:5.1,predicted:null,residual:null,controlCells:384,outcomeCells:256,controlValues:vals,observedValues:observed,controlCellIDs:vals.map((_,i)=>'source:control:'+String(i+q.offset)),observedCellIDs:observed.map((_,i)=>'source:treated:'+String(i+q.offset)),evidence:reserved||missing?'UNAVAILABLE':'MEASURED',missingReason:missing?'Gene absent from source panel':reserved?'Reserved outcome access denied':undefined}]};if(q.gene==='FOS'&&q.offset===0)setTimeout(()=>reply(d),350);else reply(d);return;}
 assert(!['/api/predict','/api/reveal'].includes(req.url),'Exploration may not invoke prediction or reveal');const filename=req.url==='/'?'index.html':req.url.slice(1);if(filename==='favicon.ico'){res.writeHead(204);res.end();return;}const data=fs.readFileSync(path.join(assets,filename)).toString().replaceAll('__TOKEN__','fixture-only');res.writeHead(200,{'Content-Type':filename.endsWith('.js')?'text/javascript':filename.endsWith('.css')?'text/css':'text/html'});res.end(data);
 }catch(e){errors.push(String(e));res.writeHead(500);res.end(JSON.stringify({error:String(e)}));}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.NUMILAB_BROWSER_CHANNEL||'chrome'});try{const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#population-readout .measured-distribution').waitFor();assert(await page.locator('#population-predict').isDisabled());assert.match(await page.locator('#population-prediction-reason').innerText(),/Register a model/);const measuredCard=page.locator('.shared-card[data-id=measured-draft]');assert.match(await measuredCard.innerText(),/Proposed RNA program/);assert.match(await measuredCard.innerText(),/No execution-compatible model/);assert.doesNotMatch(await measuredCard.innerText(),/log1p\(CPM\)|fixed measured geometry|objective change = 0/);assert(await measuredCard.getByRole('button',{name:'Seal and execute',exact:true}).isDisabled());assert.match(await page.locator('.shared-card[data-id=frozen-draft]').textContent(),/Reduce mean log1p\(CPM\) of/);assert.equal(await page.locator('#population-interventions button').count(),32);assert.equal(await page.locator('#population-readout circle').count(),256);assert.equal(await page.locator('[data-view-layer=predicted]').isDisabled(),true);if(process.env.NUMILAB_UI_OUTPUT){fs.mkdirSync(process.env.NUMILAB_UI_OUTPUT,{recursive:true});await page.locator('#population-readout').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(process.env.NUMILAB_UI_OUTPUT,'measured-fixture.png')});}
 await page.locator('#population-population').selectOption('population2');await page.waitForFunction(()=>window.populationLab.state.population==='population2');assert(await page.evaluate(()=>!window.populationLab.state.field||window.populationLab.state.field.arms.every(a=>a.population==='population2')),'A previous population readout must not remain under the new selection');await page.waitForFunction(()=>window.populationLab.state.field?.arms[0]?.population==='population2');
 await page.getByRole('button',{name:'Next targets',exact:true}).click();await page.getByRole('button',{name:/TARGET036/}).waitFor();await page.getByRole('button',{name:/TARGET036/}).click();await page.waitForFunction(()=>window.populationLab.state.field?.arms[0]?.target==='TARGET036');assert.equal(await page.locator('#population-readout circle.observed').count(),0);assert.equal(await page.evaluate(()=>window.populationLab.state.field.arms[0].observed),null);assert.match(await page.locator('#population-readout').innerText(),/Reserved outcome access denied/);if(process.env.NUMILAB_UI_OUTPUT){await page.locator('#population-readout').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(process.env.NUMILAB_UI_OUTPUT,'reserved-fixture.png')});}
 await page.getByRole('button',{name:/TARGET033/}).click();await page.waitForFunction(()=>window.populationLab.state.field?.arms[0]?.target==='TARGET033');await page.locator('#population-normalization').selectOption('log1p_10000');await page.waitForFunction(()=>window.populationLab.state.field?.units==='log1p(count/whole-cell-total*10000)');await page.getByRole('button',{name:'Next cell page',exact:true}).click();await page.waitForFunction(()=>window.populationLab.state.valueOffset===128&&window.populationLab.state.field);assert(requests.some(r=>r.query.offset===128&&r.query.normalization==='log1p_10000'));
 await page.locator('#population-gene').fill('MISSING');await page.locator('#population-gene').press('Tab');await page.waitForFunction(()=>window.populationLab.state.field?.gene==='MISSING');assert.equal(await page.locator('#population-readout circle').count(),0);assert.match(await page.locator('#population-readout').innerText(),/Missing measurements are not zero counts/);
 await page.locator('#population-gene').fill('FOS');await page.locator('#population-gene').press('Tab');await page.waitForFunction(()=>!document.getElementById('population-gene').disabled);await page.locator('#population-gene').fill('JUN');await page.waitForFunction(()=>[...document.querySelectorAll('#population-genes option')].some(o=>o.value==='JUN'));await page.locator('#population-gene').press('Tab');await page.waitForFunction(()=>window.populationLab.state.field?.gene==='JUN');await page.waitForTimeout(450);assert.equal(await page.evaluate(()=>window.populationLab.state.field.gene),'JUN','Late FOS reply must not replace JUN');
 await page.locator('#population-assay').selectOption('frozen-fixture');await page.waitForFunction(()=>window.populationLab.state.modelID==='frozen-fixture'&&window.populationLab.state.field?.arms[0]?.target==='KNOWN');assert.equal(await page.locator('#population-predict').isDisabled(),false);assert.equal(await page.locator('#population-cohort-tools').isHidden(),true);assert.equal(await page.evaluate(()=>window.populationLab.state.field.units),'log1p(CPM)');assert.equal(errors.length,0,errors.join('\n'));
 console.log(JSON.stringify({status:'passed',scope:'Synthetic owner-contract browser checks only',checks:['measured proposal identity and unexecuted objective','historical frozen objective label','capability-gated prediction','server metadata pagination','server feature autocomplete beyond initial axis page','bounded control/treated value display','reserved observations closed','normalization and row pagination','missing features not zeros','obsolete readout cancellation','population switch clears previous readout','frozen predictor presentation preserved'],readoutRequests:requests.length,researcherUsability:'pending'},null,2));
 }finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
